!4 XG-TYPE-INTERVAL-001 WHERE 条件判断

//创建表
CREATE TABLE t_table_001a (id INT , c1 INTERVAL YEAR);
CREATE TABLE t_table_001b (id INT , c1 INTERVAL MONTH);
CREATE TABLE t_table_001c (id INT , c1 INTERVAL DAY);
CREATE TABLE t_table_001d (id INT , c1 INTERVAL HOUR);
CREATE TABLE t_table_001e (id INT , c1 INTERVAL MINUTE);
CREATE TABLE t_table_001f (id INT , c1 INTERVAL SECOND);
CREATE TABLE t_table_001g (id INT , c1 INTERVAL YEAR TO MONTH);
CREATE TABLE t_table_001h (id INT , c1 INTERVAL DAY TO HOUR);
CREATE TABLE t_table_001i (id INT , c1 INTERVAL DAY TO MINUTE);
CREATE TABLE t_table_001j (id INT , c1 INTERVAL DAY TO SECOND);
CREATE TABLE t_table_001k (id INT , c1 INTERVAL HOUR TO MINUTE);
CREATE TABLE t_table_001l (id INT , c1 INTERVAL HOUR TO SECOND);
CREATE TABLE t_table_001m (id INT , c1 INTERVAL MINUTE TO SECOND);

//插入数据
INSERT INTO t_table_001a VALUES (1 , '6') , (2 , '7') , (3 , '8') , (4 , '9');
INSERT INTO t_table_001b VALUES (1 , '6') , (2 , '7') , (3 , '8') , (4 , '9');
INSERT INTO t_table_001c VALUES (1 , '6') , (2 , '7') , (3 , '8') , (4 , '9');
INSERT INTO t_table_001d VALUES (1 , '6') , (2 , '7') , (3 , '8') , (4 , '9');
INSERT INTO t_table_001e VALUES (1 , '6') , (2 , '7') , (3 , '8') , (4 , '9');
INSERT INTO t_table_001f VALUES (1 , '6') , (2 , '7') , (3 , '8') , (4 , '9');
INSERT INTO t_table_001g VALUES (1 , '6') , (2 , '7') , (3 , '8') , (4 , '9');
INSERT INTO t_table_001h VALUES (1 , '6') , (2 , '7') , (3 , '8') , (4 , '9');
INSERT INTO t_table_001i VALUES (1 , '6') , (2 , '7') , (3 , '8') , (4 , '9');
INSERT INTO t_table_001j VALUES (1 , '6') , (2 , '7') , (3 , '8') , (4 , '9');
INSERT INTO t_table_001k VALUES (1 , '6') , (2 , '7') , (3 , '8') , (4 , '9');
INSERT INTO t_table_001l VALUES (1 , '6') , (2 , '7') , (3 , '8') , (4 , '9');
INSERT INTO t_table_001m VALUES (1 , '6') , (2 , '7') , (3 , '8') , (4 , '9');

//判断条件数据格式不对应
<预期结果 : 报错>
SELECT id FROM t_table_001a WHERE c1 = 'a';
<预期结果 : 报错>
SELECT id FROM t_table_001b WHERE c1 = 'a';
<预期结果 : 报错>
SELECT id FROM t_table_001c WHERE c1 = 'a';
<预期结果 : 报错>
SELECT id FROM t_table_001d WHERE c1 = 'a';
<预期结果 : 报错>
SELECT id FROM t_table_001e WHERE c1 = 'a';
<预期结果 : 报错>
SELECT id FROM t_table_001f WHERE c1 = 'a';
<预期结果 : 报错>
SELECT id FROM t_table_001g WHERE c1 = 'a';
<预期结果 : 报错>
SELECT id FROM t_table_001h WHERE c1 = 'a';
<预期结果 : 报错>
SELECT id FROM t_table_001i WHERE c1 = 'a';
<预期结果 : 报错>
SELECT id FROM t_table_001j WHERE c1 = 'a';
<预期结果 : 报错>
SELECT id FROM t_table_001k WHERE c1 = 'a';
<预期结果 : 报错>
SELECT id FROM t_table_001l WHERE c1 = 'a';
<预期结果 : 报错>
SELECT id FROM t_table_001m WHERE c1 = 'a';

//判断条件数据类型不统一,指定类型转换,有隐式转换

{{{ 
    隐式转换中,最小类型单元可以向最大类型单元隐式转换,分为年月格式和日时分秒格式两类
    年月格式可以向 INTERVAL YEAR 隐式转换,
    日时分秒格式可以向 INTERVAL DAY 隐式转换
    两类格式中较大类型单元可以向较小类型单元隐式转换
}}}

//年月格式
<预期结果 : 4>
SELECT id FROM t_table_001a WHERE c1 = '9'::INTERVAL YEAR;
<预期结果 : 不报错但无满足结果>
SELECT id FROM t_table_001b WHERE c1 = '9'::INTERVAL YEAR;
<预期结果 : 不报错但无满足结果>
SELECT id FROM t_table_001g WHERE c1 = '9'::INTERVAL YEAR;

//日时分秒格式
<预期结果 : 4>
SELECT id FROM t_table_001c WHERE c1 = '9'::INTERVAL DAY;
<预期结果 : 不报错但无满足结果>
SELECT id FROM t_table_001d WHERE c1 = '9'::INTERVAL DAY;
<预期结果 : 不报错但无满足结果>
SELECT id FROM t_table_001e WHERE c1 = '9'::INTERVAL DAY;
SELECT id FROM t_table_001e WHERE c1 = '9'::INTERVAL HOUR;
<预期结果 : 不报错但无满足结果>
SELECT id FROM t_table_001f WHERE c1 = '9'::INTERVAL DAY;
SELECT id FROM t_table_001f WHERE c1 = '9'::INTERVAL HOUR;
SELECT id FROM t_table_001f WHERE c1 = '9'::INTERVAL MINUTE;
<预期结果 : 不报错但无满足结果>
SELECT id FROM t_table_001h WHERE c1 = '9'::INTERVAL DAY;
<预期结果 : 不报错但无满足结果>
SELECT id FROM t_table_001i WHERE c1 = '9'::INTERVAL DAY;
<预期结果 : 不报错但无满足结果>
SELECT id FROM t_table_001j WHERE c1 = '9'::INTERVAL DAY;
<预期结果 : 不报错但无满足结果>
SELECT id FROM t_table_001k WHERE c1 = '9'::INTERVAL DAY;
<预期结果 : 不报错但无满足结果>
SELECT id FROM t_table_001l WHERE c1 = '9'::INTERVAL DAY;
<预期结果 : 不报错但无满足结果>
SELECT id FROM t_table_001m WHERE c1 = '9'::INTERVAL DAY;

//判断条件数据类型不统一,指定类型转换,无隐式转换

{{{
    年月格式与日时分秒格式之间没有隐式转换,且这两类中最小类型单元无法向较大类型单元隐式转换
}}}

//年月格式
<预期结果 : 报错>
SELECT id FROM t_table_001a WHERE c1 = '9'::INTERVAL DAY;
SELECT id FROM t_table_001a WHERE c1 = '9'::INTERVAL HOUR;
SELECT id FROM t_table_001a WHERE c1 = '9'::INTERVAL MINUTE;
SELECT id FROM t_table_001a WHERE c1 = '9'::INTERVAL SECOND;
<预期结果 : 报错>
SELECT id FROM t_table_001b WHERE c1 = '9'::INTERVAL SECOND;
<预期结果 : 报错>
SELECT id FROM t_table_001g WHERE c1 = '9'::INTERVAL SECOND;

//日时分秒格式
<预期结果 : 报错>
SELECT id FROM t_table_001c WHERE c1 = '9'::INTERVAL HOUR;
SELECT id FROM t_table_001c WHERE c1 = '9'::INTERVAL MINUTE;
SELECT id FROM t_table_001c WHERE c1 = '9'::INTERVAL SECOND;
<预期结果 : 报错>
SELECT id FROM t_table_001d WHERE c1 = '9'::INTERVAL MINUTE;
SELECT id FROM t_table_001d WHERE c1 = '9'::INTERVAL SECOND;
<预期结果 : 报错>
SELECT id FROM t_table_001e WHERE c1 = '9'::INTERVAL SECOND;
<预期结果 : 4>
SELECT id FROM t_table_001f WHERE c1 = '9'::INTERVAL SECOND;
<预期结果 : 报错>
SELECT id FROM t_table_001h WHERE c1 = '9'::INTERVAL SECOND;
<预期结果 : 报错>
SELECT id FROM t_table_001i WHERE c1 = '9'::INTERVAL SECOND;
<预期结果 : 4>
SELECT id FROM t_table_001j WHERE c1 = '9'::INTERVAL SECOND;
<预期结果 : 报错>
SELECT id FROM t_table_001k WHERE c1 = '9'::INTERVAL SECOND;
<预期结果 : 4>
SELECT id FROM t_table_001l WHERE c1 = '9'::INTERVAL SECOND;
<预期结果 : 4>
SELECT id FROM t_table_001m WHERE c1 = '9'::INTERVAL SECOND;

//判断条件数据类型不统一 , 不指定类型转换
<预期结果 : 报错>
SELECT id FROM t_table_001a WHERE c1 = TRUE;
<预期结果 : 报错>
SELECT id FROM t_table_001b WHERE c1 = TRUE;
<预期结果 : 报错>
SELECT id FROM t_table_001c WHERE c1 = TRUE;
<预期结果 : 报错>
SELECT id FROM t_table_001d WHERE c1 = TRUE;
<预期结果 : 报错>
SELECT id FROM t_table_001e WHERE c1 = TRUE;
<预期结果 : 报错>
SELECT id FROM t_table_001f WHERE c1 = TRUE;
<预期结果 : 报错>
SELECT id FROM t_table_001g WHERE c1 = TRUE;
<预期结果 : 报错>
SELECT id FROM t_table_001h WHERE c1 = TRUE;
<预期结果 : 报错>
SELECT id FROM t_table_001i WHERE c1 = TRUE;
<预期结果 : 报错>
SELECT id FROM t_table_001j WHERE c1 = TRUE;
<预期结果 : 报错>
SELECT id FROM t_table_001k WHERE c1 = TRUE;
<预期结果 : 报错>
SELECT id FROM t_table_001l WHERE c1 = TRUE;
<预期结果 : 报错>
SELECT id FROM t_table_001m WHERE c1 = TRUE;

//删除表
DROP TABLE t_table_001a;
DROP TABLE t_table_001b;
DROP TABLE t_table_001c;
DROP TABLE t_table_001d;
DROP TABLE t_table_001e;
DROP TABLE t_table_001f;
DROP TABLE t_table_001g;
DROP TABLE t_table_001h;
DROP TABLE t_table_001i;
DROP TABLE t_table_001j;
DROP TABLE t_table_001k;
DROP TABLE t_table_001l;
DROP TABLE t_table_001m;

!4 XG-TYPE-INTERVAL-002 INTERVAL 类型之间的转换

{{{
    1. 测试 INTERVAL 不同类型之间的转换
    2. 表结构包括内容 : v_min、v_mid、v_max 为 INT 类型,v_min1、v_mid1、v_max1 为 VARCHAR 类型
}}}

//创建范围边界值表
CREATE TABLE t_table_002a (id INT , v_min INTERVAL YEAR , v_mid INTERVAL YEAR , v_max INTERVAL YEAR , v_min1 INTERVAL YEAR , v_mid1 INTERVAL YEAR , v_max1 INTERVAL YEAR);
CREATE TABLE t_table_002b (id INT , v_min INTERVAL MONTH , v_mid INTERVAL MONTH , v_max INTERVAL MONTH , v_min1 INTERVAL MONTH , v_mid1 INTERVAL MONTH , v_max1 INTERVAL MONTH);
CREATE TABLE t_table_002c (id INT , v_min INTERVAL DAY , v_mid INTERVAL DAY , v_max INTERVAL DAY , v_min1 INTERVAL DAY , v_mid1 INTERVAL DAY , v_max1 INTERVAL DAY);
CREATE TABLE t_table_002d (id INT , v_min INTERVAL HOUR , v_mid INTERVAL HOUR , v_max INTERVAL HOUR , v_min1 INTERVAL HOUR , v_mid1 INTERVAL HOUR , v_max1 INTERVAL HOUR);
CREATE TABLE t_table_002e (id INT , v_min INTERVAL MINUTE , v_mid INTERVAL MINUTE , v_max INTERVAL MINUTE , v_min1 INTERVAL MINUTE , v_mid1 INTERVAL MINUTE , v_max1 INTERVAL MINUTE);
CREATE TABLE t_table_002f (id INT , v_min INTERVAL SECOND , v_mid INTERVAL SECOND , v_max INTERVAL SECOND , v_min1 INTERVAL SECOND , v_mid1 INTERVAL SECOND , v_max1 INTERVAL SECOND);
CREATE TABLE t_table_002g (id INT , v_min INTERVAL YEAR TO MONTH , v_mid INTERVAL YEAR TO MONTH , v_max INTERVAL YEAR TO MONTH , v_min1 INTERVAL YEAR TO MONTH , v_mid1 INTERVAL YEAR TO MONTH , v_max1 INTERVAL YEAR TO MONTH);
CREATE TABLE t_table_002h (id INT , v_min INTERVAL DAY TO HOUR , v_mid INTERVAL DAY TO HOUR , v_max INTERVAL DAY TO HOUR , v_min1 INTERVAL DAY TO HOUR , v_mid1 INTERVAL DAY TO HOUR , v_max1 INTERVAL DAY TO HOUR);
CREATE TABLE t_table_002i (id INT , v_min INTERVAL DAY TO MINUTE , v_mid INTERVAL DAY TO MINUTE , v_max INTERVAL DAY TO MINUTE , v_min1 INTERVAL DAY TO MINUTE , v_mid1 INTERVAL DAY TO MINUTE , v_max1 INTERVAL DAY TO MINUTE);
CREATE TABLE t_table_002j (id INT , v_min INTERVAL DAY TO SECOND , v_mid INTERVAL DAY TO SECOND , v_max INTERVAL DAY TO SECOND , v_min1 INTERVAL DAY TO SECOND , v_mid1 INTERVAL DAY TO SECOND , v_max1 INTERVAL DAY TO SECOND);
CREATE TABLE t_table_002k (id INT , v_min INTERVAL HOUR TO MINUTE , v_mid INTERVAL HOUR TO MINUTE , v_max INTERVAL HOUR TO MINUTE , v_min1 INTERVAL HOUR TO MINUTE , v_mid1 INTERVAL HOUR TO MINUTE , v_max1 INTERVAL HOUR TO MINUTE);
CREATE TABLE t_table_002l (id INT , v_min INTERVAL HOUR TO SECOND , v_mid INTERVAL HOUR TO SECOND , v_max INTERVAL HOUR TO SECOND , v_min1 INTERVAL HOUR TO SECOND , v_mid1 INTERVAL HOUR TO SECOND , v_max1 INTERVAL HOUR TO SECOND);
CREATE TABLE t_table_002m (id INT , v_min INTERVAL MINUTE TO SECOND , v_mid INTERVAL MINUTE TO SECOND , v_max INTERVAL MINUTE TO SECOND , v_min1 INTERVAL MINUTE TO SECOND , v_mid1 INTERVAL MINUTE TO SECOND , v_max1 INTERVAL MINUTE TO SECOND);

//插入数据
INSERT INTO t_table_002a VALUES (1 , -999999999 , 9 ,999999999 , '-999999999' , '9' , '999999999');
INSERT INTO t_table_002b VALUES (1 , -2147483647 , 9 ,2147483647 , '-2147483647' , '9' , '2147483647');
INSERT INTO t_table_002c VALUES (1 , -2147483647 , 9 ,2147483647 , '-2147483647' , '9' , '2147483647');
INSERT INTO t_table_002d VALUES (1 , -999999999 , 9 ,999999999 , '-999999999' , '9' , '999999999');
INSERT INTO t_table_002e VALUES (1 , -999999999 , 9 ,999999999 , '-999999999' , '9' , '999999999');
INSERT INTO t_table_002f VALUES (1 , -9223372036854.775808 , 9 , 9223372036854.775807 , '-9223372036854.775808' , '9' , '9223372036854.775807');
INSERT INTO t_table_002g VALUES (1 , NULL , NULL , NULL , '-178956970-0' , '9-0' , '178956970-0');
INSERT INTO t_table_002g VALUES (2 , NULL , NULL , NULL , '0' , '0-9' , '0-11');
INSERT INTO t_table_002h VALUES (1 , NULL , NULL , NULL , '-89478485 0:00:00' , '9 0:00:00' , '89478485 0:00:00');
INSERT INTO t_table_002h VALUES (2 , NULL , NULL , NULL , '-2147483647:00:00' , '9:00:00' , '2147483647:00:00');
INSERT INTO t_table_002i VALUES (1 , NULL , NULL , NULL , '-1491308 0:00:00' , '9 0:00:00' , '1491308 0:00:00');
INSERT INTO t_table_002i VALUES (2 , NULL , NULL , NULL , '-35791394:00:00' , '9:00:00' , '35791394:00:00');
INSERT INTO t_table_002i VALUES (3 , NULL , NULL , NULL , '0' , '0:09:00' , '0:59:00');
INSERT INTO t_table_002j VALUES (1 , NULL , NULL , NULL , '-106751991 0:00:00' , '9 0:00:00' , '106751991 0:00:00');
INSERT INTO t_table_002j VALUES (2 , NULL , NULL , NULL , '-2562047788:00:00' , '9 0:00:00' , '2562047787:00:00');
INSERT INTO t_table_002j VALUES (3 , NULL , NULL , NULL , '0' , '0:09:00' , '0:59:00');
INSERT INTO t_table_002j VALUES (4 , NULL , NULL , NULL , '0' , '0:00:09' , '0:00:60');
INSERT INTO t_table_002k VALUES (1 , NULL , NULL , NULL , '-9999999 0:00:00' , '9 0:00:00' , '9999999 0:00:00');
INSERT INTO t_table_002k VALUES (2 , NULL , NULL , NULL , '0' , '0:09:00' , '0:59:00');
INSERT INTO t_table_002l VALUES (1 , NULL , NULL , NULL , '-2562047788:00:00' , '9:00:00' , '2562047788:00:00');
INSERT INTO t_table_002l VALUES (2 , NULL , NULL , NULL , '0' , '0:09:00' , '0:59:00');
INSERT INTO t_table_002l VALUES (3 , NULL , NULL , NULL , '0' , '0:00:09' , '0:00:60');
INSERT INTO t_table_002m VALUES (1 , NULL , NULL , NULL , '-999999999:00' , '9:00' , '999999999:00');
INSERT INTO t_table_002m VALUES (2 , NULL , NULL , NULL , '0' , '0:00:09' , '0:00:60');

//INTERVAL YEAR 默认精度转换
SELECT v_min::INTERVAL MONTH FROM t_table_002a;
SELECT v_mid::INTERVAL MONTH FROM t_table_002a;
SELECT v_max::INTERVAL MONTH FROM t_table_002a;
SELECT v_min1::INTERVAL MONTH FROM t_table_002a;
SELECT v_mid1::INTERVAL MONTH FROM t_table_002a;
SELECT v_max1::INTERVAL MONTH FROM t_table_002a;
SELECT v_min::INTERVAL DAY FROM t_table_002a;
SELECT v_mid::INTERVAL DAY FROM t_table_002a;
SELECT v_max::INTERVAL DAY FROM t_table_002a;
SELECT v_min1::INTERVAL DAY FROM t_table_002a;
SELECT v_mid1::INTERVAL DAY FROM t_table_002a;
SELECT v_max1::INTERVAL DAY FROM t_table_002a;
SELECT v_min::INTERVAL HOUR FROM t_table_002a;
SELECT v_mid::INTERVAL HOUR FROM t_table_002a;
SELECT v_max::INTERVAL HOUR FROM t_table_002a;
SELECT v_min1::INTERVAL HOUR FROM t_table_002a;
SELECT v_mid1::INTERVAL HOUR FROM t_table_002a;
SELECT v_max1::INTERVAL HOUR FROM t_table_002a;
SELECT v_min::INTERVAL MINUTE FROM t_table_002a;
SELECT v_mid::INTERVAL MINUTE FROM t_table_002a;
SELECT v_max::INTERVAL MINUTE FROM t_table_002a;
SELECT v_min1::INTERVAL MINUTE FROM t_table_002a;
SELECT v_mid1::INTERVAL MINUTE FROM t_table_002a;
SELECT v_max1::INTERVAL MINUTE FROM t_table_002a;
SELECT v_min::INTERVAL SECOND FROM t_table_002a;
SELECT v_mid::INTERVAL SECOND FROM t_table_002a;
SELECT v_max::INTERVAL SECOND FROM t_table_002a;
SELECT v_min1::INTERVAL SECOND FROM t_table_002a;
SELECT v_mid1::INTERVAL SECOND FROM t_table_002a;
SELECT v_max1::INTERVAL SECOND FROM t_table_002a;
SELECT v_min::INTERVAL YEAR TO MONTH FROM t_table_002a;
SELECT v_mid::INTERVAL YEAR TO MONTH FROM t_table_002a;
SELECT v_max::INTERVAL YEAR TO MONTH FROM t_table_002a;
SELECT v_min1::INTERVAL YEAR TO MONTH FROM t_table_002a;
SELECT v_mid1::INTERVAL YEAR TO MONTH FROM t_table_002a;
SELECT v_max1::INTERVAL YEAR TO MONTH FROM t_table_002a;
SELECT v_min::INTERVAL DAY TO HOUR FROM t_table_002a;
SELECT v_mid::INTERVAL DAY TO HOUR FROM t_table_002a;
SELECT v_max::INTERVAL DAY TO HOUR FROM t_table_002a;
SELECT v_min1::INTERVAL DAY TO HOUR FROM t_table_002a;
SELECT v_mid1::INTERVAL DAY TO HOUR FROM t_table_002a;
SELECT v_max1::INTERVAL DAY TO HOUR FROM t_table_002a;
SELECT v_min::INTERVAL DAY TO MINUTE FROM t_table_002a;
SELECT v_mid::INTERVAL DAY TO MINUTE FROM t_table_002a;
SELECT v_max::INTERVAL DAY TO MINUTE FROM t_table_002a;
SELECT v_min1::INTERVAL DAY TO MINUTE FROM t_table_002a;
SELECT v_mid1::INTERVAL DAY TO MINUTE FROM t_table_002a;
SELECT v_max1::INTERVAL DAY TO MINUTE FROM t_table_002a;
SELECT v_min::INTERVAL DAY TO SECOND FROM t_table_002a;
SELECT v_mid::INTERVAL DAY TO SECOND FROM t_table_002a;
SELECT v_max::INTERVAL DAY TO SECOND FROM t_table_002a;
SELECT v_min1::INTERVAL DAY TO SECOND FROM t_table_002a;
SELECT v_mid1::INTERVAL DAY TO SECOND FROM t_table_002a;
SELECT v_max1::INTERVAL DAY TO SECOND FROM t_table_002a;
SELECT v_min::INTERVAL HOUR TO MINUTE FROM t_table_002a;
SELECT v_mid::INTERVAL HOUR TO MINUTE FROM t_table_002a;
SELECT v_max::INTERVAL HOUR TO MINUTE FROM t_table_002a;
SELECT v_min1::INTERVAL HOUR TO MINUTE FROM t_table_002a;
SELECT v_mid1::INTERVAL HOUR TO MINUTE FROM t_table_002a;
SELECT v_max1::INTERVAL HOUR TO MINUTE FROM t_table_002a;
SELECT v_min::INTERVAL HOUR TO SECOND FROM t_table_002a;
SELECT v_mid::INTERVAL HOUR TO SECOND FROM t_table_002a;
SELECT v_max::INTERVAL HOUR TO SECOND FROM t_table_002a;
SELECT v_min1::INTERVAL HOUR TO SECOND FROM t_table_002a;
SELECT v_mid1::INTERVAL HOUR TO SECOND FROM t_table_002a;
SELECT v_max1::INTERVAL HOUR TO SECOND FROM t_table_002a;
SELECT v_min::INTERVAL MINUTE TO SECOND FROM t_table_002a;
SELECT v_mid::INTERVAL MINUTE TO SECOND FROM t_table_002a;
SELECT v_max::INTERVAL MINUTE TO SECOND FROM t_table_002a;
SELECT v_min1::INTERVAL MINUTE TO SECOND FROM t_table_002a;
SELECT v_mid1::INTERVAL MINUTE TO SECOND FROM t_table_002a;
SELECT v_max1::INTERVAL MINUTE TO SECOND FROM t_table_002a;

//INTERVAL MONTH 默认精度转换
SELECT v_min::INTERVAL YEAR FROM t_table_002b;
SELECT v_mid::INTERVAL YEAR FROM t_table_002b;
SELECT v_max::INTERVAL YEAR FROM t_table_002b;
SELECT v_min1::INTERVAL YEAR FROM t_table_002b;
SELECT v_mid1::INTERVAL YEAR FROM t_table_002b;
SELECT v_max1::INTERVAL YEAR FROM t_table_002b;
SELECT v_min::INTERVAL DAY FROM t_table_002b;
SELECT v_mid::INTERVAL DAY FROM t_table_002b;
SELECT v_max::INTERVAL DAY FROM t_table_002b;
SELECT v_min1::INTERVAL DAY FROM t_table_002b;
SELECT v_mid1::INTERVAL DAY FROM t_table_002b;
SELECT v_max1::INTERVAL DAY FROM t_table_002b;
SELECT v_min::INTERVAL HOUR FROM t_table_002b;
SELECT v_mid::INTERVAL HOUR FROM t_table_002b;
SELECT v_max::INTERVAL HOUR FROM t_table_002b;
SELECT v_min1::INTERVAL HOUR FROM t_table_002b;
SELECT v_mid1::INTERVAL HOUR FROM t_table_002b;
SELECT v_max1::INTERVAL HOUR FROM t_table_002b;
SELECT v_min::INTERVAL MINUTE FROM t_table_002b;
SELECT v_mid::INTERVAL MINUTE FROM t_table_002b;
SELECT v_max::INTERVAL MINUTE FROM t_table_002b;
SELECT v_min1::INTERVAL MINUTE FROM t_table_002b;
SELECT v_mid1::INTERVAL MINUTE FROM t_table_002b;
SELECT v_max1::INTERVAL MINUTE FROM t_table_002b;
SELECT v_min::INTERVAL SECOND FROM t_table_002b;
SELECT v_mid::INTERVAL SECOND FROM t_table_002b;
SELECT v_max::INTERVAL SECOND FROM t_table_002b;
SELECT v_min1::INTERVAL SECOND FROM t_table_002b;
SELECT v_mid1::INTERVAL SECOND FROM t_table_002b;
SELECT v_max1::INTERVAL SECOND FROM t_table_002b;
SELECT v_min::INTERVAL YEAR TO MONTH FROM t_table_002b;
SELECT v_mid::INTERVAL YEAR TO MONTH FROM t_table_002b;
SELECT v_max::INTERVAL YEAR TO MONTH FROM t_table_002b;
SELECT v_min1::INTERVAL YEAR TO MONTH FROM t_table_002b;
SELECT v_mid1::INTERVAL YEAR TO MONTH FROM t_table_002b;
SELECT v_max1::INTERVAL YEAR TO MONTH FROM t_table_002b;
SELECT v_min::INTERVAL DAY TO HOUR FROM t_table_002b;
SELECT v_mid::INTERVAL DAY TO HOUR FROM t_table_002b;
SELECT v_max::INTERVAL DAY TO HOUR FROM t_table_002b;
SELECT v_min1::INTERVAL DAY TO HOUR FROM t_table_002b;
SELECT v_mid1::INTERVAL DAY TO HOUR FROM t_table_002b;
SELECT v_max1::INTERVAL DAY TO HOUR FROM t_table_002b;
SELECT v_min::INTERVAL DAY TO MINUTE FROM t_table_002b;
SELECT v_mid::INTERVAL DAY TO MINUTE FROM t_table_002b;
SELECT v_max::INTERVAL DAY TO MINUTE FROM t_table_002b;
SELECT v_min1::INTERVAL DAY TO MINUTE FROM t_table_002b;
SELECT v_mid1::INTERVAL DAY TO MINUTE FROM t_table_002b;
SELECT v_max1::INTERVAL DAY TO MINUTE FROM t_table_002b;
SELECT v_min::INTERVAL DAY TO SECOND FROM t_table_002b;
SELECT v_mid::INTERVAL DAY TO SECOND FROM t_table_002b;
SELECT v_max::INTERVAL DAY TO SECOND FROM t_table_002b;
SELECT v_min1::INTERVAL DAY TO SECOND FROM t_table_002b;
SELECT v_mid1::INTERVAL DAY TO SECOND FROM t_table_002b;
SELECT v_max1::INTERVAL DAY TO SECOND FROM t_table_002b;
SELECT v_min::INTERVAL HOUR TO MINUTE FROM t_table_002b;
SELECT v_mid::INTERVAL HOUR TO MINUTE FROM t_table_002b;
SELECT v_max::INTERVAL HOUR TO MINUTE FROM t_table_002b;
SELECT v_min1::INTERVAL HOUR TO MINUTE FROM t_table_002b;
SELECT v_mid1::INTERVAL HOUR TO MINUTE FROM t_table_002b;
SELECT v_max1::INTERVAL HOUR TO MINUTE FROM t_table_002b;
SELECT v_min::INTERVAL HOUR TO SECOND FROM t_table_002b;
SELECT v_mid::INTERVAL HOUR TO SECOND FROM t_table_002b;
SELECT v_max::INTERVAL HOUR TO SECOND FROM t_table_002b;
SELECT v_min1::INTERVAL HOUR TO SECOND FROM t_table_002b;
SELECT v_mid1::INTERVAL HOUR TO SECOND FROM t_table_002b;
SELECT v_max1::INTERVAL HOUR TO SECOND FROM t_table_002b;
SELECT v_min::INTERVAL MINUTE TO SECOND FROM t_table_002b;
SELECT v_mid::INTERVAL MINUTE TO SECOND FROM t_table_002b;
SELECT v_max::INTERVAL MINUTE TO SECOND FROM t_table_002b;
SELECT v_min1::INTERVAL MINUTE TO SECOND FROM t_table_002b;
SELECT v_mid1::INTERVAL MINUTE TO SECOND FROM t_table_002b;
SELECT v_max1::INTERVAL MINUTE TO SECOND FROM t_table_002b;

//INTERVAL DAY 默认精度转换
SELECT v_min::INTERVAL YEAR FROM t_table_002c;
SELECT v_mid::INTERVAL YEAR FROM t_table_002c;
SELECT v_max::INTERVAL YEAR FROM t_table_002c;
SELECT v_min1::INTERVAL YEAR FROM t_table_002c;
SELECT v_mid1::INTERVAL YEAR FROM t_table_002c;
SELECT v_max1::INTERVAL YEAR FROM t_table_002c;
SELECT v_min::INTERVAL MONTH FROM t_table_002c;
SELECT v_mid::INTERVAL MONTH FROM t_table_002c;
SELECT v_max::INTERVAL MONTH FROM t_table_002c;
SELECT v_min1::INTERVAL MONTH FROM t_table_002c;
SELECT v_mid1::INTERVAL MONTH FROM t_table_002c;
SELECT v_max1::INTERVAL MONTH FROM t_table_002c;
SELECT v_min::INTERVAL HOUR FROM t_table_002c;
SELECT v_mid::INTERVAL HOUR FROM t_table_002c;
SELECT v_max::INTERVAL HOUR FROM t_table_002c;
SELECT v_min1::INTERVAL HOUR FROM t_table_002c;
SELECT v_mid1::INTERVAL HOUR FROM t_table_002c;
SELECT v_max1::INTERVAL HOUR FROM t_table_002c;
SELECT v_min::INTERVAL MINUTE FROM t_table_002c;
SELECT v_mid::INTERVAL MINUTE FROM t_table_002c;
SELECT v_max::INTERVAL MINUTE FROM t_table_002c;
SELECT v_min1::INTERVAL MINUTE FROM t_table_002c;
SELECT v_mid1::INTERVAL MINUTE FROM t_table_002c;
SELECT v_max1::INTERVAL MINUTE FROM t_table_002c;
SELECT v_min::INTERVAL SECOND FROM t_table_002c;
SELECT v_mid::INTERVAL SECOND FROM t_table_002c;
SELECT v_max::INTERVAL SECOND FROM t_table_002c;
SELECT v_min1::INTERVAL SECOND FROM t_table_002c;
SELECT v_mid1::INTERVAL SECOND FROM t_table_002c;
SELECT v_max1::INTERVAL SECOND FROM t_table_002c;
SELECT v_min::INTERVAL YEAR TO MONTH FROM t_table_002c;
SELECT v_mid::INTERVAL YEAR TO MONTH FROM t_table_002c;
SELECT v_max::INTERVAL YEAR TO MONTH FROM t_table_002c;
SELECT v_min1::INTERVAL YEAR TO MONTH FROM t_table_002c;
SELECT v_mid1::INTERVAL YEAR TO MONTH FROM t_table_002c;
SELECT v_max1::INTERVAL YEAR TO MONTH FROM t_table_002c;
SELECT v_min::INTERVAL DAY TO HOUR FROM t_table_002c;
SELECT v_mid::INTERVAL DAY TO HOUR FROM t_table_002c;
SELECT v_max::INTERVAL DAY TO HOUR FROM t_table_002c;
SELECT v_min1::INTERVAL DAY TO HOUR FROM t_table_002c;
SELECT v_mid1::INTERVAL DAY TO HOUR FROM t_table_002c;
SELECT v_max1::INTERVAL DAY TO HOUR FROM t_table_002c;
SELECT v_min::INTERVAL DAY TO MINUTE FROM t_table_002c;
SELECT v_mid::INTERVAL DAY TO MINUTE FROM t_table_002c;
SELECT v_max::INTERVAL DAY TO MINUTE FROM t_table_002c;
SELECT v_min1::INTERVAL DAY TO MINUTE FROM t_table_002c;
SELECT v_mid1::INTERVAL DAY TO MINUTE FROM t_table_002c;
SELECT v_max1::INTERVAL DAY TO MINUTE FROM t_table_002c;
SELECT v_min::INTERVAL DAY TO SECOND FROM t_table_002c;
SELECT v_mid::INTERVAL DAY TO SECOND FROM t_table_002c;
SELECT v_max::INTERVAL DAY TO SECOND FROM t_table_002c;
SELECT v_min1::INTERVAL DAY TO SECOND FROM t_table_002c;
SELECT v_mid1::INTERVAL DAY TO SECOND FROM t_table_002c;
SELECT v_max1::INTERVAL DAY TO SECOND FROM t_table_002c;
SELECT v_min::INTERVAL HOUR TO MINUTE FROM t_table_002c;
SELECT v_mid::INTERVAL HOUR TO MINUTE FROM t_table_002c;
SELECT v_max::INTERVAL HOUR TO MINUTE FROM t_table_002c;
SELECT v_min1::INTERVAL HOUR TO MINUTE FROM t_table_002c;
SELECT v_mid1::INTERVAL HOUR TO MINUTE FROM t_table_002c;
SELECT v_max1::INTERVAL HOUR TO MINUTE FROM t_table_002c;
SELECT v_min::INTERVAL HOUR TO SECOND FROM t_table_002c;
SELECT v_mid::INTERVAL HOUR TO SECOND FROM t_table_002c;
SELECT v_max::INTERVAL HOUR TO SECOND FROM t_table_002c;
SELECT v_min1::INTERVAL HOUR TO SECOND FROM t_table_002c;
SELECT v_mid1::INTERVAL HOUR TO SECOND FROM t_table_002c;
SELECT v_max1::INTERVAL HOUR TO SECOND FROM t_table_002c;
SELECT v_min::INTERVAL MINUTE TO SECOND FROM t_table_002c;
SELECT v_mid::INTERVAL MINUTE TO SECOND FROM t_table_002c;
SELECT v_max::INTERVAL MINUTE TO SECOND FROM t_table_002c;
SELECT v_min1::INTERVAL MINUTE TO SECOND FROM t_table_002c;
SELECT v_mid1::INTERVAL MINUTE TO SECOND FROM t_table_002c;
SELECT v_max1::INTERVAL MINUTE TO SECOND FROM t_table_002c;

//INTERVAL HOUR 默认精度转换
SELECT v_min::INTERVAL YEAR FROM t_table_002d;
SELECT v_mid::INTERVAL YEAR FROM t_table_002d;
SELECT v_max::INTERVAL YEAR FROM t_table_002d;
SELECT v_min1::INTERVAL YEAR FROM t_table_002d;
SELECT v_mid1::INTERVAL YEAR FROM t_table_002d;
SELECT v_max1::INTERVAL YEAR FROM t_table_002d;
SELECT v_min::INTERVAL MONTH FROM t_table_002d;
SELECT v_mid::INTERVAL MONTH FROM t_table_002d;
SELECT v_max::INTERVAL MONTH FROM t_table_002d;
SELECT v_min1::INTERVAL MONTH FROM t_table_002d;
SELECT v_mid1::INTERVAL MONTH FROM t_table_002d;
SELECT v_max1::INTERVAL MONTH FROM t_table_002d;
SELECT v_min::INTERVAL DAY FROM t_table_002d;
SELECT v_mid::INTERVAL DAY FROM t_table_002d;
SELECT v_max::INTERVAL DAY FROM t_table_002d;
SELECT v_min1::INTERVAL DAY FROM t_table_002d;
SELECT v_mid1::INTERVAL DAY FROM t_table_002d;
SELECT v_max1::INTERVAL DAY FROM t_table_002d;
SELECT v_min::INTERVAL MINUTE FROM t_table_002d;
SELECT v_mid::INTERVAL MINUTE FROM t_table_002d;
SELECT v_max::INTERVAL MINUTE FROM t_table_002d;
SELECT v_min1::INTERVAL MINUTE FROM t_table_002d;
SELECT v_mid1::INTERVAL MINUTE FROM t_table_002d;
SELECT v_max1::INTERVAL MINUTE FROM t_table_002d;
SELECT v_min::INTERVAL SECOND FROM t_table_002d;
SELECT v_mid::INTERVAL SECOND FROM t_table_002d;
SELECT v_max::INTERVAL SECOND FROM t_table_002d;
SELECT v_min1::INTERVAL SECOND FROM t_table_002d;
SELECT v_mid1::INTERVAL SECOND FROM t_table_002d;
SELECT v_max1::INTERVAL SECOND FROM t_table_002d;
SELECT v_min::INTERVAL YEAR TO MONTH FROM t_table_002d;
SELECT v_mid::INTERVAL YEAR TO MONTH FROM t_table_002d;
SELECT v_max::INTERVAL YEAR TO MONTH FROM t_table_002d;
SELECT v_min1::INTERVAL YEAR TO MONTH FROM t_table_002d;
SELECT v_mid1::INTERVAL YEAR TO MONTH FROM t_table_002d;
SELECT v_max1::INTERVAL YEAR TO MONTH FROM t_table_002d;
SELECT v_min::INTERVAL DAY TO HOUR FROM t_table_002d;
SELECT v_mid::INTERVAL DAY TO HOUR FROM t_table_002d;
SELECT v_max::INTERVAL DAY TO HOUR FROM t_table_002d;
SELECT v_min1::INTERVAL DAY TO HOUR FROM t_table_002d;
SELECT v_mid1::INTERVAL DAY TO HOUR FROM t_table_002d;
SELECT v_max1::INTERVAL DAY TO HOUR FROM t_table_002d;
SELECT v_min::INTERVAL DAY TO MINUTE FROM t_table_002d;
SELECT v_mid::INTERVAL DAY TO MINUTE FROM t_table_002d;
SELECT v_max::INTERVAL DAY TO MINUTE FROM t_table_002d;
SELECT v_min1::INTERVAL DAY TO MINUTE FROM t_table_002d;
SELECT v_mid1::INTERVAL DAY TO MINUTE FROM t_table_002d;
SELECT v_max1::INTERVAL DAY TO MINUTE FROM t_table_002d;
SELECT v_min::INTERVAL DAY TO SECOND FROM t_table_002d;
SELECT v_mid::INTERVAL DAY TO SECOND FROM t_table_002d;
SELECT v_max::INTERVAL DAY TO SECOND FROM t_table_002d;
SELECT v_min1::INTERVAL DAY TO SECOND FROM t_table_002d;
SELECT v_mid1::INTERVAL DAY TO SECOND FROM t_table_002d;
SELECT v_max1::INTERVAL DAY TO SECOND FROM t_table_002d;
SELECT v_min::INTERVAL HOUR TO MINUTE FROM t_table_002d;
SELECT v_mid::INTERVAL HOUR TO MINUTE FROM t_table_002d;
SELECT v_max::INTERVAL HOUR TO MINUTE FROM t_table_002d;
SELECT v_min1::INTERVAL HOUR TO MINUTE FROM t_table_002d;
SELECT v_mid1::INTERVAL HOUR TO MINUTE FROM t_table_002d;
SELECT v_max1::INTERVAL HOUR TO MINUTE FROM t_table_002d;
SELECT v_min::INTERVAL HOUR TO SECOND FROM t_table_002d;
SELECT v_mid::INTERVAL HOUR TO SECOND FROM t_table_002d;
SELECT v_max::INTERVAL HOUR TO SECOND FROM t_table_002d;
SELECT v_min1::INTERVAL HOUR TO SECOND FROM t_table_002d;
SELECT v_mid1::INTERVAL HOUR TO SECOND FROM t_table_002d;
SELECT v_max1::INTERVAL HOUR TO SECOND FROM t_table_002d;
SELECT v_min::INTERVAL MINUTE TO SECOND FROM t_table_002d;
SELECT v_mid::INTERVAL MINUTE TO SECOND FROM t_table_002d;
SELECT v_max::INTERVAL MINUTE TO SECOND FROM t_table_002d;
SELECT v_min1::INTERVAL MINUTE TO SECOND FROM t_table_002d;
SELECT v_mid1::INTERVAL MINUTE TO SECOND FROM t_table_002d;
SELECT v_max1::INTERVAL MINUTE TO SECOND FROM t_table_002d;

//INTERVAL MINUTE 默认精度转换
SELECT v_min::INTERVAL YEAR FROM t_table_002e;
SELECT v_mid::INTERVAL YEAR FROM t_table_002e;
SELECT v_max::INTERVAL YEAR FROM t_table_002e;
SELECT v_min1::INTERVAL YEAR FROM t_table_002e;
SELECT v_mid1::INTERVAL YEAR FROM t_table_002e;
SELECT v_max1::INTERVAL YEAR FROM t_table_002e;
SELECT v_min::INTERVAL MONTH FROM t_table_002e;
SELECT v_mid::INTERVAL MONTH FROM t_table_002e;
SELECT v_max::INTERVAL MONTH FROM t_table_002e;
SELECT v_min1::INTERVAL MONTH FROM t_table_002e;
SELECT v_mid1::INTERVAL MONTH FROM t_table_002e;
SELECT v_max1::INTERVAL MONTH FROM t_table_002e;
SELECT v_min::INTERVAL DAY FROM t_table_002e;
SELECT v_mid::INTERVAL DAY FROM t_table_002e;
SELECT v_max::INTERVAL DAY FROM t_table_002e;
SELECT v_min1::INTERVAL DAY FROM t_table_002e;
SELECT v_mid1::INTERVAL DAY FROM t_table_002e;
SELECT v_max1::INTERVAL DAY FROM t_table_002e;
SELECT v_min::INTERVAL HOUR FROM t_table_002e;
SELECT v_mid::INTERVAL HOUR FROM t_table_002e;
SELECT v_max::INTERVAL HOUR FROM t_table_002e;
SELECT v_min1::INTERVAL HOUR FROM t_table_002e;
SELECT v_mid1::INTERVAL HOUR FROM t_table_002e;
SELECT v_max1::INTERVAL HOUR FROM t_table_002e;
SELECT v_min::INTERVAL SECOND FROM t_table_002e;
SELECT v_mid::INTERVAL SECOND FROM t_table_002e;
SELECT v_max::INTERVAL SECOND FROM t_table_002e;
SELECT v_min1::INTERVAL SECOND FROM t_table_002e;
SELECT v_mid1::INTERVAL SECOND FROM t_table_002e;
SELECT v_max1::INTERVAL SECOND FROM t_table_002e;
SELECT v_min::INTERVAL YEAR TO MONTH FROM t_table_002e;
SELECT v_mid::INTERVAL YEAR TO MONTH FROM t_table_002e;
SELECT v_max::INTERVAL YEAR TO MONTH FROM t_table_002e;
SELECT v_min1::INTERVAL YEAR TO MONTH FROM t_table_002e;
SELECT v_mid1::INTERVAL YEAR TO MONTH FROM t_table_002e;
SELECT v_max1::INTERVAL YEAR TO MONTH FROM t_table_002e;
SELECT v_min::INTERVAL DAY TO HOUR FROM t_table_002e;
SELECT v_mid::INTERVAL DAY TO HOUR FROM t_table_002e;
SELECT v_max::INTERVAL DAY TO HOUR FROM t_table_002e;
SELECT v_min1::INTERVAL DAY TO HOUR FROM t_table_002e;
SELECT v_mid1::INTERVAL DAY TO HOUR FROM t_table_002e;
SELECT v_max1::INTERVAL DAY TO HOUR FROM t_table_002e;
SELECT v_min::INTERVAL DAY TO MINUTE FROM t_table_002e;
SELECT v_mid::INTERVAL DAY TO MINUTE FROM t_table_002e;
SELECT v_max::INTERVAL DAY TO MINUTE FROM t_table_002e;
SELECT v_min1::INTERVAL DAY TO MINUTE FROM t_table_002e;
SELECT v_mid1::INTERVAL DAY TO MINUTE FROM t_table_002e;
SELECT v_max1::INTERVAL DAY TO MINUTE FROM t_table_002e;
SELECT v_min::INTERVAL DAY TO SECOND FROM t_table_002e;
SELECT v_mid::INTERVAL DAY TO SECOND FROM t_table_002e;
SELECT v_max::INTERVAL DAY TO SECOND FROM t_table_002e;
SELECT v_min1::INTERVAL DAY TO SECOND FROM t_table_002e;
SELECT v_mid1::INTERVAL DAY TO SECOND FROM t_table_002e;
SELECT v_max1::INTERVAL DAY TO SECOND FROM t_table_002e;
SELECT v_min::INTERVAL HOUR TO MINUTE FROM t_table_002e;
SELECT v_mid::INTERVAL HOUR TO MINUTE FROM t_table_002e;
SELECT v_max::INTERVAL HOUR TO MINUTE FROM t_table_002e;
SELECT v_min1::INTERVAL HOUR TO MINUTE FROM t_table_002e;
SELECT v_mid1::INTERVAL HOUR TO MINUTE FROM t_table_002e;
SELECT v_max1::INTERVAL HOUR TO MINUTE FROM t_table_002e;
SELECT v_min::INTERVAL HOUR TO SECOND FROM t_table_002e;
SELECT v_mid::INTERVAL HOUR TO SECOND FROM t_table_002e;
SELECT v_max::INTERVAL HOUR TO SECOND FROM t_table_002e;
SELECT v_min1::INTERVAL HOUR TO SECOND FROM t_table_002e;
SELECT v_mid1::INTERVAL HOUR TO SECOND FROM t_table_002e;
SELECT v_max1::INTERVAL HOUR TO SECOND FROM t_table_002e;
SELECT v_min::INTERVAL MINUTE TO SECOND FROM t_table_002e;
SELECT v_mid::INTERVAL MINUTE TO SECOND FROM t_table_002e;
SELECT v_max::INTERVAL MINUTE TO SECOND FROM t_table_002e;
SELECT v_min1::INTERVAL MINUTE TO SECOND FROM t_table_002e;
SELECT v_mid1::INTERVAL MINUTE TO SECOND FROM t_table_002e;
SELECT v_max1::INTERVAL MINUTE TO SECOND FROM t_table_002e;

//INTERVAL SECOND 默认精度转换
SELECT v_min::INTERVAL YEAR FROM t_table_002f;
SELECT v_mid::INTERVAL YEAR FROM t_table_002f;
SELECT v_max::INTERVAL YEAR FROM t_table_002f;
SELECT v_min1::INTERVAL YEAR FROM t_table_002f;
SELECT v_mid1::INTERVAL YEAR FROM t_table_002f;
SELECT v_max1::INTERVAL YEAR FROM t_table_002f;
SELECT v_min::INTERVAL MONTH FROM t_table_002f;
SELECT v_mid::INTERVAL MONTH FROM t_table_002f;
SELECT v_max::INTERVAL MONTH FROM t_table_002f;
SELECT v_min1::INTERVAL MONTH FROM t_table_002f;
SELECT v_mid1::INTERVAL MONTH FROM t_table_002f;
SELECT v_max1::INTERVAL MONTH FROM t_table_002f;
SELECT v_min::INTERVAL DAY FROM t_table_002f;
SELECT v_mid::INTERVAL DAY FROM t_table_002f;
SELECT v_max::INTERVAL DAY FROM t_table_002f;
SELECT v_min1::INTERVAL DAY FROM t_table_002f;
SELECT v_mid1::INTERVAL DAY FROM t_table_002f;
SELECT v_max1::INTERVAL DAY FROM t_table_002f;
SELECT v_min::INTERVAL HOUR FROM t_table_002f;
SELECT v_mid::INTERVAL HOUR FROM t_table_002f;
SELECT v_max::INTERVAL HOUR FROM t_table_002f;
SELECT v_min1::INTERVAL HOUR FROM t_table_002f;
SELECT v_mid1::INTERVAL HOUR FROM t_table_002f;
SELECT v_max1::INTERVAL HOUR FROM t_table_002f;
SELECT v_min::INTERVAL MINUTE FROM t_table_002f;
SELECT v_mid::INTERVAL MINUTE FROM t_table_002f;
SELECT v_max::INTERVAL MINUTE FROM t_table_002f;
SELECT v_min1::INTERVAL MINUTE FROM t_table_002f;
SELECT v_mid1::INTERVAL MINUTE FROM t_table_002f;
SELECT v_max1::INTERVAL MINUTE FROM t_table_002f;
SELECT v_min::INTERVAL YEAR TO MONTH FROM t_table_002f;
SELECT v_mid::INTERVAL YEAR TO MONTH FROM t_table_002f;
SELECT v_max::INTERVAL YEAR TO MONTH FROM t_table_002f;
SELECT v_min1::INTERVAL YEAR TO MONTH FROM t_table_002f;
SELECT v_mid1::INTERVAL YEAR TO MONTH FROM t_table_002f;
SELECT v_max1::INTERVAL YEAR TO MONTH FROM t_table_002f;
SELECT v_min::INTERVAL DAY TO HOUR FROM t_table_002f;
SELECT v_mid::INTERVAL DAY TO HOUR FROM t_table_002f;
SELECT v_max::INTERVAL DAY TO HOUR FROM t_table_002f;
SELECT v_min1::INTERVAL DAY TO HOUR FROM t_table_002f;
SELECT v_mid1::INTERVAL DAY TO HOUR FROM t_table_002f;
SELECT v_max1::INTERVAL DAY TO HOUR FROM t_table_002f;
SELECT v_min::INTERVAL DAY TO MINUTE FROM t_table_002f;
SELECT v_mid::INTERVAL DAY TO MINUTE FROM t_table_002f;
SELECT v_max::INTERVAL DAY TO MINUTE FROM t_table_002f;
SELECT v_min1::INTERVAL DAY TO MINUTE FROM t_table_002f;
SELECT v_mid1::INTERVAL DAY TO MINUTE FROM t_table_002f;
SELECT v_max1::INTERVAL DAY TO MINUTE FROM t_table_002f;
SELECT v_min::INTERVAL DAY TO SECOND FROM t_table_002f;
SELECT v_mid::INTERVAL DAY TO SECOND FROM t_table_002f;
SELECT v_max::INTERVAL DAY TO SECOND FROM t_table_002f;
SELECT v_min1::INTERVAL DAY TO SECOND FROM t_table_002f;
SELECT v_mid1::INTERVAL DAY TO SECOND FROM t_table_002f;
SELECT v_max1::INTERVAL DAY TO SECOND FROM t_table_002f;
SELECT v_min::INTERVAL HOUR TO MINUTE FROM t_table_002f;
SELECT v_mid::INTERVAL HOUR TO MINUTE FROM t_table_002f;
SELECT v_max::INTERVAL HOUR TO MINUTE FROM t_table_002f;
SELECT v_min1::INTERVAL HOUR TO MINUTE FROM t_table_002f;
SELECT v_mid1::INTERVAL HOUR TO MINUTE FROM t_table_002f;
SELECT v_max1::INTERVAL HOUR TO MINUTE FROM t_table_002f;
SELECT v_min::INTERVAL HOUR TO SECOND FROM t_table_002f;
SELECT v_mid::INTERVAL HOUR TO SECOND FROM t_table_002f;
SELECT v_max::INTERVAL HOUR TO SECOND FROM t_table_002f;
SELECT v_min1::INTERVAL HOUR TO SECOND FROM t_table_002f;
SELECT v_mid1::INTERVAL HOUR TO SECOND FROM t_table_002f;
SELECT v_max1::INTERVAL HOUR TO SECOND FROM t_table_002f;
SELECT v_min::INTERVAL MINUTE TO SECOND FROM t_table_002f;
SELECT v_mid::INTERVAL MINUTE TO SECOND FROM t_table_002f;
SELECT v_max::INTERVAL MINUTE TO SECOND FROM t_table_002f;
SELECT v_min1::INTERVAL MINUTE TO SECOND FROM t_table_002f;
SELECT v_mid1::INTERVAL MINUTE TO SECOND FROM t_table_002f;
SELECT v_max1::INTERVAL MINUTE TO SECOND FROM t_table_002f;

//INTERVAL YEAR TO MONTH 默认精度转换
SELECT v_min::INTERVAL YEAR FROM t_table_002g;
SELECT v_mid::INTERVAL YEAR FROM t_table_002g;
SELECT v_max::INTERVAL YEAR FROM t_table_002g;
SELECT v_min1::INTERVAL YEAR FROM t_table_002g;
SELECT v_mid1::INTERVAL YEAR FROM t_table_002g;
SELECT v_max1::INTERVAL YEAR FROM t_table_002g;
SELECT v_min::INTERVAL MONTH FROM t_table_002g;
SELECT v_mid::INTERVAL MONTH FROM t_table_002g;
SELECT v_max::INTERVAL MONTH FROM t_table_002g;
SELECT v_min1::INTERVAL MONTH FROM t_table_002g;
SELECT v_mid1::INTERVAL MONTH FROM t_table_002g;
SELECT v_max1::INTERVAL MONTH FROM t_table_002g;
SELECT v_min::INTERVAL DAY FROM t_table_002g;
SELECT v_mid::INTERVAL DAY FROM t_table_002g;
SELECT v_max::INTERVAL DAY FROM t_table_002g;
SELECT v_min1::INTERVAL DAY FROM t_table_002g;
SELECT v_mid1::INTERVAL DAY FROM t_table_002g;
SELECT v_max1::INTERVAL DAY FROM t_table_002g;
SELECT v_min::INTERVAL HOUR FROM t_table_002g;
SELECT v_mid::INTERVAL HOUR FROM t_table_002g;
SELECT v_max::INTERVAL HOUR FROM t_table_002g;
SELECT v_min1::INTERVAL HOUR FROM t_table_002g;
SELECT v_mid1::INTERVAL HOUR FROM t_table_002g;
SELECT v_max1::INTERVAL HOUR FROM t_table_002g;
SELECT v_min::INTERVAL MINUTE FROM t_table_002g;
SELECT v_mid::INTERVAL MINUTE FROM t_table_002g;
SELECT v_max::INTERVAL MINUTE FROM t_table_002g;
SELECT v_min1::INTERVAL MINUTE FROM t_table_002g;
SELECT v_mid1::INTERVAL MINUTE FROM t_table_002g;
SELECT v_max1::INTERVAL MINUTE FROM t_table_002g;
SELECT v_min::INTERVAL SECOND FROM t_table_002g;
SELECT v_mid::INTERVAL SECOND FROM t_table_002g;
SELECT v_max::INTERVAL SECOND FROM t_table_002g;
SELECT v_min1::INTERVAL SECOND FROM t_table_002g;
SELECT v_mid1::INTERVAL SECOND FROM t_table_002g;
SELECT v_max1::INTERVAL SECOND FROM t_table_002g;
SELECT v_min::INTERVAL DAY TO HOUR FROM t_table_002g;
SELECT v_mid::INTERVAL DAY TO HOUR FROM t_table_002g;
SELECT v_max::INTERVAL DAY TO HOUR FROM t_table_002g;
SELECT v_min1::INTERVAL DAY TO HOUR FROM t_table_002g;
SELECT v_mid1::INTERVAL DAY TO HOUR FROM t_table_002g;
SELECT v_max1::INTERVAL DAY TO HOUR FROM t_table_002g;
SELECT v_min::INTERVAL DAY TO MINUTE FROM t_table_002g;
SELECT v_mid::INTERVAL DAY TO MINUTE FROM t_table_002g;
SELECT v_max::INTERVAL DAY TO MINUTE FROM t_table_002g;
SELECT v_min1::INTERVAL DAY TO MINUTE FROM t_table_002g;
SELECT v_mid1::INTERVAL DAY TO MINUTE FROM t_table_002g;
SELECT v_max1::INTERVAL DAY TO MINUTE FROM t_table_002g;
SELECT v_min::INTERVAL DAY TO SECOND FROM t_table_002g;
SELECT v_mid::INTERVAL DAY TO SECOND FROM t_table_002g;
SELECT v_max::INTERVAL DAY TO SECOND FROM t_table_002g;
SELECT v_min1::INTERVAL DAY TO SECOND FROM t_table_002g;
SELECT v_mid1::INTERVAL DAY TO SECOND FROM t_table_002g;
SELECT v_max1::INTERVAL DAY TO SECOND FROM t_table_002g;
SELECT v_min::INTERVAL HOUR TO MINUTE FROM t_table_002g;
SELECT v_mid::INTERVAL HOUR TO MINUTE FROM t_table_002g;
SELECT v_max::INTERVAL HOUR TO MINUTE FROM t_table_002g;
SELECT v_min1::INTERVAL HOUR TO MINUTE FROM t_table_002g;
SELECT v_mid1::INTERVAL HOUR TO MINUTE FROM t_table_002g;
SELECT v_max1::INTERVAL HOUR TO MINUTE FROM t_table_002g;
SELECT v_min::INTERVAL HOUR TO SECOND FROM t_table_002g;
SELECT v_mid::INTERVAL HOUR TO SECOND FROM t_table_002g;
SELECT v_max::INTERVAL HOUR TO SECOND FROM t_table_002g;
SELECT v_min1::INTERVAL HOUR TO SECOND FROM t_table_002g;
SELECT v_mid1::INTERVAL HOUR TO SECOND FROM t_table_002g;
SELECT v_max1::INTERVAL HOUR TO SECOND FROM t_table_002g;
SELECT v_min::INTERVAL MINUTE TO SECOND FROM t_table_002g;
SELECT v_mid::INTERVAL MINUTE TO SECOND FROM t_table_002g;
SELECT v_max::INTERVAL MINUTE TO SECOND FROM t_table_002g;
SELECT v_min1::INTERVAL MINUTE TO SECOND FROM t_table_002g;
SELECT v_mid1::INTERVAL MINUTE TO SECOND FROM t_table_002g;
SELECT v_max1::INTERVAL MINUTE TO SECOND FROM t_table_002g;

//INTERVAL DAY TO HOUR 默认精度转换
SELECT v_min::INTERVAL YEAR FROM t_table_002h;
SELECT v_mid::INTERVAL YEAR FROM t_table_002h;
SELECT v_max::INTERVAL YEAR FROM t_table_002h;
SELECT v_min1::INTERVAL YEAR FROM t_table_002h;
SELECT v_mid1::INTERVAL YEAR FROM t_table_002h;
SELECT v_max1::INTERVAL YEAR FROM t_table_002h;
SELECT v_min::INTERVAL MONTH FROM t_table_002h;
SELECT v_mid::INTERVAL MONTH FROM t_table_002h;
SELECT v_max::INTERVAL MONTH FROM t_table_002h;
SELECT v_min1::INTERVAL MONTH FROM t_table_002h;
SELECT v_mid1::INTERVAL MONTH FROM t_table_002h;
SELECT v_max1::INTERVAL MONTH FROM t_table_002h;
SELECT v_min::INTERVAL DAY FROM t_table_002h;
SELECT v_mid::INTERVAL DAY FROM t_table_002h;
SELECT v_max::INTERVAL DAY FROM t_table_002h;
SELECT v_min1::INTERVAL DAY FROM t_table_002h;
SELECT v_mid1::INTERVAL DAY FROM t_table_002h;
SELECT v_max1::INTERVAL DAY FROM t_table_002h;
SELECT v_min::INTERVAL HOUR FROM t_table_002h;
SELECT v_mid::INTERVAL HOUR FROM t_table_002h;
SELECT v_max::INTERVAL HOUR FROM t_table_002h;
SELECT v_min1::INTERVAL HOUR FROM t_table_002h;
SELECT v_mid1::INTERVAL HOUR FROM t_table_002h;
SELECT v_max1::INTERVAL HOUR FROM t_table_002h;
SELECT v_min::INTERVAL MINUTE FROM t_table_002h;
SELECT v_mid::INTERVAL MINUTE FROM t_table_002h;
SELECT v_max::INTERVAL MINUTE FROM t_table_002h;
SELECT v_min1::INTERVAL MINUTE FROM t_table_002h;
SELECT v_mid1::INTERVAL MINUTE FROM t_table_002h;
SELECT v_max1::INTERVAL MINUTE FROM t_table_002h;
SELECT v_min::INTERVAL SECOND FROM t_table_002h;
SELECT v_mid::INTERVAL SECOND FROM t_table_002h;
SELECT v_max::INTERVAL SECOND FROM t_table_002h;
SELECT v_min1::INTERVAL SECOND FROM t_table_002h;
SELECT v_mid1::INTERVAL SECOND FROM t_table_002h;
SELECT v_max1::INTERVAL SECOND FROM t_table_002h;
SELECT v_min::INTERVAL YEAR TO MONTH FROM t_table_002h;
SELECT v_mid::INTERVAL YEAR TO MONTH FROM t_table_002h;
SELECT v_max::INTERVAL YEAR TO MONTH FROM t_table_002h;
SELECT v_min1::INTERVAL YEAR TO MONTH FROM t_table_002h;
SELECT v_mid1::INTERVAL YEAR TO MONTH FROM t_table_002h;
SELECT v_max1::INTERVAL YEAR TO MONTH FROM t_table_002h;
SELECT v_min::INTERVAL DAY TO MINUTE FROM t_table_002h;
SELECT v_mid::INTERVAL DAY TO MINUTE FROM t_table_002h;
SELECT v_max::INTERVAL DAY TO MINUTE FROM t_table_002h;
SELECT v_min1::INTERVAL DAY TO MINUTE FROM t_table_002h;
SELECT v_mid1::INTERVAL DAY TO MINUTE FROM t_table_002h;
SELECT v_max1::INTERVAL DAY TO MINUTE FROM t_table_002h;
SELECT v_min::INTERVAL DAY TO SECOND FROM t_table_002h;
SELECT v_mid::INTERVAL DAY TO SECOND FROM t_table_002h;
SELECT v_max::INTERVAL DAY TO SECOND FROM t_table_002h;
SELECT v_min1::INTERVAL DAY TO SECOND FROM t_table_002h;
SELECT v_mid1::INTERVAL DAY TO SECOND FROM t_table_002h;
SELECT v_max1::INTERVAL DAY TO SECOND FROM t_table_002h;
SELECT v_min::INTERVAL HOUR TO MINUTE FROM t_table_002h;
SELECT v_mid::INTERVAL HOUR TO MINUTE FROM t_table_002h;
SELECT v_max::INTERVAL HOUR TO MINUTE FROM t_table_002h;
SELECT v_min1::INTERVAL HOUR TO MINUTE FROM t_table_002h;
SELECT v_mid1::INTERVAL HOUR TO MINUTE FROM t_table_002h;
SELECT v_max1::INTERVAL HOUR TO MINUTE FROM t_table_002h;
SELECT v_min::INTERVAL HOUR TO SECOND FROM t_table_002h;
SELECT v_mid::INTERVAL HOUR TO SECOND FROM t_table_002h;
SELECT v_max::INTERVAL HOUR TO SECOND FROM t_table_002h;
SELECT v_min1::INTERVAL HOUR TO SECOND FROM t_table_002h;
SELECT v_mid1::INTERVAL HOUR TO SECOND FROM t_table_002h;
SELECT v_max1::INTERVAL HOUR TO SECOND FROM t_table_002h;
SELECT v_min::INTERVAL MINUTE TO SECOND FROM t_table_002h;
SELECT v_mid::INTERVAL MINUTE TO SECOND FROM t_table_002h;
SELECT v_max::INTERVAL MINUTE TO SECOND FROM t_table_002h;
SELECT v_min1::INTERVAL MINUTE TO SECOND FROM t_table_002h;
SELECT v_mid1::INTERVAL MINUTE TO SECOND FROM t_table_002h;
SELECT v_max1::INTERVAL MINUTE TO SECOND FROM t_table_002h;

//INTERVAL DAY TO MINUTE 默认精度转换
SELECT v_min::INTERVAL YEAR FROM t_table_002i;
SELECT v_mid::INTERVAL YEAR FROM t_table_002i;
SELECT v_max::INTERVAL YEAR FROM t_table_002i;
SELECT v_min1::INTERVAL YEAR FROM t_table_002i;
SELECT v_mid1::INTERVAL YEAR FROM t_table_002i;
SELECT v_max1::INTERVAL YEAR FROM t_table_002i;
SELECT v_min::INTERVAL MONTH FROM t_table_002i;
SELECT v_mid::INTERVAL MONTH FROM t_table_002i;
SELECT v_max::INTERVAL MONTH FROM t_table_002i;
SELECT v_min1::INTERVAL MONTH FROM t_table_002i;
SELECT v_mid1::INTERVAL MONTH FROM t_table_002i;
SELECT v_max1::INTERVAL MONTH FROM t_table_002i;
SELECT v_min::INTERVAL DAY FROM t_table_002i;
SELECT v_mid::INTERVAL DAY FROM t_table_002i;
SELECT v_max::INTERVAL DAY FROM t_table_002i;
SELECT v_min1::INTERVAL DAY FROM t_table_002i;
SELECT v_mid1::INTERVAL DAY FROM t_table_002i;
SELECT v_max1::INTERVAL DAY FROM t_table_002i;
SELECT v_min::INTERVAL HOUR FROM t_table_002i;
SELECT v_mid::INTERVAL HOUR FROM t_table_002i;
SELECT v_max::INTERVAL HOUR FROM t_table_002i;
SELECT v_min1::INTERVAL HOUR FROM t_table_002i;
SELECT v_mid1::INTERVAL HOUR FROM t_table_002i;
SELECT v_max1::INTERVAL HOUR FROM t_table_002i;
SELECT v_min::INTERVAL MINUTE FROM t_table_002i;
SELECT v_mid::INTERVAL MINUTE FROM t_table_002i;
SELECT v_max::INTERVAL MINUTE FROM t_table_002i;
SELECT v_min1::INTERVAL MINUTE FROM t_table_002i;
SELECT v_mid1::INTERVAL MINUTE FROM t_table_002i;
SELECT v_max1::INTERVAL MINUTE FROM t_table_002i;
SELECT v_min::INTERVAL SECOND FROM t_table_002i;
SELECT v_mid::INTERVAL SECOND FROM t_table_002i;
SELECT v_max::INTERVAL SECOND FROM t_table_002i;
SELECT v_min1::INTERVAL SECOND FROM t_table_002i;
SELECT v_mid1::INTERVAL SECOND FROM t_table_002i;
SELECT v_max1::INTERVAL SECOND FROM t_table_002i;
SELECT v_min::INTERVAL YEAR TO MONTH FROM t_table_002i;
SELECT v_mid::INTERVAL YEAR TO MONTH FROM t_table_002i;
SELECT v_max::INTERVAL YEAR TO MONTH FROM t_table_002i;
SELECT v_min1::INTERVAL YEAR TO MONTH FROM t_table_002i;
SELECT v_mid1::INTERVAL YEAR TO MONTH FROM t_table_002i;
SELECT v_max1::INTERVAL YEAR TO MONTH FROM t_table_002i;
SELECT v_min::INTERVAL DAY TO HOUR FROM t_table_002i;
SELECT v_mid::INTERVAL DAY TO HOUR FROM t_table_002i;
SELECT v_max::INTERVAL DAY TO HOUR FROM t_table_002i;
SELECT v_min1::INTERVAL DAY TO HOUR FROM t_table_002i;
SELECT v_mid1::INTERVAL DAY TO HOUR FROM t_table_002i;
SELECT v_max1::INTERVAL DAY TO HOUR FROM t_table_002i;
SELECT v_min::INTERVAL DAY TO SECOND FROM t_table_002i;
SELECT v_mid::INTERVAL DAY TO SECOND FROM t_table_002i;
SELECT v_max::INTERVAL DAY TO SECOND FROM t_table_002i;
SELECT v_min1::INTERVAL DAY TO SECOND FROM t_table_002i;
SELECT v_mid1::INTERVAL DAY TO SECOND FROM t_table_002i;
SELECT v_max1::INTERVAL DAY TO SECOND FROM t_table_002i;
SELECT v_min::INTERVAL HOUR TO MINUTE FROM t_table_002i;
SELECT v_mid::INTERVAL HOUR TO MINUTE FROM t_table_002i;
SELECT v_max::INTERVAL HOUR TO MINUTE FROM t_table_002i;
SELECT v_min1::INTERVAL HOUR TO MINUTE FROM t_table_002i;
SELECT v_mid1::INTERVAL HOUR TO MINUTE FROM t_table_002i;
SELECT v_max1::INTERVAL HOUR TO MINUTE FROM t_table_002i;
SELECT v_min::INTERVAL HOUR TO SECOND FROM t_table_002i;
SELECT v_mid::INTERVAL HOUR TO SECOND FROM t_table_002i;
SELECT v_max::INTERVAL HOUR TO SECOND FROM t_table_002i;
SELECT v_min1::INTERVAL HOUR TO SECOND FROM t_table_002i;
SELECT v_mid1::INTERVAL HOUR TO SECOND FROM t_table_002i;
SELECT v_max1::INTERVAL HOUR TO SECOND FROM t_table_002i;
SELECT v_min::INTERVAL MINUTE TO SECOND FROM t_table_002i;
SELECT v_mid::INTERVAL MINUTE TO SECOND FROM t_table_002i;
SELECT v_max::INTERVAL MINUTE TO SECOND FROM t_table_002i;
SELECT v_min1::INTERVAL MINUTE TO SECOND FROM t_table_002i;
SELECT v_mid1::INTERVAL MINUTE TO SECOND FROM t_table_002i;
SELECT v_max1::INTERVAL MINUTE TO SECOND FROM t_table_002i;

//INTERVAL DAY TO SECOND 默认精度转换
SELECT v_min::INTERVAL YEAR FROM t_table_002j;
SELECT v_mid::INTERVAL YEAR FROM t_table_002j;
SELECT v_max::INTERVAL YEAR FROM t_table_002j;
SELECT v_min1::INTERVAL YEAR FROM t_table_002j;
SELECT v_mid1::INTERVAL YEAR FROM t_table_002j;
SELECT v_max1::INTERVAL YEAR FROM t_table_002j;
SELECT v_min::INTERVAL MONTH FROM t_table_002j;
SELECT v_mid::INTERVAL MONTH FROM t_table_002j;
SELECT v_max::INTERVAL MONTH FROM t_table_002j;
SELECT v_min1::INTERVAL MONTH FROM t_table_002j;
SELECT v_mid1::INTERVAL MONTH FROM t_table_002j;
SELECT v_max1::INTERVAL MONTH FROM t_table_002j;
SELECT v_min::INTERVAL DAY FROM t_table_002j;
SELECT v_mid::INTERVAL DAY FROM t_table_002j;
SELECT v_max::INTERVAL DAY FROM t_table_002j;
SELECT v_min1::INTERVAL DAY FROM t_table_002j;
SELECT v_mid1::INTERVAL DAY FROM t_table_002j;
SELECT v_max1::INTERVAL DAY FROM t_table_002j;
SELECT v_min::INTERVAL HOUR FROM t_table_002j;
SELECT v_mid::INTERVAL HOUR FROM t_table_002j;
SELECT v_max::INTERVAL HOUR FROM t_table_002j;
SELECT v_min1::INTERVAL HOUR FROM t_table_002j;
SELECT v_mid1::INTERVAL HOUR FROM t_table_002j;
SELECT v_max1::INTERVAL HOUR FROM t_table_002j;
SELECT v_min::INTERVAL MINUTE FROM t_table_002j;
SELECT v_mid::INTERVAL MINUTE FROM t_table_002j;
SELECT v_max::INTERVAL MINUTE FROM t_table_002j;
SELECT v_min1::INTERVAL MINUTE FROM t_table_002j;
SELECT v_mid1::INTERVAL MINUTE FROM t_table_002j;
SELECT v_max1::INTERVAL MINUTE FROM t_table_002j;
SELECT v_min::INTERVAL SECOND FROM t_table_002j;
SELECT v_mid::INTERVAL SECOND FROM t_table_002j;
SELECT v_max::INTERVAL SECOND FROM t_table_002j;
SELECT v_min1::INTERVAL SECOND FROM t_table_002j;
SELECT v_mid1::INTERVAL SECOND FROM t_table_002j;
SELECT v_max1::INTERVAL SECOND FROM t_table_002j;
SELECT v_min::INTERVAL YEAR TO MONTH FROM t_table_002j;
SELECT v_mid::INTERVAL YEAR TO MONTH FROM t_table_002j;
SELECT v_max::INTERVAL YEAR TO MONTH FROM t_table_002j;
SELECT v_min1::INTERVAL YEAR TO MONTH FROM t_table_002j;
SELECT v_mid1::INTERVAL YEAR TO MONTH FROM t_table_002j;
SELECT v_max1::INTERVAL YEAR TO MONTH FROM t_table_002j;
SELECT v_min::INTERVAL DAY TO HOUR FROM t_table_002j;
SELECT v_mid::INTERVAL DAY TO HOUR FROM t_table_002j;
SELECT v_max::INTERVAL DAY TO HOUR FROM t_table_002j;
SELECT v_min1::INTERVAL DAY TO HOUR FROM t_table_002j;
SELECT v_mid1::INTERVAL DAY TO HOUR FROM t_table_002j;
SELECT v_max1::INTERVAL DAY TO HOUR FROM t_table_002j;
SELECT v_min::INTERVAL DAY TO MINUTE FROM t_table_002j;
SELECT v_mid::INTERVAL DAY TO MINUTE FROM t_table_002j;
SELECT v_max::INTERVAL DAY TO MINUTE FROM t_table_002j;
SELECT v_min1::INTERVAL DAY TO MINUTE FROM t_table_002j;
SELECT v_mid1::INTERVAL DAY TO MINUTE FROM t_table_002j;
SELECT v_min::INTERVAL HOUR TO MINUTE FROM t_table_002j;
SELECT v_mid::INTERVAL HOUR TO MINUTE FROM t_table_002j;
SELECT v_max::INTERVAL HOUR TO MINUTE FROM t_table_002j;
SELECT v_min1::INTERVAL HOUR TO MINUTE FROM t_table_002j;
SELECT v_mid1::INTERVAL HOUR TO MINUTE FROM t_table_002j;
SELECT v_max1::INTERVAL HOUR TO MINUTE FROM t_table_002j;
SELECT v_min::INTERVAL HOUR TO SECOND FROM t_table_002j;
SELECT v_mid::INTERVAL HOUR TO SECOND FROM t_table_002j;
SELECT v_max::INTERVAL HOUR TO SECOND FROM t_table_002j;
SELECT v_min1::INTERVAL HOUR TO SECOND FROM t_table_002j;
SELECT v_mid1::INTERVAL HOUR TO SECOND FROM t_table_002j;
SELECT v_max1::INTERVAL HOUR TO SECOND FROM t_table_002j;
SELECT v_min::INTERVAL MINUTE TO SECOND FROM t_table_002j;
SELECT v_mid::INTERVAL MINUTE TO SECOND FROM t_table_002j;
SELECT v_max::INTERVAL MINUTE TO SECOND FROM t_table_002j;
SELECT v_min1::INTERVAL MINUTE TO SECOND FROM t_table_002j;
SELECT v_mid1::INTERVAL MINUTE TO SECOND FROM t_table_002j;
SELECT v_max1::INTERVAL MINUTE TO SECOND FROM t_table_002j;

//INTERVAL HOUR TO MINUTE 默认精度转换
SELECT v_min::INTERVAL YEAR FROM t_table_002k;
SELECT v_mid::INTERVAL YEAR FROM t_table_002k;
SELECT v_max::INTERVAL YEAR FROM t_table_002k;
SELECT v_min1::INTERVAL YEAR FROM t_table_002k;
SELECT v_mid1::INTERVAL YEAR FROM t_table_002k;
SELECT v_max1::INTERVAL YEAR FROM t_table_002k;
SELECT v_min::INTERVAL MONTH FROM t_table_002k;
SELECT v_mid::INTERVAL MONTH FROM t_table_002k;
SELECT v_max::INTERVAL MONTH FROM t_table_002k;
SELECT v_min1::INTERVAL MONTH FROM t_table_002k;
SELECT v_mid1::INTERVAL MONTH FROM t_table_002k;
SELECT v_max1::INTERVAL MONTH FROM t_table_002k;
SELECT v_min::INTERVAL DAY FROM t_table_002k;
SELECT v_mid::INTERVAL DAY FROM t_table_002k;
SELECT v_max::INTERVAL DAY FROM t_table_002k;
SELECT v_min1::INTERVAL DAY FROM t_table_002k;
SELECT v_mid1::INTERVAL DAY FROM t_table_002k;
SELECT v_max1::INTERVAL DAY FROM t_table_002k;
SELECT v_min::INTERVAL HOUR FROM t_table_002k;
SELECT v_mid::INTERVAL HOUR FROM t_table_002k;
SELECT v_max::INTERVAL HOUR FROM t_table_002k;
SELECT v_min1::INTERVAL HOUR FROM t_table_002k;
SELECT v_mid1::INTERVAL HOUR FROM t_table_002k;
SELECT v_max1::INTERVAL HOUR FROM t_table_002k;
SELECT v_min::INTERVAL MINUTE FROM t_table_002k;
SELECT v_mid::INTERVAL MINUTE FROM t_table_002k;
SELECT v_max::INTERVAL MINUTE FROM t_table_002k;
SELECT v_min1::INTERVAL MINUTE FROM t_table_002k;
SELECT v_mid1::INTERVAL MINUTE FROM t_table_002k;
SELECT v_max1::INTERVAL MINUTE FROM t_table_002k;
SELECT v_min::INTERVAL SECOND FROM t_table_002k;
SELECT v_mid::INTERVAL SECOND FROM t_table_002k;
SELECT v_max::INTERVAL SECOND FROM t_table_002k;
SELECT v_min1::INTERVAL SECOND FROM t_table_002k;
SELECT v_mid1::INTERVAL SECOND FROM t_table_002k;
SELECT v_max1::INTERVAL SECOND FROM t_table_002k;
SELECT v_min::INTERVAL YEAR TO MONTH FROM t_table_002k;
SELECT v_mid::INTERVAL YEAR TO MONTH FROM t_table_002k;
SELECT v_max::INTERVAL YEAR TO MONTH FROM t_table_002k;
SELECT v_min1::INTERVAL YEAR TO MONTH FROM t_table_002k;
SELECT v_mid1::INTERVAL YEAR TO MONTH FROM t_table_002k;
SELECT v_max1::INTERVAL YEAR TO MONTH FROM t_table_002k;
SELECT v_min::INTERVAL DAY TO HOUR FROM t_table_002k;
SELECT v_mid::INTERVAL DAY TO HOUR FROM t_table_002k;
SELECT v_max::INTERVAL DAY TO HOUR FROM t_table_002k;
SELECT v_min1::INTERVAL DAY TO HOUR FROM t_table_002k;
SELECT v_mid1::INTERVAL DAY TO HOUR FROM t_table_002k;
SELECT v_max1::INTERVAL DAY TO HOUR FROM t_table_002k;
SELECT v_min::INTERVAL DAY TO MINUTE FROM t_table_002k;
SELECT v_mid::INTERVAL DAY TO MINUTE FROM t_table_002k;
SELECT v_max::INTERVAL DAY TO MINUTE FROM t_table_002k;
SELECT v_min1::INTERVAL DAY TO MINUTE FROM t_table_002k;
SELECT v_mid1::INTERVAL DAY TO MINUTE FROM t_table_002k;
SELECT v_max1::INTERVAL DAY TO MINUTE FROM t_table_002k;
SELECT v_min::INTERVAL DAY TO SECOND FROM t_table_002k;
SELECT v_mid::INTERVAL DAY TO SECOND FROM t_table_002k;
SELECT v_max::INTERVAL DAY TO SECOND FROM t_table_002k;
SELECT v_min1::INTERVAL DAY TO SECOND FROM t_table_002k;
SELECT v_mid1::INTERVAL DAY TO SECOND FROM t_table_002k;
SELECT v_max1::INTERVAL DAY TO SECOND FROM t_table_002k;
SELECT v_min::INTERVAL HOUR TO SECOND FROM t_table_002k;
SELECT v_mid::INTERVAL HOUR TO SECOND FROM t_table_002k;
SELECT v_max::INTERVAL HOUR TO SECOND FROM t_table_002k;
SELECT v_min1::INTERVAL HOUR TO SECOND FROM t_table_002k;
SELECT v_mid1::INTERVAL HOUR TO SECOND FROM t_table_002k;
SELECT v_max1::INTERVAL HOUR TO SECOND FROM t_table_002k;
SELECT v_min::INTERVAL MINUTE TO SECOND FROM t_table_002k;
SELECT v_mid::INTERVAL MINUTE TO SECOND FROM t_table_002k;
SELECT v_max::INTERVAL MINUTE TO SECOND FROM t_table_002k;
SELECT v_min1::INTERVAL MINUTE TO SECOND FROM t_table_002k;
SELECT v_mid1::INTERVAL MINUTE TO SECOND FROM t_table_002k;
SELECT v_max1::INTERVAL MINUTE TO SECOND FROM t_table_002k;

//INTERVAL HOUR TO SECOND 默认精度转换
SELECT v_min::INTERVAL YEAR FROM t_table_002l;
SELECT v_mid::INTERVAL YEAR FROM t_table_002l;
SELECT v_max::INTERVAL YEAR FROM t_table_002l;
SELECT v_min1::INTERVAL YEAR FROM t_table_002l;
SELECT v_mid1::INTERVAL YEAR FROM t_table_002l;
SELECT v_max1::INTERVAL YEAR FROM t_table_002l;
SELECT v_min::INTERVAL MONTH FROM t_table_002l;
SELECT v_mid::INTERVAL MONTH FROM t_table_002l;
SELECT v_max::INTERVAL MONTH FROM t_table_002l;
SELECT v_min1::INTERVAL MONTH FROM t_table_002l;
SELECT v_mid1::INTERVAL MONTH FROM t_table_002l;
SELECT v_max1::INTERVAL MONTH FROM t_table_002l;
SELECT v_min::INTERVAL DAY FROM t_table_002l;
SELECT v_mid::INTERVAL DAY FROM t_table_002l;
SELECT v_max::INTERVAL DAY FROM t_table_002l;
SELECT v_min1::INTERVAL DAY FROM t_table_002l;
SELECT v_mid1::INTERVAL DAY FROM t_table_002l;
SELECT v_max1::INTERVAL DAY FROM t_table_002l;
SELECT v_min::INTERVAL HOUR FROM t_table_002l;
SELECT v_mid::INTERVAL HOUR FROM t_table_002l;
SELECT v_max::INTERVAL HOUR FROM t_table_002l;
SELECT v_min1::INTERVAL HOUR FROM t_table_002l;
SELECT v_mid1::INTERVAL HOUR FROM t_table_002l;
SELECT v_max1::INTERVAL HOUR FROM t_table_002l;
SELECT v_min::INTERVAL MINUTE FROM t_table_002l;
SELECT v_mid::INTERVAL MINUTE FROM t_table_002l;
SELECT v_max::INTERVAL MINUTE FROM t_table_002l;
SELECT v_min1::INTERVAL MINUTE FROM t_table_002l;
SELECT v_mid1::INTERVAL MINUTE FROM t_table_002l;
SELECT v_max1::INTERVAL MINUTE FROM t_table_002l;
SELECT v_min::INTERVAL SECOND FROM t_table_002l;
SELECT v_mid::INTERVAL SECOND FROM t_table_002l;
SELECT v_max::INTERVAL SECOND FROM t_table_002l;
SELECT v_min1::INTERVAL SECOND FROM t_table_002l;
SELECT v_mid1::INTERVAL SECOND FROM t_table_002l;
SELECT v_max1::INTERVAL SECOND FROM t_table_002l;
SELECT v_min::INTERVAL YEAR TO MONTH FROM t_table_002l;
SELECT v_mid::INTERVAL YEAR TO MONTH FROM t_table_002l;
SELECT v_max::INTERVAL YEAR TO MONTH FROM t_table_002l;
SELECT v_min1::INTERVAL YEAR TO MONTH FROM t_table_002l;
SELECT v_mid1::INTERVAL YEAR TO MONTH FROM t_table_002l;
SELECT v_max1::INTERVAL YEAR TO MONTH FROM t_table_002l;
SELECT v_min::INTERVAL DAY TO HOUR FROM t_table_002l;
SELECT v_mid::INTERVAL DAY TO HOUR FROM t_table_002l;
SELECT v_max::INTERVAL DAY TO HOUR FROM t_table_002l;
SELECT v_min1::INTERVAL DAY TO HOUR FROM t_table_002l;
SELECT v_mid1::INTERVAL DAY TO HOUR FROM t_table_002l;
SELECT v_max1::INTERVAL DAY TO HOUR FROM t_table_002l;
SELECT v_min::INTERVAL DAY TO MINUTE FROM t_table_002l;
SELECT v_mid::INTERVAL DAY TO MINUTE FROM t_table_002l;
SELECT v_max::INTERVAL DAY TO MINUTE FROM t_table_002l;
SELECT v_min1::INTERVAL DAY TO MINUTE FROM t_table_002l;
SELECT v_mid1::INTERVAL DAY TO MINUTE FROM t_table_002l;
SELECT v_max1::INTERVAL DAY TO MINUTE FROM t_table_002l;
SELECT v_min::INTERVAL DAY TO SECOND FROM t_table_002l;
SELECT v_mid::INTERVAL DAY TO SECOND FROM t_table_002l;
SELECT v_max::INTERVAL DAY TO SECOND FROM t_table_002l;
SELECT v_min1::INTERVAL DAY TO SECOND FROM t_table_002l;
SELECT v_mid1::INTERVAL DAY TO SECOND FROM t_table_002l;
SELECT v_max1::INTERVAL DAY TO SECOND FROM t_table_002l;
SELECT v_min::INTERVAL HOUR TO MINUTE FROM t_table_002l;
SELECT v_mid::INTERVAL HOUR TO MINUTE FROM t_table_002l;
SELECT v_max::INTERVAL HOUR TO MINUTE FROM t_table_002l;
SELECT v_min1::INTERVAL HOUR TO MINUTE FROM t_table_002l;
SELECT v_mid1::INTERVAL HOUR TO MINUTE FROM t_table_002l;
SELECT v_max1::INTERVAL HOUR TO MINUTE FROM t_table_002l;
SELECT v_min::INTERVAL MINUTE TO SECOND FROM t_table_002l;
SELECT v_mid::INTERVAL MINUTE TO SECOND FROM t_table_002l;
SELECT v_max::INTERVAL MINUTE TO SECOND FROM t_table_002l;
SELECT v_min1::INTERVAL MINUTE TO SECOND FROM t_table_002l;
SELECT v_mid1::INTERVAL MINUTE TO SECOND FROM t_table_002l;
SELECT v_max1::INTERVAL MINUTE TO SECOND FROM t_table_002l;

//INTERVAL MINUTE TO SECOND 默认精度转换
SELECT v_min::INTERVAL YEAR FROM t_table_002m;
SELECT v_mid::INTERVAL YEAR FROM t_table_002m;
SELECT v_max::INTERVAL YEAR FROM t_table_002m;
SELECT v_min1::INTERVAL YEAR FROM t_table_002m;
SELECT v_mid1::INTERVAL YEAR FROM t_table_002m;
SELECT v_max1::INTERVAL YEAR FROM t_table_002m;
SELECT v_min::INTERVAL MONTH FROM t_table_002m;
SELECT v_mid::INTERVAL MONTH FROM t_table_002m;
SELECT v_max::INTERVAL MONTH FROM t_table_002m;
SELECT v_min1::INTERVAL MONTH FROM t_table_002m;
SELECT v_mid1::INTERVAL MONTH FROM t_table_002m;
SELECT v_max1::INTERVAL MONTH FROM t_table_002m;
SELECT v_min::INTERVAL DAY FROM t_table_002m;
SELECT v_mid::INTERVAL DAY FROM t_table_002m;
SELECT v_max::INTERVAL DAY FROM t_table_002m;
SELECT v_min1::INTERVAL DAY FROM t_table_002m;
SELECT v_mid1::INTERVAL DAY FROM t_table_002m;
SELECT v_max1::INTERVAL DAY FROM t_table_002m;
SELECT v_min::INTERVAL HOUR FROM t_table_002m;
SELECT v_mid::INTERVAL HOUR FROM t_table_002m;
SELECT v_max::INTERVAL HOUR FROM t_table_002m;
SELECT v_min1::INTERVAL HOUR FROM t_table_002m;
SELECT v_mid1::INTERVAL HOUR FROM t_table_002m;
SELECT v_max1::INTERVAL HOUR FROM t_table_002m;
SELECT v_min::INTERVAL MINUTE FROM t_table_002m;
SELECT v_mid::INTERVAL MINUTE FROM t_table_002m;
SELECT v_max::INTERVAL MINUTE FROM t_table_002m;
SELECT v_min1::INTERVAL MINUTE FROM t_table_002m;
SELECT v_mid1::INTERVAL MINUTE FROM t_table_002m;
SELECT v_max1::INTERVAL MINUTE FROM t_table_002m;
SELECT v_min::INTERVAL SECOND FROM t_table_002m;
SELECT v_mid::INTERVAL SECOND FROM t_table_002m;
SELECT v_max::INTERVAL SECOND FROM t_table_002m;
SELECT v_min1::INTERVAL SECOND FROM t_table_002m;
SELECT v_mid1::INTERVAL SECOND FROM t_table_002m;
SELECT v_max1::INTERVAL SECOND FROM t_table_002m;
SELECT v_min::INTERVAL YEAR TO MONTH FROM t_table_002m;
SELECT v_mid::INTERVAL YEAR TO MONTH FROM t_table_002m;
SELECT v_max::INTERVAL YEAR TO MONTH FROM t_table_002m;
SELECT v_min1::INTERVAL YEAR TO MONTH FROM t_table_002m;
SELECT v_mid1::INTERVAL YEAR TO MONTH FROM t_table_002m;
SELECT v_max1::INTERVAL YEAR TO MONTH FROM t_table_002m;
SELECT v_min::INTERVAL DAY TO HOUR FROM t_table_002m;
SELECT v_mid::INTERVAL DAY TO HOUR FROM t_table_002m;
SELECT v_max::INTERVAL DAY TO HOUR FROM t_table_002m;
SELECT v_min1::INTERVAL DAY TO HOUR FROM t_table_002m;
SELECT v_mid1::INTERVAL DAY TO HOUR FROM t_table_002m;
SELECT v_max1::INTERVAL DAY TO HOUR FROM t_table_002m;
SELECT v_min::INTERVAL DAY TO MINUTE FROM t_table_002m;
SELECT v_mid::INTERVAL DAY TO MINUTE FROM t_table_002m;
SELECT v_max::INTERVAL DAY TO MINUTE FROM t_table_002m;
SELECT v_min1::INTERVAL DAY TO MINUTE FROM t_table_002m;
SELECT v_mid1::INTERVAL DAY TO MINUTE FROM t_table_002m;
SELECT v_max1::INTERVAL DAY TO MINUTE FROM t_table_002m;
SELECT v_min::INTERVAL DAY TO SECOND FROM t_table_002m;
SELECT v_mid::INTERVAL DAY TO SECOND FROM t_table_002m;
SELECT v_max::INTERVAL DAY TO SECOND FROM t_table_002m;
SELECT v_min1::INTERVAL DAY TO SECOND FROM t_table_002m;
SELECT v_mid1::INTERVAL DAY TO SECOND FROM t_table_002m;
SELECT v_max1::INTERVAL DAY TO SECOND FROM t_table_002m;
SELECT v_min::INTERVAL HOUR TO MINUTE FROM t_table_002m;
SELECT v_mid::INTERVAL HOUR TO MINUTE FROM t_table_002m;
SELECT v_max::INTERVAL HOUR TO MINUTE FROM t_table_002m;
SELECT v_min1::INTERVAL HOUR TO MINUTE FROM t_table_002m;
SELECT v_mid1::INTERVAL HOUR TO MINUTE FROM t_table_002m;
SELECT v_max1::INTERVAL HOUR TO MINUTE FROM t_table_002m;
SELECT v_min::INTERVAL HOUR TO SECOND FROM t_table_002m;
SELECT v_mid::INTERVAL HOUR TO SECOND FROM t_table_002m;
SELECT v_max::INTERVAL HOUR TO SECOND FROM t_table_002m;
SELECT v_min1::INTERVAL HOUR TO SECOND FROM t_table_002m;
SELECT v_mid1::INTERVAL HOUR TO SECOND FROM t_table_002m;
SELECT v_max1::INTERVAL HOUR TO SECOND FROM t_table_002m;
SELECT v_min::INTERVAL MINUTE TO SECOND FROM t_table_002m;
SELECT v_mid::INTERVAL MINUTE TO SECOND FROM t_table_002m;
SELECT v_max::INTERVAL MINUTE TO SECOND FROM t_table_002m;
SELECT v_min1::INTERVAL MINUTE TO SECOND FROM t_table_002m;
SELECT v_mid1::INTERVAL MINUTE TO SECOND FROM t_table_002m;
SELECT v_max1::INTERVAL MINUTE TO SECOND FROM t_table_002m;

//删除表
DROP TABLE t_table_002a;
DROP TABLE t_table_002b;
DROP TABLE t_table_002c;
DROP TABLE t_table_002d;
DROP TABLE t_table_002e;
DROP TABLE t_table_002f;
DROP TABLE t_table_002g;
DROP TABLE t_table_002h;
DROP TABLE t_table_002i;
DROP TABLE t_table_002j;
DROP TABLE t_table_002k;
DROP TABLE t_table_002l;
DROP TABLE t_table_002m;
