!4 XG-TYPE-INTERVAL-001 INTERVAL 类型相互运算 : 异常 - 运算后到达边界
{{{ INTERVAL 之间相互运算时,分为年月之间和时分秒之间两类,两类之间不支持运算,且在执行运算的时候都隐式转换为运算符左右支中较小类型单元}}}
//INTERVAL YEAR
{{{
    返回值类型:
    y + y -> y
    y + m -> m
}}}
SELECT '999999998'::INTERVAL YEAR + '1'::INTERVAL YEAR;
SELECT '999999998'::INTERVAL YEAR + '2'::INTERVAL YEAR;
SELECT '178956970'::INTERVAL YEAR + '7'::INTERVAL MONTH;
SELECT '178956970'::INTERVAL YEAR + '8'::INTERVAL MONTH;

//INTERVAL MONTH
{{{
    返回值类型:
    m + y -> m
    m + m -> m
}}}
SELECT '2147483647'::INTERVAL MONTH + '0'::INTERVAL YEAR;
SELECT '2147483647'::INTERVAL MONTH + '1'::INTERVAL YEAR;
SELECT '2147483647'::INTERVAL MONTH + '0'::INTERVAL MONTH;
SELECT '2147483647'::INTERVAL MONTH + '1'::INTERVAL MONTH;

//INTERVAL DAY
{{{
    返回值类型:
    d + d -> d
    d + h -> h
    d + m -> m
    d + s -> s
}}}
SELECT '2147483647'::INTERVAL DAY + '0'::INTERVAL DAY;
SELECT '2147483647'::INTERVAL DAY + '1'::INTERVAL DAY;
SELECT '41666666'::INTERVAL DAY + '15'::INTERVAL HOUR;
SELECT '41666666'::INTERVAL DAY + '16'::INTERVAL HOUR;
SELECT '694444'::INTERVAL DAY + '639'::INTERVAL MINUTE;
SELECT '694444'::INTERVAL DAY + '640'::INTERVAL MINUTE;
SELECT '106751991'::INTERVAL DAY + '14454'::INTERVAL SECOND;
SELECT '106751991'::INTERVAL DAY + '14455'::INTERVAL SECOND;

//INTERVAL HOUR
{{{
    返回值类型:
    h + d -> h
    h + h -> h
}}}
SELECT '999999999'::INTERVAL HOUR + '0'::INTERVAL DAY;
SELECT '999999999'::INTERVAL HOUR + '1'::INTERVAL DAY;
SELECT '999999999'::INTERVAL HOUR + '0'::INTERVAL HOUR;
SELECT '999999999'::INTERVAL HOUR + '1'::INTERVAL HOUR;

//INTERVAL MINUTE
{{{
    返回值类型:
    min + d -> min
    min + min -> min
}}}
SELECT '999999999'::INTERVAL MINUTE + '0'::INTERVAL DAY;
SELECT '999999999'::INTERVAL MINUTE + '1'::INTERVAL DAY;
SELECT '999999999'::INTERVAL MINUTE + '0'::INTERVAL MINUTE;
SELECT '999999999'::INTERVAL MINUTE + '1'::INTERVAL MINUTE;

//INTERVAL SECOND
{{{
    返回值类型:
    s + d -> s
    s + s -> s
}}}
SELECT '9223372036854.775807'::INTERVAL SECOND + '0'::INTERVAL DAY;
SELECT '9223372036854.775807'::INTERVAL SECOND + '1'::INTERVAL DAY;
SELECT '9223372036854.775807'::INTERVAL SECOND + '0'::INTERVAL SECOND;
SELECT '9223372036854.775807'::INTERVAL SECOND + '0.000001'::INTERVAL SECOND;

//INTERVAL YEAR TO MONTH
{{{
    返回值类型:
    y2m + y -> y2m
    y2m + m -> y2m
    y2m + y2m -> y2m
}}}
SELECT '2147483647'::INTERVAL YEAR TO MONTH + '0'::INTERVAL YEAR;
SELECT '2147483647'::INTERVAL YEAR TO MONTH + '1'::INTERVAL YEAR;
SELECT '2147483647'::INTERVAL YEAR TO MONTH + '0'::INTERVAL MONTH;
SELECT '2147483647'::INTERVAL YEAR TO MONTH + '1'::INTERVAL MONTH;
SELECT '2147483647'::INTERVAL YEAR TO MONTH + '0'::INTERVAL YEAR TO MONTH;
SELECT '2147483647'::INTERVAL YEAR TO MONTH + '1'::INTERVAL YEAR TO MONTH;

//INTERVAL DAY TO HOUR
{{{
    返回值类型:
    d2h + d -> d2h
    d2h + h -> d2h
    d2h + d2h -> d2h
}}}
SELECT '2147483647'::INTERVAL DAY TO HOUR + '0'::INTERVAL DAY;
SELECT '2147483647'::INTERVAL DAY TO HOUR + '1'::INTERVAL DAY;
SELECT '2147483647'::INTERVAL DAY TO HOUR + '0'::INTERVAL HOUR;
SELECT '2147483647'::INTERVAL DAY TO HOUR + '1'::INTERVAL HOUR;
SELECT '2147483647'::INTERVAL DAY TO HOUR + '0'::INTERVAL DAY TO HOUR;
SELECT '2147483647'::INTERVAL DAY TO HOUR + '1'::INTERVAL DAY TO HOUR;

//INTERVAL DAY TO MINUTE
{{{
    返回值类型:
    d2m + d -> d2m
    d2m + m -> d2m
    d2m + d2m -> d2m
}}}
SELECT '2147483647'::INTERVAL DAY TO MINUTE + '0'::INTERVAL DAY;
SELECT '2147483647'::INTERVAL DAY TO MINUTE + '1'::INTERVAL DAY;
SELECT '2147483647'::INTERVAL DAY TO MINUTE + '0'::INTERVAL MINUTE;
SELECT '2147483647'::INTERVAL DAY TO MINUTE + '1'::INTERVAL MINUTE;
SELECT '2147483647'::INTERVAL DAY TO MINUTE + '0'::INTERVAL DAY TO MINUTE;
SELECT '2147483647'::INTERVAL DAY TO MINUTE + '1'::INTERVAL DAY TO MINUTE;

//INTERVAL DAY TO SECOND
{{{
    返回值类型:
    d2s + d -> d2s
    d2s + s -> d2s
    d2s + d2s -> d2s
}}}
SELECT '9223372036854.775807'::INTERVAL DAY TO SECOND + '0'::INTERVAL DAY;
SELECT '9223372036854.775807'::INTERVAL DAY TO SECOND + '1'::INTERVAL DAY;
SELECT '9223372036854.775807'::INTERVAL DAY TO SECOND + '0'::INTERVAL SECOND;
SELECT '9223372036854.775807'::INTERVAL DAY TO SECOND + '1'::INTERVAL SECOND;
SELECT '9223372036854.775807'::INTERVAL DAY TO SECOND + '0'::INTERVAL DAY TO SECOND;
SELECT '9223372036854.775807'::INTERVAL DAY TO SECOND + '1'::INTERVAL DAY TO SECOND;

//INTERVAL HOUR TO MINUTE
{{{
    返回值类型:
    h2m + m -> h2m
    h2m + h2m -> h2m
}}}
SELECT '999999999'::INTERVAL HOUR TO MINUTE + '0'::INTERVAL MINUTE;
SELECT '999999999'::INTERVAL HOUR TO MINUTE + '1'::INTERVAL MINUTE;
SELECT '999999999'::INTERVAL HOUR TO MINUTE + '0'::INTERVAL HOUR TO MINUTE;
SELECT '999999999'::INTERVAL HOUR TO MINUTE + '1'::INTERVAL HOUR TO MINUTE;

//INTERVAL HOUR TO SECOND
{{{
    返回值类型:
    h2s + d -> h2s
    h2s + h2s -> h2s
}}}
SELECT '9223372036854.775807'::INTERVAL HOUR TO SECOND + '0'::INTERVAL DAY;
SELECT '9223372036854.775807'::INTERVAL HOUR TO SECOND + '1'::INTERVAL DAY;
SELECT '9223372036854.775807'::INTERVAL HOUR TO SECOND + '0'::INTERVAL HOUR TO SECOND;
SELECT '9223372036854.775807'::INTERVAL HOUR TO SECOND + '1'::INTERVAL HOUR TO SECOND;

//INTERVAL MINUTE TO SECOND

{{{
    返回值类型:
    m2s + d -> m2s
    m2s + m2s -> m2s
}}}
SELECT '9223372036854.775807'::INTERVAL HOUR TO SECOND + '0'::INTERVAL DAY;
SELECT '9223372036854.775807'::INTERVAL HOUR TO SECOND + '1'::INTERVAL DAY;
SELECT '9223372036854.775807'::INTERVAL HOUR TO SECOND + '0'::INTERVAL HOUR TO SECOND;
SELECT '9223372036854.775807'::INTERVAL HOUR TO SECOND + '1'::INTERVAL HOUR TO SECOND;

!4 XG-TYPE-INTERVAL-002 INTERVAL 类型相互运算 : 异常 - 乘除法运算
{{{ INTERVAL 之间相互乘除时,分为年月之间和时分秒之间两类,两类之间不支持运算,无相乘且执行运算的时候都隐式转换为运算符左右支中较小类型单元}}}

// "*" : INTERVAL YEAR;
SELECT '2'::INTERVAL YEAR * '1'::INTERVAL YEAR;
SELECT '2'::INTERVAL YEAR * '1'::INTERVAL MONTH;
SELECT '2'::INTERVAL YEAR * '1'::INTERVAL YEAR TO MONTH;
SELECT '2'::INTERVAL YEAR * '1'::INTERVAL DAY;
SELECT '2'::INTERVAL YEAR * '1'::INTERVAL HOUR;
SELECT '2'::INTERVAL YEAR * '1'::INTERVAL MINUTE;
SELECT '2'::INTERVAL YEAR * '1'::INTERVAL SECOND;
SELECT '2'::INTERVAL YEAR * '1'::INTERVAL DAY TO HOUR;
SELECT '2'::INTERVAL YEAR * '1'::INTERVAL DAY TO MINUTE;
SELECT '2'::INTERVAL YEAR * '1'::INTERVAL DAY TO SECOND;
SELECT '2'::INTERVAL YEAR * '1'::INTERVAL HOUR TO MINUTE;
SELECT '2'::INTERVAL YEAR * '1'::INTERVAL HOUR TO SECOND;
SELECT '2'::INTERVAL YEAR * '1'::INTERVAL MINUTE TO SECOND;

// "*" : INTERVAL MONTH;
SELECT '2'::INTERVAL MONTH * '1'::INTERVAL YEAR;
SELECT '2'::INTERVAL MONTH * '1'::INTERVAL MONTH;
SELECT '2'::INTERVAL MONTH * '1'::INTERVAL YEAR TO MONTH;
SELECT '2'::INTERVAL MONTH * '1'::INTERVAL DAY;
SELECT '2'::INTERVAL MONTH * '1'::INTERVAL HOUR;
SELECT '2'::INTERVAL MONTH * '1'::INTERVAL MINUTE;
SELECT '2'::INTERVAL MONTH * '1'::INTERVAL SECOND;
SELECT '2'::INTERVAL MONTH * '1'::INTERVAL DAY TO HOUR;
SELECT '2'::INTERVAL MONTH * '1'::INTERVAL DAY TO MINUTE;
SELECT '2'::INTERVAL MONTH * '1'::INTERVAL DAY TO SECOND;
SELECT '2'::INTERVAL MONTH * '1'::INTERVAL HOUR TO MINUTE;
SELECT '2'::INTERVAL MONTH * '1'::INTERVAL HOUR TO SECOND;
SELECT '2'::INTERVAL MONTH * '1'::INTERVAL MINUTE TO SECOND;

// "*" : INTERVAL DAY;
SELECT '2'::INTERVAL DAY * '1'::INTERVAL YEAR;
SELECT '2'::INTERVAL DAY * '1'::INTERVAL MONTH;
SELECT '2'::INTERVAL DAY * '1'::INTERVAL YEAR TO MONTH;
SELECT '2'::INTERVAL DAY * '1'::INTERVAL DAY;
SELECT '2'::INTERVAL DAY * '1'::INTERVAL HOUR;
SELECT '2'::INTERVAL DAY * '1'::INTERVAL MINUTE;
SELECT '2'::INTERVAL DAY * '1'::INTERVAL SECOND;
SELECT '2'::INTERVAL DAY * '1'::INTERVAL DAY TO HOUR;
SELECT '2'::INTERVAL DAY * '1'::INTERVAL DAY TO MINUTE;
SELECT '2'::INTERVAL DAY * '1'::INTERVAL DAY TO SECOND;
SELECT '2'::INTERVAL DAY * '1'::INTERVAL HOUR TO MINUTE;
SELECT '2'::INTERVAL DAY * '1'::INTERVAL HOUR TO SECOND;
SELECT '2'::INTERVAL DAY * '1'::INTERVAL MINUTE TO SECOND;

// "*" : INTERVAL HOUR;
SELECT '2'::INTERVAL HOUR * '1'::INTERVAL YEAR;
SELECT '2'::INTERVAL HOUR * '1'::INTERVAL MONTH;
SELECT '2'::INTERVAL HOUR * '1'::INTERVAL YEAR TO MONTH;
SELECT '2'::INTERVAL HOUR * '1'::INTERVAL DAY;
SELECT '2'::INTERVAL HOUR * '1'::INTERVAL HOUR;
SELECT '2'::INTERVAL HOUR * '1'::INTERVAL MINUTE;
SELECT '2'::INTERVAL HOUR * '1'::INTERVAL SECOND;
SELECT '2'::INTERVAL HOUR * '1'::INTERVAL DAY TO HOUR;
SELECT '2'::INTERVAL HOUR * '1'::INTERVAL DAY TO MINUTE;
SELECT '2'::INTERVAL HOUR * '1'::INTERVAL DAY TO SECOND;
SELECT '2'::INTERVAL HOUR * '1'::INTERVAL HOUR TO MINUTE;
SELECT '2'::INTERVAL HOUR * '1'::INTERVAL HOUR TO SECOND;
SELECT '2'::INTERVAL HOUR * '1'::INTERVAL MINUTE TO SECOND;

// "*" : INTERVAL MINUTE;
SELECT '2'::INTERVAL MINUTE * '1'::INTERVAL YEAR;
SELECT '2'::INTERVAL MINUTE * '1'::INTERVAL MONTH;
SELECT '2'::INTERVAL MINUTE * '1'::INTERVAL YEAR TO MONTH;
SELECT '2'::INTERVAL MINUTE * '1'::INTERVAL DAY;
SELECT '2'::INTERVAL MINUTE * '1'::INTERVAL HOUR;
SELECT '2'::INTERVAL MINUTE * '1'::INTERVAL MINUTE;
SELECT '2'::INTERVAL MINUTE * '1'::INTERVAL SECOND;
SELECT '2'::INTERVAL MINUTE * '1'::INTERVAL DAY TO HOUR;
SELECT '2'::INTERVAL MINUTE * '1'::INTERVAL DAY TO MINUTE;
SELECT '2'::INTERVAL MINUTE * '1'::INTERVAL DAY TO SECOND;
SELECT '2'::INTERVAL MINUTE * '1'::INTERVAL HOUR TO MINUTE;
SELECT '2'::INTERVAL MINUTE * '1'::INTERVAL HOUR TO SECOND;
SELECT '2'::INTERVAL MINUTE * '1'::INTERVAL MINUTE TO SECOND;

// "*" : INTERVAL SECOND;
SELECT '2'::INTERVAL SECOND * '1'::INTERVAL YEAR;
SELECT '2'::INTERVAL SECOND * '1'::INTERVAL MONTH;
SELECT '2'::INTERVAL SECOND * '1'::INTERVAL YEAR TO MONTH;
SELECT '2'::INTERVAL SECOND * '1'::INTERVAL DAY;
SELECT '2'::INTERVAL SECOND * '1'::INTERVAL HOUR;
SELECT '2'::INTERVAL SECOND * '1'::INTERVAL MINUTE;
SELECT '2'::INTERVAL SECOND * '1'::INTERVAL SECOND;
SELECT '2'::INTERVAL SECOND * '1'::INTERVAL DAY TO HOUR;
SELECT '2'::INTERVAL SECOND * '1'::INTERVAL DAY TO MINUTE;
SELECT '2'::INTERVAL SECOND * '1'::INTERVAL DAY TO SECOND;
SELECT '2'::INTERVAL SECOND * '1'::INTERVAL HOUR TO MINUTE;
SELECT '2'::INTERVAL SECOND * '1'::INTERVAL HOUR TO SECOND;
SELECT '2'::INTERVAL SECOND * '1'::INTERVAL MINUTE TO SECOND;

// "*" : INTERVAL YEAR TO MONTH;
SELECT '2'::INTERVAL YEAR TO MONTH * '1'::INTERVAL YEAR;
SELECT '2'::INTERVAL YEAR TO MONTH * '1'::INTERVAL MONTH;
SELECT '2'::INTERVAL YEAR TO MONTH * '1'::INTERVAL YEAR TO MONTH;
SELECT '2'::INTERVAL YEAR TO MONTH * '1'::INTERVAL DAY;
SELECT '2'::INTERVAL YEAR TO MONTH * '1'::INTERVAL HOUR;
SELECT '2'::INTERVAL YEAR TO MONTH * '1'::INTERVAL MINUTE;
SELECT '2'::INTERVAL YEAR TO MONTH * '1'::INTERVAL SECOND;
SELECT '2'::INTERVAL YEAR TO MONTH * '1'::INTERVAL DAY TO HOUR;
SELECT '2'::INTERVAL YEAR TO MONTH * '1'::INTERVAL DAY TO MINUTE;
SELECT '2'::INTERVAL YEAR TO MONTH * '1'::INTERVAL DAY TO SECOND;
SELECT '2'::INTERVAL YEAR TO MONTH * '1'::INTERVAL HOUR TO MINUTE;
SELECT '2'::INTERVAL YEAR TO MONTH * '1'::INTERVAL HOUR TO SECOND;
SELECT '2'::INTERVAL YEAR TO MONTH * '1'::INTERVAL MINUTE TO SECOND;

// "*" : INTERVAL DAY TO HOUR;
SELECT '2'::INTERVAL DAY TO HOUR * '1'::INTERVAL YEAR;
SELECT '2'::INTERVAL DAY TO HOUR * '1'::INTERVAL MONTH;
SELECT '2'::INTERVAL DAY TO HOUR * '1'::INTERVAL YEAR TO MONTH;
SELECT '2'::INTERVAL DAY TO HOUR * '1'::INTERVAL DAY;
SELECT '2'::INTERVAL DAY TO HOUR * '1'::INTERVAL HOUR;
SELECT '2'::INTERVAL DAY TO HOUR * '1'::INTERVAL MINUTE;
SELECT '2'::INTERVAL DAY TO HOUR * '1'::INTERVAL SECOND;
SELECT '2'::INTERVAL DAY TO HOUR * '1'::INTERVAL DAY TO HOUR;
SELECT '2'::INTERVAL DAY TO HOUR * '1'::INTERVAL DAY TO MINUTE;
SELECT '2'::INTERVAL DAY TO HOUR * '1'::INTERVAL DAY TO SECOND;
SELECT '2'::INTERVAL DAY TO HOUR * '1'::INTERVAL HOUR TO MINUTE;
SELECT '2'::INTERVAL DAY TO HOUR * '1'::INTERVAL HOUR TO SECOND;
SELECT '2'::INTERVAL DAY TO HOUR * '1'::INTERVAL MINUTE TO SECOND;

// "*" : INTERVAL DAY TO MINUTE;
SELECT '2'::INTERVAL DAY TO MINUTE * '1'::INTERVAL YEAR;
SELECT '2'::INTERVAL DAY TO MINUTE * '1'::INTERVAL MONTH;
SELECT '2'::INTERVAL DAY TO MINUTE * '1'::INTERVAL YEAR TO MONTH;
SELECT '2'::INTERVAL DAY TO MINUTE * '1'::INTERVAL DAY;
SELECT '2'::INTERVAL DAY TO MINUTE * '1'::INTERVAL HOUR;
SELECT '2'::INTERVAL DAY TO MINUTE * '1'::INTERVAL MINUTE;
SELECT '2'::INTERVAL DAY TO MINUTE * '1'::INTERVAL SECOND;
SELECT '2'::INTERVAL DAY TO MINUTE * '1'::INTERVAL DAY TO HOUR;
SELECT '2'::INTERVAL DAY TO MINUTE * '1'::INTERVAL DAY TO MINUTE;
SELECT '2'::INTERVAL DAY TO MINUTE * '1'::INTERVAL DAY TO SECOND;
SELECT '2'::INTERVAL DAY TO MINUTE * '1'::INTERVAL HOUR TO MINUTE;
SELECT '2'::INTERVAL DAY TO MINUTE * '1'::INTERVAL HOUR TO SECOND;
SELECT '2'::INTERVAL DAY TO MINUTE * '1'::INTERVAL MINUTE TO SECOND;

// "*" : INTERVAL DAY TO SECOND;
SELECT '2'::INTERVAL DAY TO SECOND * '1'::INTERVAL YEAR;
SELECT '2'::INTERVAL DAY TO SECOND * '1'::INTERVAL MONTH;
SELECT '2'::INTERVAL DAY TO SECOND * '1'::INTERVAL YEAR TO MONTH;
SELECT '2'::INTERVAL DAY TO SECOND * '1'::INTERVAL DAY;
SELECT '2'::INTERVAL DAY TO SECOND * '1'::INTERVAL HOUR;
SELECT '2'::INTERVAL DAY TO SECOND * '1'::INTERVAL MINUTE;
SELECT '2'::INTERVAL DAY TO SECOND * '1'::INTERVAL SECOND;
SELECT '2'::INTERVAL DAY TO SECOND * '1'::INTERVAL DAY TO HOUR;
SELECT '2'::INTERVAL DAY TO SECOND * '1'::INTERVAL DAY TO MINUTE;
SELECT '2'::INTERVAL DAY TO SECOND * '1'::INTERVAL DAY TO SECOND;
SELECT '2'::INTERVAL DAY TO SECOND * '1'::INTERVAL HOUR TO MINUTE;
SELECT '2'::INTERVAL DAY TO SECOND * '1'::INTERVAL HOUR TO SECOND;
SELECT '2'::INTERVAL DAY TO SECOND * '1'::INTERVAL MINUTE TO SECOND;

// "*" : INTERVAL HOUR TO MINUTE;
SELECT '2'::INTERVAL HOUR TO MINUTE * '1'::INTERVAL YEAR;
SELECT '2'::INTERVAL HOUR TO MINUTE * '1'::INTERVAL MONTH;
SELECT '2'::INTERVAL HOUR TO MINUTE * '1'::INTERVAL YEAR TO MONTH;
SELECT '2'::INTERVAL HOUR TO MINUTE * '1'::INTERVAL DAY;
SELECT '2'::INTERVAL HOUR TO MINUTE * '1'::INTERVAL HOUR;
SELECT '2'::INTERVAL HOUR TO MINUTE * '1'::INTERVAL MINUTE;
SELECT '2'::INTERVAL HOUR TO MINUTE * '1'::INTERVAL SECOND;
SELECT '2'::INTERVAL HOUR TO MINUTE * '1'::INTERVAL DAY TO HOUR;
SELECT '2'::INTERVAL HOUR TO MINUTE * '1'::INTERVAL DAY TO MINUTE;
SELECT '2'::INTERVAL HOUR TO MINUTE * '1'::INTERVAL DAY TO SECOND;
SELECT '2'::INTERVAL HOUR TO MINUTE * '1'::INTERVAL HOUR TO MINUTE;
SELECT '2'::INTERVAL HOUR TO MINUTE * '1'::INTERVAL HOUR TO SECOND;
SELECT '2'::INTERVAL HOUR TO MINUTE * '1'::INTERVAL MINUTE TO SECOND;

// "*" : INTERVAL HOUR TO SECOND;
SELECT '2'::INTERVAL HOUR TO SECOND * '1'::INTERVAL YEAR;
SELECT '2'::INTERVAL HOUR TO SECOND * '1'::INTERVAL MONTH;
SELECT '2'::INTERVAL HOUR TO SECOND * '1'::INTERVAL YEAR TO MONTH;
SELECT '2'::INTERVAL HOUR TO SECOND * '1'::INTERVAL DAY;
SELECT '2'::INTERVAL HOUR TO SECOND * '1'::INTERVAL HOUR;
SELECT '2'::INTERVAL HOUR TO SECOND * '1'::INTERVAL MINUTE;
SELECT '2'::INTERVAL HOUR TO SECOND * '1'::INTERVAL SECOND;
SELECT '2'::INTERVAL HOUR TO SECOND * '1'::INTERVAL DAY TO HOUR;
SELECT '2'::INTERVAL HOUR TO SECOND * '1'::INTERVAL DAY TO MINUTE;
SELECT '2'::INTERVAL HOUR TO SECOND * '1'::INTERVAL DAY TO SECOND;
SELECT '2'::INTERVAL HOUR TO SECOND * '1'::INTERVAL HOUR TO MINUTE;
SELECT '2'::INTERVAL HOUR TO SECOND * '1'::INTERVAL HOUR TO SECOND;
SELECT '2'::INTERVAL HOUR TO SECOND * '1'::INTERVAL MINUTE TO SECOND;

// "*" : INTERVAL MINUTE TO SECOND;
SELECT '2'::INTERVAL MINUTE TO SECOND * '1'::INTERVAL YEAR;
SELECT '2'::INTERVAL MINUTE TO SECOND * '1'::INTERVAL MONTH;
SELECT '2'::INTERVAL MINUTE TO SECOND * '1'::INTERVAL YEAR TO MONTH;
SELECT '2'::INTERVAL MINUTE TO SECOND * '1'::INTERVAL DAY;
SELECT '2'::INTERVAL MINUTE TO SECOND * '1'::INTERVAL HOUR;
SELECT '2'::INTERVAL MINUTE TO SECOND * '1'::INTERVAL MINUTE;
SELECT '2'::INTERVAL MINUTE TO SECOND * '1'::INTERVAL SECOND;
SELECT '2'::INTERVAL MINUTE TO SECOND * '1'::INTERVAL DAY TO HOUR;
SELECT '2'::INTERVAL MINUTE TO SECOND * '1'::INTERVAL DAY TO MINUTE;
SELECT '2'::INTERVAL MINUTE TO SECOND * '1'::INTERVAL DAY TO SECOND;
SELECT '2'::INTERVAL MINUTE TO SECOND * '1'::INTERVAL HOUR TO MINUTE;
SELECT '2'::INTERVAL MINUTE TO SECOND * '1'::INTERVAL HOUR TO SECOND;
SELECT '2'::INTERVAL MINUTE TO SECOND * '1'::INTERVAL MINUTE TO SECOND;

// "/" : INTERVAL YEAR
SELECT '2'::INTERVAL YEAR / '1'::INTERVAL YEAR;
SELECT '2'::INTERVAL YEAR / '1'::INTERVAL MONTH;
SELECT '2'::INTERVAL YEAR / '1'::INTERVAL YEAR TO MONTH;
SELECT '2'::INTERVAL YEAR / '1'::INTERVAL DAY;
SELECT '2'::INTERVAL YEAR / '1'::INTERVAL HOUR;
SELECT '2'::INTERVAL YEAR / '1'::INTERVAL MINUTE;
SELECT '2'::INTERVAL YEAR / '1'::INTERVAL SECOND;
SELECT '2'::INTERVAL YEAR / '1'::INTERVAL DAY TO HOUR;
SELECT '2'::INTERVAL YEAR / '1'::INTERVAL DAY TO MINUTE;
SELECT '2'::INTERVAL YEAR / '1'::INTERVAL DAY TO SECOND;
SELECT '2'::INTERVAL YEAR / '1'::INTERVAL HOUR TO MINUTE;
SELECT '2'::INTERVAL YEAR / '1'::INTERVAL HOUR TO SECOND;
SELECT '2'::INTERVAL YEAR / '1'::INTERVAL MINUTE TO SECOND;

// "/" : INTERVAL MONTH
SELECT '2'::INTERVAL MONTH / '1'::INTERVAL YEAR;
SELECT '2'::INTERVAL MONTH / '1'::INTERVAL MONTH;
SELECT '2'::INTERVAL MONTH / '1'::INTERVAL YEAR TO MONTH;
SELECT '2'::INTERVAL MONTH / '1'::INTERVAL DAY;
SELECT '2'::INTERVAL MONTH / '1'::INTERVAL HOUR;
SELECT '2'::INTERVAL MONTH / '1'::INTERVAL MINUTE;
SELECT '2'::INTERVAL MONTH / '1'::INTERVAL SECOND;
SELECT '2'::INTERVAL MONTH / '1'::INTERVAL DAY TO HOUR;
SELECT '2'::INTERVAL MONTH / '1'::INTERVAL DAY TO MINUTE;
SELECT '2'::INTERVAL MONTH / '1'::INTERVAL DAY TO SECOND;
SELECT '2'::INTERVAL MONTH / '1'::INTERVAL HOUR TO MINUTE;
SELECT '2'::INTERVAL MONTH / '1'::INTERVAL HOUR TO SECOND;
SELECT '2'::INTERVAL MONTH / '1'::INTERVAL MINUTE TO SECOND;

// "/" : INTERVAL DAY
SELECT '2'::INTERVAL DAY / '1'::INTERVAL YEAR;
SELECT '2'::INTERVAL DAY / '1'::INTERVAL MONTH;
SELECT '2'::INTERVAL DAY / '1'::INTERVAL YEAR TO MONTH;
SELECT '2'::INTERVAL DAY / '1'::INTERVAL DAY;
SELECT '2'::INTERVAL DAY / '1'::INTERVAL HOUR;
SELECT '2'::INTERVAL DAY / '1'::INTERVAL MINUTE;
SELECT '2'::INTERVAL DAY / '1'::INTERVAL SECOND;
SELECT '2'::INTERVAL DAY / '1'::INTERVAL DAY TO HOUR;
SELECT '2'::INTERVAL DAY / '1'::INTERVAL DAY TO MINUTE;
SELECT '2'::INTERVAL DAY / '1'::INTERVAL DAY TO SECOND;
SELECT '2'::INTERVAL DAY / '1'::INTERVAL HOUR TO MINUTE;
SELECT '2'::INTERVAL DAY / '1'::INTERVAL HOUR TO SECOND;
SELECT '2'::INTERVAL DAY / '1'::INTERVAL MINUTE TO SECOND;

// "/" : INTERVAL HOUR
SELECT '2'::INTERVAL HOUR / '1'::INTERVAL YEAR;
SELECT '2'::INTERVAL HOUR / '1'::INTERVAL MONTH;
SELECT '2'::INTERVAL HOUR / '1'::INTERVAL YEAR TO MONTH;
SELECT '2'::INTERVAL HOUR / '1'::INTERVAL DAY;
SELECT '2'::INTERVAL HOUR / '1'::INTERVAL HOUR;
SELECT '2'::INTERVAL HOUR / '1'::INTERVAL MINUTE;
SELECT '2'::INTERVAL HOUR / '1'::INTERVAL SECOND;
SELECT '2'::INTERVAL HOUR / '1'::INTERVAL DAY TO HOUR;
SELECT '2'::INTERVAL HOUR / '1'::INTERVAL DAY TO MINUTE;
SELECT '2'::INTERVAL HOUR / '1'::INTERVAL DAY TO SECOND;
SELECT '2'::INTERVAL HOUR / '1'::INTERVAL HOUR TO MINUTE;
SELECT '2'::INTERVAL HOUR / '1'::INTERVAL HOUR TO SECOND;
SELECT '2'::INTERVAL HOUR / '1'::INTERVAL MINUTE TO SECOND;

// "/" : INTERVAL MINUTE
SELECT '2'::INTERVAL MINUTE / '1'::INTERVAL YEAR;
SELECT '2'::INTERVAL MINUTE / '1'::INTERVAL MONTH;
SELECT '2'::INTERVAL MINUTE / '1'::INTERVAL YEAR TO MONTH;
SELECT '2'::INTERVAL MINUTE / '1'::INTERVAL DAY;
SELECT '2'::INTERVAL MINUTE / '1'::INTERVAL HOUR;
SELECT '2'::INTERVAL MINUTE / '1'::INTERVAL MINUTE;
SELECT '2'::INTERVAL MINUTE / '1'::INTERVAL SECOND;
SELECT '2'::INTERVAL MINUTE / '1'::INTERVAL DAY TO HOUR;
SELECT '2'::INTERVAL MINUTE / '1'::INTERVAL DAY TO MINUTE;
SELECT '2'::INTERVAL MINUTE / '1'::INTERVAL DAY TO SECOND;
SELECT '2'::INTERVAL MINUTE / '1'::INTERVAL HOUR TO MINUTE;
SELECT '2'::INTERVAL MINUTE / '1'::INTERVAL HOUR TO SECOND;
SELECT '2'::INTERVAL MINUTE / '1'::INTERVAL MINUTE TO SECOND;

// "/" : INTERVAL SECOND
SELECT '2'::INTERVAL SECOND / '1'::INTERVAL YEAR;
SELECT '2'::INTERVAL SECOND / '1'::INTERVAL MONTH;
SELECT '2'::INTERVAL SECOND / '1'::INTERVAL YEAR TO MONTH;
SELECT '2'::INTERVAL SECOND / '1'::INTERVAL DAY;
SELECT '2'::INTERVAL SECOND / '1'::INTERVAL HOUR;
SELECT '2'::INTERVAL SECOND / '1'::INTERVAL MINUTE;
SELECT '2'::INTERVAL SECOND / '1'::INTERVAL SECOND;
SELECT '2'::INTERVAL SECOND / '1'::INTERVAL DAY TO HOUR;
SELECT '2'::INTERVAL SECOND / '1'::INTERVAL DAY TO MINUTE;
SELECT '2'::INTERVAL SECOND / '1'::INTERVAL DAY TO SECOND;
SELECT '2'::INTERVAL SECOND / '1'::INTERVAL HOUR TO MINUTE;
SELECT '2'::INTERVAL SECOND / '1'::INTERVAL HOUR TO SECOND;
SELECT '2'::INTERVAL SECOND / '1'::INTERVAL MINUTE TO SECOND;

// "/" : INTERVAL YEAR TO MONTH
SELECT '2'::INTERVAL YEAR TO MONTH / '1'::INTERVAL YEAR;
SELECT '2'::INTERVAL YEAR TO MONTH / '1'::INTERVAL MONTH;
SELECT '2'::INTERVAL YEAR TO MONTH / '1'::INTERVAL YEAR TO MONTH;
SELECT '2'::INTERVAL YEAR TO MONTH / '1'::INTERVAL DAY;
SELECT '2'::INTERVAL YEAR TO MONTH / '1'::INTERVAL HOUR;
SELECT '2'::INTERVAL YEAR TO MONTH / '1'::INTERVAL MINUTE;
SELECT '2'::INTERVAL YEAR TO MONTH / '1'::INTERVAL SECOND;
SELECT '2'::INTERVAL YEAR TO MONTH / '1'::INTERVAL DAY TO HOUR;
SELECT '2'::INTERVAL YEAR TO MONTH / '1'::INTERVAL DAY TO MINUTE;
SELECT '2'::INTERVAL YEAR TO MONTH / '1'::INTERVAL DAY TO SECOND;
SELECT '2'::INTERVAL YEAR TO MONTH / '1'::INTERVAL HOUR TO MINUTE;
SELECT '2'::INTERVAL YEAR TO MONTH / '1'::INTERVAL HOUR TO SECOND;
SELECT '2'::INTERVAL YEAR TO MONTH / '1'::INTERVAL MINUTE TO SECOND;

// "/" : INTERVAL DAY TO HOUR
SELECT '2'::INTERVAL DAY TO HOUR / '1'::INTERVAL YEAR;
SELECT '2'::INTERVAL DAY TO HOUR / '1'::INTERVAL MONTH;
SELECT '2'::INTERVAL DAY TO HOUR / '1'::INTERVAL YEAR TO MONTH;
SELECT '2'::INTERVAL DAY TO HOUR / '1'::INTERVAL DAY;
SELECT '2'::INTERVAL DAY TO HOUR / '1'::INTERVAL HOUR;
SELECT '2'::INTERVAL DAY TO HOUR / '1'::INTERVAL MINUTE;
SELECT '2'::INTERVAL DAY TO HOUR / '1'::INTERVAL SECOND;
SELECT '2'::INTERVAL DAY TO HOUR / '1'::INTERVAL DAY TO HOUR;
SELECT '2'::INTERVAL DAY TO HOUR / '1'::INTERVAL DAY TO MINUTE;
SELECT '2'::INTERVAL DAY TO HOUR / '1'::INTERVAL DAY TO SECOND;
SELECT '2'::INTERVAL DAY TO HOUR / '1'::INTERVAL HOUR TO MINUTE;
SELECT '2'::INTERVAL DAY TO HOUR / '1'::INTERVAL HOUR TO SECOND;
SELECT '2'::INTERVAL DAY TO HOUR / '1'::INTERVAL MINUTE TO SECOND;

// "/" : INTERVAL DAY TO MINUTE
SELECT '2'::INTERVAL DAY TO MINUTE / '1'::INTERVAL YEAR;
SELECT '2'::INTERVAL DAY TO MINUTE / '1'::INTERVAL MONTH;
SELECT '2'::INTERVAL DAY TO MINUTE / '1'::INTERVAL YEAR TO MONTH;
SELECT '2'::INTERVAL DAY TO MINUTE / '1'::INTERVAL DAY;
SELECT '2'::INTERVAL DAY TO MINUTE / '1'::INTERVAL HOUR;
SELECT '2'::INTERVAL DAY TO MINUTE / '1'::INTERVAL MINUTE;
SELECT '2'::INTERVAL DAY TO MINUTE / '1'::INTERVAL SECOND;
SELECT '2'::INTERVAL DAY TO MINUTE / '1'::INTERVAL DAY TO HOUR;
SELECT '2'::INTERVAL DAY TO MINUTE / '1'::INTERVAL DAY TO MINUTE;
SELECT '2'::INTERVAL DAY TO MINUTE / '1'::INTERVAL DAY TO SECOND;
SELECT '2'::INTERVAL DAY TO MINUTE / '1'::INTERVAL HOUR TO MINUTE;
SELECT '2'::INTERVAL DAY TO MINUTE / '1'::INTERVAL HOUR TO SECOND;
SELECT '2'::INTERVAL DAY TO MINUTE / '1'::INTERVAL MINUTE TO SECOND;

// "/" : INTERVAL DAY TO SECOND
SELECT '2'::INTERVAL DAY TO SECOND / '1'::INTERVAL YEAR;
SELECT '2'::INTERVAL DAY TO SECOND / '1'::INTERVAL MONTH;
SELECT '2'::INTERVAL DAY TO SECOND / '1'::INTERVAL YEAR TO MONTH;
SELECT '2'::INTERVAL DAY TO SECOND / '1'::INTERVAL DAY;
SELECT '2'::INTERVAL DAY TO SECOND / '1'::INTERVAL HOUR;
SELECT '2'::INTERVAL DAY TO SECOND / '1'::INTERVAL MINUTE;
SELECT '2'::INTERVAL DAY TO SECOND / '1'::INTERVAL SECOND;
SELECT '2'::INTERVAL DAY TO SECOND / '1'::INTERVAL DAY TO HOUR;
SELECT '2'::INTERVAL DAY TO SECOND / '1'::INTERVAL DAY TO MINUTE;
SELECT '2'::INTERVAL DAY TO SECOND / '1'::INTERVAL DAY TO SECOND;
SELECT '2'::INTERVAL DAY TO SECOND / '1'::INTERVAL HOUR TO MINUTE;
SELECT '2'::INTERVAL DAY TO SECOND / '1'::INTERVAL HOUR TO SECOND;
SELECT '2'::INTERVAL DAY TO SECOND / '1'::INTERVAL MINUTE TO SECOND;

// "/" : INTERVAL HOUR TO MINUTE
SELECT '2'::INTERVAL HOUR TO MINUTE / '1'::INTERVAL YEAR;
SELECT '2'::INTERVAL HOUR TO MINUTE / '1'::INTERVAL MONTH;
SELECT '2'::INTERVAL HOUR TO MINUTE / '1'::INTERVAL YEAR TO MONTH;
SELECT '2'::INTERVAL HOUR TO MINUTE / '1'::INTERVAL DAY;
SELECT '2'::INTERVAL HOUR TO MINUTE / '1'::INTERVAL HOUR;
SELECT '2'::INTERVAL HOUR TO MINUTE / '1'::INTERVAL MINUTE;
SELECT '2'::INTERVAL HOUR TO MINUTE / '1'::INTERVAL SECOND;
SELECT '2'::INTERVAL HOUR TO MINUTE / '1'::INTERVAL DAY TO HOUR;
SELECT '2'::INTERVAL HOUR TO MINUTE / '1'::INTERVAL DAY TO MINUTE;
SELECT '2'::INTERVAL HOUR TO MINUTE / '1'::INTERVAL DAY TO SECOND;
SELECT '2'::INTERVAL HOUR TO MINUTE / '1'::INTERVAL HOUR TO MINUTE;
SELECT '2'::INTERVAL HOUR TO MINUTE / '1'::INTERVAL HOUR TO SECOND;
SELECT '2'::INTERVAL HOUR TO MINUTE / '1'::INTERVAL MINUTE TO SECOND;

// "/" : INTERVAL HOUR TO SECOND
SELECT '2'::INTERVAL HOUR TO SECOND / '1'::INTERVAL YEAR;
SELECT '2'::INTERVAL HOUR TO SECOND / '1'::INTERVAL MONTH;
SELECT '2'::INTERVAL HOUR TO SECOND / '1'::INTERVAL YEAR TO MONTH;
SELECT '2'::INTERVAL HOUR TO SECOND / '1'::INTERVAL DAY;
SELECT '2'::INTERVAL HOUR TO SECOND / '1'::INTERVAL HOUR;
SELECT '2'::INTERVAL HOUR TO SECOND / '1'::INTERVAL MINUTE;
SELECT '2'::INTERVAL HOUR TO SECOND / '1'::INTERVAL SECOND;
SELECT '2'::INTERVAL HOUR TO SECOND / '1'::INTERVAL DAY TO HOUR;
SELECT '2'::INTERVAL HOUR TO SECOND / '1'::INTERVAL DAY TO MINUTE;
SELECT '2'::INTERVAL HOUR TO SECOND / '1'::INTERVAL DAY TO SECOND;
SELECT '2'::INTERVAL HOUR TO SECOND / '1'::INTERVAL HOUR TO MINUTE;
SELECT '2'::INTERVAL HOUR TO SECOND / '1'::INTERVAL HOUR TO SECOND;
SELECT '2'::INTERVAL HOUR TO SECOND / '1'::INTERVAL MINUTE TO SECOND;

// "/" : INTERVAL MINUTE TO SECOND
SELECT '2'::INTERVAL MINUTE TO SECOND / '1'::INTERVAL YEAR;
SELECT '2'::INTERVAL MINUTE TO SECOND / '1'::INTERVAL MONTH;
SELECT '2'::INTERVAL MINUTE TO SECOND / '1'::INTERVAL YEAR TO MONTH;
SELECT '2'::INTERVAL MINUTE TO SECOND / '1'::INTERVAL DAY;
SELECT '2'::INTERVAL MINUTE TO SECOND / '1'::INTERVAL HOUR;
SELECT '2'::INTERVAL MINUTE TO SECOND / '1'::INTERVAL MINUTE;
SELECT '2'::INTERVAL MINUTE TO SECOND / '1'::INTERVAL SECOND;
SELECT '2'::INTERVAL MINUTE TO SECOND / '1'::INTERVAL DAY TO HOUR;
SELECT '2'::INTERVAL MINUTE TO SECOND / '1'::INTERVAL DAY TO MINUTE;
SELECT '2'::INTERVAL MINUTE TO SECOND / '1'::INTERVAL DAY TO SECOND;
SELECT '2'::INTERVAL MINUTE TO SECOND / '1'::INTERVAL HOUR TO MINUTE;
SELECT '2'::INTERVAL MINUTE TO SECOND / '1'::INTERVAL HOUR TO SECOND;
SELECT '2'::INTERVAL MINUTE TO SECOND / '1'::INTERVAL MINUTE TO SECOND;

!4 XG-TYPE-INTERVAL-003 INTERVAL 类型运算 : 和 NULL、空串、空格 运算

//和 NULL 四则运算 : +
SELECT '1'::INTERVAL YEAR + NULL;
SELECT '1'::INTERVAL MONTH + NULL;
SELECT '1'::INTERVAL DAY + NULL;
SELECT '1'::INTERVAL HOUR + NULL;
SELECT '1'::INTERVAL MINUTE + NULL;
SELECT '1'::INTERVAL SECOND + NULL;
SELECT '1'::INTERVAL YEAR TO MONTH + NULL;
SELECT '1'::INTERVAL DAY TO HOUR + NULL;
SELECT '1'::INTERVAL DAY TO MINUTE + NULL;
SELECT '1'::INTERVAL DAY TO SECOND + NULL;
SELECT '1'::INTERVAL HOUR TO MINUTE + NULL;
SELECT '1'::INTERVAL HOUR TO SECOND + NULL;
SELECT '1'::INTERVAL MINUTE TO SECOND + NULL;

//和 NULL 四则运算 : -
SELECT '1'::INTERVAL YEAR - NULL;
SELECT '1'::INTERVAL MONTH - NULL;
SELECT '1'::INTERVAL DAY - NULL;
SELECT '1'::INTERVAL HOUR - NULL;
SELECT '1'::INTERVAL MINUTE - NULL;
SELECT '1'::INTERVAL SECOND - NULL;
SELECT '1'::INTERVAL YEAR TO MONTH - NULL;
SELECT '1'::INTERVAL DAY TO HOUR - NULL;
SELECT '1'::INTERVAL DAY TO MINUTE - NULL;
SELECT '1'::INTERVAL DAY TO SECOND - NULL;
SELECT '1'::INTERVAL HOUR TO MINUTE - NULL;
SELECT '1'::INTERVAL HOUR TO SECOND - NULL;
SELECT '1'::INTERVAL MINUTE TO SECOND - NULL;

//和 NULL 四则运算 : *
SELECT '1'::INTERVAL YEAR * NULL;
SELECT '1'::INTERVAL MONTH * NULL;
SELECT '1'::INTERVAL DAY * NULL;
SELECT '1'::INTERVAL HOUR * NULL;
SELECT '1'::INTERVAL MINUTE * NULL;
SELECT '1'::INTERVAL SECOND * NULL;
SELECT '1'::INTERVAL YEAR TO MONTH * NULL;
SELECT '1'::INTERVAL DAY TO HOUR * NULL;
SELECT '1'::INTERVAL DAY TO MINUTE * NULL;
SELECT '1'::INTERVAL DAY TO SECOND * NULL;
SELECT '1'::INTERVAL HOUR TO MINUTE * NULL;
SELECT '1'::INTERVAL HOUR TO SECOND * NULL;
SELECT '1'::INTERVAL MINUTE TO SECOND * NULL;

//和 NULL 四则运算 : /
SELECT '1'::INTERVAL YEAR / NULL;
SELECT '1'::INTERVAL MONTH / NULL;
SELECT '1'::INTERVAL DAY / NULL;
SELECT '1'::INTERVAL HOUR / NULL;
SELECT '1'::INTERVAL MINUTE / NULL;
SELECT '1'::INTERVAL SECOND / NULL;
SELECT '1'::INTERVAL YEAR TO MONTH / NULL;
SELECT '1'::INTERVAL DAY TO HOUR / NULL;
SELECT '1'::INTERVAL DAY TO MINUTE / NULL;
SELECT '1'::INTERVAL DAY TO SECOND / NULL;
SELECT '1'::INTERVAL HOUR TO MINUTE / NULL;
SELECT '1'::INTERVAL HOUR TO SECOND / NULL;
SELECT '1'::INTERVAL MINUTE TO SECOND / NULL;

//和 空串 四则运算 : +
SELECT '1'::INTERVAL YEAR + '';
SELECT '1'::INTERVAL MONTH + '';
SELECT '1'::INTERVAL DAY + '';
SELECT '1'::INTERVAL HOUR + '';
SELECT '1'::INTERVAL MINUTE + '';
SELECT '1'::INTERVAL SECOND + '';
SELECT '1'::INTERVAL YEAR TO MONTH + '';
SELECT '1'::INTERVAL DAY TO HOUR + '';
SELECT '1'::INTERVAL DAY TO MINUTE + '';
SELECT '1'::INTERVAL DAY TO SECOND + '';
SELECT '1'::INTERVAL HOUR TO MINUTE + '';
SELECT '1'::INTERVAL HOUR TO SECOND + '';
SELECT '1'::INTERVAL MINUTE TO SECOND + '';

//和 空串 四则运算 : -
SELECT '1'::INTERVAL YEAR - '';
SELECT '1'::INTERVAL MONTH - '';
SELECT '1'::INTERVAL DAY - '';
SELECT '1'::INTERVAL HOUR - '';
SELECT '1'::INTERVAL MINUTE - '';
SELECT '1'::INTERVAL SECOND - '';
SELECT '1'::INTERVAL YEAR TO MONTH - '';
SELECT '1'::INTERVAL DAY TO HOUR - '';
SELECT '1'::INTERVAL DAY TO MINUTE - '';
SELECT '1'::INTERVAL DAY TO SECOND - '';
SELECT '1'::INTERVAL HOUR TO MINUTE - '';
SELECT '1'::INTERVAL HOUR TO SECOND - '';
SELECT '1'::INTERVAL MINUTE TO SECOND - '';

//和 空串 四则运算 : *
SELECT '1'::INTERVAL YEAR * '';
SELECT '1'::INTERVAL MONTH * '';
SELECT '1'::INTERVAL DAY * '';
SELECT '1'::INTERVAL HOUR * '';
SELECT '1'::INTERVAL MINUTE * '';
SELECT '1'::INTERVAL SECOND * '';
SELECT '1'::INTERVAL YEAR TO MONTH * '';
SELECT '1'::INTERVAL DAY TO HOUR * '';
SELECT '1'::INTERVAL DAY TO MINUTE * '';
SELECT '1'::INTERVAL DAY TO SECOND * '';
SELECT '1'::INTERVAL HOUR TO MINUTE * '';
SELECT '1'::INTERVAL HOUR TO SECOND * '';
SELECT '1'::INTERVAL MINUTE TO SECOND * '';

//和 空串 四则运算 : /
SELECT '1'::INTERVAL YEAR / '';
SELECT '1'::INTERVAL MONTH / '';
SELECT '1'::INTERVAL DAY / '';
SELECT '1'::INTERVAL HOUR / '';
SELECT '1'::INTERVAL MINUTE / '';
SELECT '1'::INTERVAL SECOND / '';
SELECT '1'::INTERVAL YEAR TO MONTH / '';
SELECT '1'::INTERVAL DAY TO HOUR / '';
SELECT '1'::INTERVAL DAY TO MINUTE / '';
SELECT '1'::INTERVAL DAY TO SECOND / '';
SELECT '1'::INTERVAL HOUR TO MINUTE / '';
SELECT '1'::INTERVAL HOUR TO SECOND / '';
SELECT '1'::INTERVAL MINUTE TO SECOND / '';

//和 空格 四则运算 : +
SELECT '1'::INTERVAL YEAR + ' ';
SELECT '1'::INTERVAL MONTH + ' ';
SELECT '1'::INTERVAL DAY + ' ';
SELECT '1'::INTERVAL HOUR + ' ';
SELECT '1'::INTERVAL MINUTE + ' ';
SELECT '1'::INTERVAL SECOND + ' ';
SELECT '1'::INTERVAL YEAR TO MONTH + ' ';
SELECT '1'::INTERVAL DAY TO HOUR + ' ';
SELECT '1'::INTERVAL DAY TO MINUTE + ' ';
SELECT '1'::INTERVAL DAY TO SECOND + ' ';
SELECT '1'::INTERVAL HOUR TO MINUTE + ' ';
SELECT '1'::INTERVAL HOUR TO SECOND + ' ';
SELECT '1'::INTERVAL MINUTE TO SECOND + ' ';

//和 空格 四则运算 : -
SELECT '1'::INTERVAL YEAR - ' ';
SELECT '1'::INTERVAL MONTH - ' ';
SELECT '1'::INTERVAL DAY - ' ';
SELECT '1'::INTERVAL HOUR - ' ';
SELECT '1'::INTERVAL MINUTE - ' ';
SELECT '1'::INTERVAL SECOND - ' ';
SELECT '1'::INTERVAL YEAR TO MONTH - ' ';
SELECT '1'::INTERVAL DAY TO HOUR - ' ';
SELECT '1'::INTERVAL DAY TO MINUTE - ' ';
SELECT '1'::INTERVAL DAY TO SECOND - ' ';
SELECT '1'::INTERVAL HOUR TO MINUTE - ' ';
SELECT '1'::INTERVAL HOUR TO SECOND - ' ';
SELECT '1'::INTERVAL MINUTE TO SECOND - ' ';

//和 空格 四则运算 : *
SELECT '1'::INTERVAL YEAR * ' ';
SELECT '1'::INTERVAL MONTH * ' ';
SELECT '1'::INTERVAL DAY * ' ';
SELECT '1'::INTERVAL HOUR * ' ';
SELECT '1'::INTERVAL MINUTE * ' ';
SELECT '1'::INTERVAL SECOND * ' ';
SELECT '1'::INTERVAL YEAR TO MONTH * ' ';
SELECT '1'::INTERVAL DAY TO HOUR * ' ';
SELECT '1'::INTERVAL DAY TO MINUTE * ' ';
SELECT '1'::INTERVAL DAY TO SECOND * ' ';
SELECT '1'::INTERVAL HOUR TO MINUTE * ' ';
SELECT '1'::INTERVAL HOUR TO SECOND * ' ';
SELECT '1'::INTERVAL MINUTE TO SECOND * ' ';

//和 空格 四则运算 : /
SELECT '1'::INTERVAL YEAR / ' ';
SELECT '1'::INTERVAL MONTH / ' ';
SELECT '1'::INTERVAL DAY / ' ';
SELECT '1'::INTERVAL HOUR / ' ';
SELECT '1'::INTERVAL MINUTE / ' ';
SELECT '1'::INTERVAL SECOND / ' ';
SELECT '1'::INTERVAL YEAR TO MONTH / ' ';
SELECT '1'::INTERVAL DAY TO HOUR / ' ';
SELECT '1'::INTERVAL DAY TO MINUTE / ' ';
SELECT '1'::INTERVAL DAY TO SECOND / ' ';
SELECT '1'::INTERVAL HOUR TO MINUTE / ' ';
SELECT '1'::INTERVAL HOUR TO SECOND / ' ';
SELECT '1'::INTERVAL MINUTE TO SECOND / ' ';

!4 XG-TYPE-INTERVAL-004 INTERVAL 类型常量运算转换

//运算时左右分支都加强转 (INTERVAL 和 INT)
SELECT '1-0'::INTERVAL YEAR + 1::INT;
SELECT '0-1'::INTERVAL MONTH + 1::INT;
SELECT '1 0:00:00'::INTERVAL DAY + 1::INT;
SELECT '1:00:00'::INTERVAL HOUR + 1::INT;
SELECT '0:01:00'::INTERVAL MINUTE + 1::INT;
SELECT '0:00:01'::INTERVAL SECOND + 1::INT;
SELECT '0-1'::INTERVAL YEAR TO MONTH + 1::INT;
SELECT '1:00:00'::INTERVAL DAY TO HOUR + 1::INT;
SELECT '0:01:00'::INTERVAL DAY TO MINUTE + 1::INT;
SELECT '0:00:01'::INTERVAL DAY TO SECOND + 1::INT;
SELECT '0:01:00'::INTERVAL HOUR TO MINUTE + 1::INT;
SELECT '0:00:01'::INTERVAL HOUR TO SECOND + 1::INT;
SELECT '0:00:01'::INTERVAL MINUTE TO SECOND + 1::INT;

SELECT '1-0'::INTERVAL YEAR - 1::INT;
SELECT '0-1'::INTERVAL MONTH - 1::INT;
SELECT '1 0:00:00'::INTERVAL DAY - 1::INT;
SELECT '1:00:00'::INTERVAL HOUR - 1::INT;
SELECT '0:01:00'::INTERVAL MINUTE - 1::INT;
SELECT '0:00:01'::INTERVAL SECOND - 1::INT;
SELECT '0-1'::INTERVAL YEAR TO MONTH - 1::INT;
SELECT '1:00:00'::INTERVAL DAY TO HOUR - 1::INT;
SELECT '0:01:00'::INTERVAL DAY TO MINUTE - 1::INT;
SELECT '0:00:01'::INTERVAL DAY TO SECOND - 1::INT;
SELECT '0:01:00'::INTERVAL HOUR TO MINUTE - 1::INT;
SELECT '0:00:01'::INTERVAL HOUR TO SECOND - 1::INT;
SELECT '0:00:01'::INTERVAL MINUTE TO SECOND - 1::INT;

SELECT '1-0'::INTERVAL YEAR * 1::INT;
SELECT '0-1'::INTERVAL MONTH * 1::INT;
SELECT '1 0:00:00'::INTERVAL DAY * 1::INT;
SELECT '1:00:00'::INTERVAL HOUR * 1::INT;
SELECT '0:01:00'::INTERVAL MINUTE * 1::INT;
SELECT '0:00:01'::INTERVAL SECOND * 1::INT;
SELECT '0-1'::INTERVAL YEAR TO MONTH * 1::INT;
SELECT '1:00:00'::INTERVAL DAY TO HOUR * 1::INT;
SELECT '0:01:00'::INTERVAL DAY TO MINUTE * 1::INT;
SELECT '0:00:01'::INTERVAL DAY TO SECOND * 1::INT;
SELECT '0:01:00'::INTERVAL HOUR TO MINUTE * 1::INT;
SELECT '0:00:01'::INTERVAL HOUR TO SECOND * 1::INT;
SELECT '0:00:01'::INTERVAL MINUTE TO SECOND * 1::INT;

SELECT '1-0'::INTERVAL YEAR / 1::INT;
SELECT '0-1'::INTERVAL MONTH / 1::INT;
SELECT '1 0:00:00'::INTERVAL DAY / 1::INT;
SELECT '1:00:00'::INTERVAL HOUR / 1::INT;
SELECT '0:01:00'::INTERVAL MINUTE / 1::INT;
SELECT '0:00:01'::INTERVAL SECOND / 1::INT;
SELECT '0-1'::INTERVAL YEAR TO MONTH / 1::INT;
SELECT '1:00:00'::INTERVAL DAY TO HOUR / 1::INT;
SELECT '0:01:00'::INTERVAL DAY TO MINUTE / 1::INT;
SELECT '0:00:01'::INTERVAL DAY TO SECOND / 1::INT;
SELECT '0:01:00'::INTERVAL HOUR TO MINUTE / 1::INT;
SELECT '0:00:01'::INTERVAL HOUR TO SECOND / 1::INT;
SELECT '0:00:01'::INTERVAL MINUTE TO SECOND / 1::INT;

//运算时左右分支都加强转 (INTERVAL 和 DOUBLE)
SELECT '1-0'::INTERVAL YEAR + 1.5::DOUBLE;
SELECT '0-1'::INTERVAL MONTH + 1.5::DOUBLE;
SELECT '1 0:00:00'::INTERVAL DAY + 1.5::DOUBLE;
SELECT '1:00:00'::INTERVAL HOUR + 1.5::DOUBLE;
SELECT '0:01:00'::INTERVAL MINUTE + 1.5::DOUBLE;
SELECT '0:00:01'::INTERVAL SECOND + 1.5::DOUBLE;
SELECT '0-1'::INTERVAL YEAR TO MONTH + 1.5::DOUBLE;
SELECT '1:00:00'::INTERVAL DAY TO HOUR + 1.5::DOUBLE;
SELECT '0:01:00'::INTERVAL DAY TO MINUTE + 1.5::DOUBLE;
SELECT '0:00:01'::INTERVAL DAY TO SECOND + 1.5::DOUBLE;
SELECT '0:01:00'::INTERVAL HOUR TO MINUTE + 1.5::DOUBLE;
SELECT '0:00:01'::INTERVAL HOUR TO SECOND + 1.5::DOUBLE;
SELECT '0:00:01'::INTERVAL MINUTE TO SECOND + 1.5::DOUBLE;

SELECT '1-0'::INTERVAL YEAR - 1.5::DOUBLE;
SELECT '0-1'::INTERVAL MONTH - 1.5::DOUBLE;
SELECT '1 0:00:00'::INTERVAL DAY - 1.5::DOUBLE;
SELECT '1:00:00'::INTERVAL HOUR - 1.5::DOUBLE;
SELECT '0:01:00'::INTERVAL MINUTE - 1.5::DOUBLE;
SELECT '0:00:01'::INTERVAL SECOND - 1.5::DOUBLE;
SELECT '0-1'::INTERVAL YEAR TO MONTH - 1.5::DOUBLE;
SELECT '1:00:00'::INTERVAL DAY TO HOUR - 1.5::DOUBLE;
SELECT '0:01:00'::INTERVAL DAY TO MINUTE - 1.5::DOUBLE;
SELECT '0:00:01'::INTERVAL DAY TO SECOND - 1.5::DOUBLE;
SELECT '0:01:00'::INTERVAL HOUR TO MINUTE - 1.5::DOUBLE;
SELECT '0:00:01'::INTERVAL HOUR TO SECOND - 1.5::DOUBLE;
SELECT '0:00:01'::INTERVAL MINUTE TO SECOND - 1.5::DOUBLE;

SELECT '1-0'::INTERVAL YEAR * 1.5::DOUBLE;
SELECT '0-1'::INTERVAL MONTH * 1.5::DOUBLE;
SELECT '1 0:00:00'::INTERVAL DAY * 1.5::DOUBLE;
SELECT '1:00:00'::INTERVAL HOUR * 1.5::DOUBLE;
SELECT '0:01:00'::INTERVAL MINUTE * 1.5::DOUBLE;
SELECT '0:00:01'::INTERVAL SECOND * 1.5::DOUBLE;
SELECT '0-1'::INTERVAL YEAR TO MONTH * 1.5::DOUBLE;
SELECT '1:00:00'::INTERVAL DAY TO HOUR * 1.5::DOUBLE;
SELECT '0:01:00'::INTERVAL DAY TO MINUTE * 1.5::DOUBLE;
SELECT '0:00:01'::INTERVAL DAY TO SECOND * 1.5::DOUBLE;
SELECT '0:01:00'::INTERVAL HOUR TO MINUTE * 1.5::DOUBLE;
SELECT '0:00:01'::INTERVAL HOUR TO SECOND * 1.5::DOUBLE;
SELECT '0:00:01'::INTERVAL MINUTE TO SECOND * 1.5::DOUBLE;

SELECT '1-0'::INTERVAL YEAR / 1.5::DOUBLE;
SELECT '0-1'::INTERVAL MONTH / 1.5::DOUBLE;
SELECT '1 0:00:00'::INTERVAL DAY / 1.5::DOUBLE;
SELECT '1:00:00'::INTERVAL HOUR / 1.5::DOUBLE;
SELECT '0:01:00'::INTERVAL MINUTE / 1.5::DOUBLE;
SELECT '0:00:01'::INTERVAL SECOND / 1.5::DOUBLE;
SELECT '0-1'::INTERVAL YEAR TO MONTH / 1.5::DOUBLE;
SELECT '1:00:00'::INTERVAL DAY TO HOUR / 1.5::DOUBLE;
SELECT '0:01:00'::INTERVAL DAY TO MINUTE / 1.5::DOUBLE;
SELECT '0:00:01'::INTERVAL DAY TO SECOND / 1.5::DOUBLE;
SELECT '0:01:00'::INTERVAL HOUR TO MINUTE / 1.5::DOUBLE;
SELECT '0:00:01'::INTERVAL HOUR TO SECOND / 1.5::DOUBLE;
SELECT '0:00:01'::INTERVAL MINUTE TO SECOND / 1.5::DOUBLE;

//运算时左支加强转 (INTERVAL 和 INT)
SELECT '1-0'::INTERVAL YEAR + 1;
SELECT '0-1'::INTERVAL MONTH + 1;
SELECT '1 0:00:00'::INTERVAL DAY + 1;
SELECT '1:00:00'::INTERVAL HOUR + 1;
SELECT '0:01:00'::INTERVAL MINUTE + 1;
SELECT '0:00:01'::INTERVAL SECOND + 1;
SELECT '0-1'::INTERVAL YEAR TO MONTH + 1;
SELECT '1:00:00'::INTERVAL DAY TO HOUR + 1;
SELECT '0:01:00'::INTERVAL DAY TO MINUTE + 1;
SELECT '0:00:01'::INTERVAL DAY TO SECOND + 1;
SELECT '0:01:00'::INTERVAL HOUR TO MINUTE + 1;
SELECT '0:00:01'::INTERVAL HOUR TO SECOND + 1;
SELECT '0:00:01'::INTERVAL MINUTE TO SECOND + 1;

SELECT '1-0'::INTERVAL YEAR - 1;
SELECT '0-1'::INTERVAL MONTH - 1;
SELECT '1 0:00:00'::INTERVAL DAY - 1;
SELECT '1:00:00'::INTERVAL HOUR - 1;
SELECT '0:01:00'::INTERVAL MINUTE - 1;
SELECT '0:00:01'::INTERVAL SECOND - 1;
SELECT '0-1'::INTERVAL YEAR TO MONTH - 1;
SELECT '1:00:00'::INTERVAL DAY TO HOUR - 1;
SELECT '0:01:00'::INTERVAL DAY TO MINUTE - 1;
SELECT '0:00:01'::INTERVAL DAY TO SECOND - 1;
SELECT '0:01:00'::INTERVAL HOUR TO MINUTE - 1;
SELECT '0:00:01'::INTERVAL HOUR TO SECOND - 1;
SELECT '0:00:01'::INTERVAL MINUTE TO SECOND - 1;

SELECT '1-0'::INTERVAL YEAR * 1;
SELECT '0-1'::INTERVAL MONTH * 1;
SELECT '1 0:00:00'::INTERVAL DAY * 1;
SELECT '1:00:00'::INTERVAL HOUR * 1;
SELECT '0:01:00'::INTERVAL MINUTE * 1;
SELECT '0:00:01'::INTERVAL SECOND * 1;
SELECT '0-1'::INTERVAL YEAR TO MONTH * 1;
SELECT '1:00:00'::INTERVAL DAY TO HOUR * 1;
SELECT '0:01:00'::INTERVAL DAY TO MINUTE * 1;
SELECT '0:00:01'::INTERVAL DAY TO SECOND * 1;
SELECT '0:01:00'::INTERVAL HOUR TO MINUTE * 1;
SELECT '0:00:01'::INTERVAL HOUR TO SECOND * 1;
SELECT '0:00:01'::INTERVAL MINUTE TO SECOND * 1;

SELECT '1-0'::INTERVAL YEAR / 1;
SELECT '0-1'::INTERVAL MONTH / 1;
SELECT '1 0:00:00'::INTERVAL DAY / 1;
SELECT '1:00:00'::INTERVAL HOUR / 1;
SELECT '0:01:00'::INTERVAL MINUTE / 1;
SELECT '0:00:01'::INTERVAL SECOND / 1;
SELECT '0-1'::INTERVAL YEAR TO MONTH / 1;
SELECT '1:00:00'::INTERVAL DAY TO HOUR / 1;
SELECT '0:01:00'::INTERVAL DAY TO MINUTE / 1;
SELECT '0:00:01'::INTERVAL DAY TO SECOND / 1;
SELECT '0:01:00'::INTERVAL HOUR TO MINUTE / 1;
SELECT '0:00:01'::INTERVAL HOUR TO SECOND / 1;
SELECT '0:00:01'::INTERVAL MINUTE TO SECOND / 1;

//运算时右支加强转 (INTERVAL 和 INT)
SELECT '1-0' + 1::INT;
SELECT '0-1' + 1::INT;
SELECT '1 0:00:00' + 1::INT;
SELECT '1:00:00' + 1::INT;
SELECT '0:01:00' + 1::INT;
SELECT '0:00:01' + 1::INT;
SELECT '0-1' + 1::INT;
SELECT '1:00:00' + 1::INT;
SELECT '0:01:00' + 1::INT;
SELECT '0:00:01' + 1::INT;
SELECT '0:01:00' + 1::INT;
SELECT '0:00:01' + 1::INT;
SELECT '0:00:01' + 1::INT;

SELECT '1-0' - 1::INT;
SELECT '0-1' - 1::INT;
SELECT '1 0:00:00' - 1::INT;
SELECT '1:00:00' - 1::INT;
SELECT '0:01:00' - 1::INT;
SELECT '0:00:01' - 1::INT;
SELECT '0-1' - 1::INT;
SELECT '1:00:00' - 1::INT;
SELECT '0:01:00' - 1::INT;
SELECT '0:00:01' - 1::INT;
SELECT '0:01:00' - 1::INT;
SELECT '0:00:01' - 1::INT;
SELECT '0:00:01' - 1::INT;

SELECT '1-0' * 1::INT;
SELECT '0-1' * 1::INT;
SELECT '1 0:00:00' * 1::INT;
SELECT '1:00:00' * 1::INT;
SELECT '0:01:00' * 1::INT;
SELECT '0:00:01' * 1::INT;
SELECT '0-1' * 1::INT;
SELECT '1:00:00' * 1::INT;
SELECT '0:01:00' * 1::INT;
SELECT '0:00:01' * 1::INT;
SELECT '0:01:00' * 1::INT;
SELECT '0:00:01' * 1::INT;
SELECT '0:00:01' * 1::INT;

SELECT '1-0' / 1::INT;
SELECT '0-1' / 1::INT;
SELECT '1 0:00:00' / 1::INT;
SELECT '1:00:00' / 1::INT;
SELECT '0:01:00' / 1::INT;
SELECT '0:00:01' / 1::INT;
SELECT '0-1' / 1::INT;
SELECT '1:00:00' / 1::INT;
SELECT '0:01:00' / 1::INT;
SELECT '0:00:01' / 1::INT;
SELECT '0:01:00' / 1::INT;
SELECT '0:00:01' / 1::INT;
SELECT '0:00:01' / 1::INT;

//运算时左支加强转 (INTERVAL 和 DOUBLE)
SELECT '1-0'::INTERVAL YEAR + 1.5;
SELECT '0-1'::INTERVAL MONTH + 1.5;
SELECT '1 0:00:00'::INTERVAL DAY + 1.5;
SELECT '1:00:00'::INTERVAL HOUR + 1.5;
SELECT '0:01:00'::INTERVAL MINUTE + 1.5;
SELECT '0:00:01'::INTERVAL SECOND + 1.5;
SELECT '0-1'::INTERVAL YEAR TO MONTH + 1.5;
SELECT '1:00:00'::INTERVAL DAY TO HOUR + 1.5;
SELECT '0:01:00'::INTERVAL DAY TO MINUTE + 1.5;
SELECT '0:00:01'::INTERVAL DAY TO SECOND + 1.5;
SELECT '0:01:00'::INTERVAL HOUR TO MINUTE + 1.5;
SELECT '0:00:01'::INTERVAL HOUR TO SECOND + 1.5;
SELECT '0:00:01'::INTERVAL MINUTE TO SECOND + 1.5;

SELECT '1-0'::INTERVAL YEAR - 1.5;
SELECT '0-1'::INTERVAL MONTH - 1.5;
SELECT '1 0:00:00'::INTERVAL DAY - 1.5;
SELECT '1:00:00'::INTERVAL HOUR - 1.5;
SELECT '0:01:00'::INTERVAL MINUTE - 1.5;
SELECT '0:00:01'::INTERVAL SECOND - 1.5;
SELECT '0-1'::INTERVAL YEAR TO MONTH - 1.5;
SELECT '1:00:00'::INTERVAL DAY TO HOUR - 1.5;
SELECT '0:01:00'::INTERVAL DAY TO MINUTE - 1.5;
SELECT '0:00:01'::INTERVAL DAY TO SECOND - 1.5;
SELECT '0:01:00'::INTERVAL HOUR TO MINUTE - 1.5;
SELECT '0:00:01'::INTERVAL HOUR TO SECOND - 1.5;
SELECT '0:00:01'::INTERVAL MINUTE TO SECOND - 1.5;

SELECT '1-0'::INTERVAL YEAR * 1.5;
SELECT '0-1'::INTERVAL MONTH * 1.5;
SELECT '1 0:00:00'::INTERVAL DAY * 1.5;
SELECT '1:00:00'::INTERVAL HOUR * 1.5;
SELECT '0:01:00'::INTERVAL MINUTE * 1.5;
SELECT '0:00:01'::INTERVAL SECOND * 1.5;
SELECT '0-1'::INTERVAL YEAR TO MONTH * 1.5;
SELECT '1:00:00'::INTERVAL DAY TO HOUR * 1.5;
SELECT '0:01:00'::INTERVAL DAY TO MINUTE * 1.5;
SELECT '0:00:01'::INTERVAL DAY TO SECOND * 1.5;
SELECT '0:01:00'::INTERVAL HOUR TO MINUTE * 1.5;
SELECT '0:00:01'::INTERVAL HOUR TO SECOND * 1.5;
SELECT '0:00:01'::INTERVAL MINUTE TO SECOND * 1.5;

SELECT '1-0'::INTERVAL YEAR / 1.5;
SELECT '0-1'::INTERVAL MONTH / 1.5;
SELECT '1 0:00:00'::INTERVAL DAY / 1.5;
SELECT '1:00:00'::INTERVAL HOUR / 1.5;
SELECT '0:01:00'::INTERVAL MINUTE / 1.5;
SELECT '0:00:01'::INTERVAL SECOND / 1.5;
SELECT '0-1'::INTERVAL YEAR TO MONTH / 1.5;
SELECT '1:00:00'::INTERVAL DAY TO HOUR / 1.5;
SELECT '0:01:00'::INTERVAL DAY TO MINUTE / 1.5;
SELECT '0:00:01'::INTERVAL DAY TO SECOND / 1.5;
SELECT '0:01:00'::INTERVAL HOUR TO MINUTE / 1.5;
SELECT '0:00:01'::INTERVAL HOUR TO SECOND / 1.5;
SELECT '0:00:01'::INTERVAL MINUTE TO SECOND / 1.5;

//运算时右支加强转 (INTERVAL 和 DOUBLE)
SELECT '1-0' + 1.5::DOUBLE;
SELECT '0-1' + 1.5::DOUBLE;
SELECT '1 0:00:00' + 1.5::DOUBLE;
SELECT '1:00:00' + 1.5::DOUBLE;
SELECT '0:01:00' + 1.5::DOUBLE;
SELECT '0:00:01' + 1.5::DOUBLE;
SELECT '0-1' + 1.5::DOUBLE;
SELECT '1:00:00' + 1.5::DOUBLE;
SELECT '0:01:00' + 1.5::DOUBLE;
SELECT '0:00:01' + 1.5::DOUBLE;
SELECT '0:01:00' + 1.5::DOUBLE;
SELECT '0:00:01' + 1.5::DOUBLE;
SELECT '0:00:01' + 1.5::DOUBLE;

SELECT '1-0' - 1.5::DOUBLE;
SELECT '0-1' - 1.5::DOUBLE;
SELECT '1 0:00:00' - 1.5::DOUBLE;
SELECT '1:00:00' - 1.5::DOUBLE;
SELECT '0:01:00' - 1.5::DOUBLE;
SELECT '0:00:01' - 1.5::DOUBLE;
SELECT '0-1' - 1.5::DOUBLE;
SELECT '1:00:00' - 1.5::DOUBLE;
SELECT '0:01:00' - 1.5::DOUBLE;
SELECT '0:00:01' - 1.5::DOUBLE;
SELECT '0:01:00' - 1.5::DOUBLE;
SELECT '0:00:01' - 1.5::DOUBLE;
SELECT '0:00:01' - 1.5::DOUBLE;

SELECT '1-0' * 1.5::DOUBLE;
SELECT '0-1' * 1.5::DOUBLE;
SELECT '1 0:00:00' * 1.5::DOUBLE;
SELECT '1:00:00' * 1.5::DOUBLE;
SELECT '0:01:00' * 1.5::DOUBLE;
SELECT '0:00:01' * 1.5::DOUBLE;
SELECT '0-1' * 1.5::DOUBLE;
SELECT '1:00:00' * 1.5::DOUBLE;
SELECT '0:01:00' * 1.5::DOUBLE;
SELECT '0:00:01' * 1.5::DOUBLE;
SELECT '0:01:00' * 1.5::DOUBLE;
SELECT '0:00:01' * 1.5::DOUBLE;
SELECT '0:00:01' * 1.5::DOUBLE;

SELECT '1-0' / 1.5::DOUBLE;
SELECT '0-1' / 1.5::DOUBLE;
SELECT '1 0:00:00' / 1.5::DOUBLE;
SELECT '1:00:00' / 1.5::DOUBLE;
SELECT '0:01:00' / 1.5::DOUBLE;
SELECT '0:00:01' / 1.5::DOUBLE;
SELECT '0-1' / 1.5::DOUBLE;
SELECT '1:00:00' / 1.5::DOUBLE;
SELECT '0:01:00' / 1.5::DOUBLE;
SELECT '0:00:01' / 1.5::DOUBLE;
SELECT '0:01:00' / 1.5::DOUBLE;
SELECT '0:00:01' / 1.5::DOUBLE;
SELECT '0:00:01' / 1.5::DOUBLE;

//运算时都不加强转 (INTERVAL 和 INT)
SELECT '1-0' + 1;
SELECT '0-1' + 1;
SELECT '1 0:00:00' + 1;
SELECT '1:00:00' + 1;
SELECT '0:01:00' + 1;
SELECT '0:00:01' + 1;
SELECT '0-1' + 1;
SELECT '1:00:00' + 1;
SELECT '0:01:00' + 1;
SELECT '0:00:01' + 1;
SELECT '0:01:00' + 1;
SELECT '0:00:01' + 1;
SELECT '0:00:01' + 1;

SELECT '1-0' - 1;
SELECT '0-1' - 1;
SELECT '1 0:00:00' - 1;
SELECT '1:00:00' - 1;
SELECT '0:01:00' - 1;
SELECT '0:00:01' - 1;
SELECT '0-1' - 1;
SELECT '1:00:00' - 1;
SELECT '0:01:00' - 1;
SELECT '0:00:01' - 1;
SELECT '0:01:00' - 1;
SELECT '0:00:01' - 1;
SELECT '0:00:01' - 1;

SELECT '1-0' * 1;
SELECT '0-1' * 1;
SELECT '1 0:00:00' * 1;
SELECT '1:00:00' * 1;
SELECT '0:01:00' * 1;
SELECT '0:00:01' * 1;
SELECT '0-1' * 1;
SELECT '1:00:00' * 1;
SELECT '0:01:00' * 1;
SELECT '0:00:01' * 1;
SELECT '0:01:00' * 1;
SELECT '0:00:01' * 1;
SELECT '0:00:01' * 1;

SELECT '1-0' / 1;
SELECT '0-1' / 1;
SELECT '1 0:00:00' / 1;
SELECT '1:00:00' / 1;
SELECT '0:01:00' / 1;
SELECT '0:00:01' / 1;
SELECT '0-1' / 1;
SELECT '1:00:00' / 1;
SELECT '0:01:00' / 1;
SELECT '0:00:01' / 1;
SELECT '0:01:00' / 1;
SELECT '0:00:01' / 1;
SELECT '0:00:01' / 1;

//运算时都不加强转 (INTERVAL 和 DOUBLE)
SELECT '1-0' + 1.5;
SELECT '0-1' + 1.5;
SELECT '1 0:00:00' + 1.5;
SELECT '1:00:00' + 1.5;
SELECT '0:01:00' + 1.5;
SELECT '0:00:01' + 1.5;
SELECT '0-1' + 1.5;
SELECT '1:00:00' + 1.5;
SELECT '0:01:00' + 1.5;
SELECT '0:00:01' + 1.5;
SELECT '0:01:00' + 1.5;
SELECT '0:00:01' + 1.5;
SELECT '0:00:01' + 1.5;

SELECT '1-0' - 1.5;
SELECT '0-1' - 1.5;
SELECT '1 0:00:00' - 1.5;
SELECT '1:00:00' - 1.5;
SELECT '0:01:00' - 1.5;
SELECT '0:00:01' - 1.5;
SELECT '0-1' - 1.5;
SELECT '1:00:00' - 1.5;
SELECT '0:01:00' - 1.5;
SELECT '0:00:01' - 1.5;
SELECT '0:01:00' - 1.5;
SELECT '0:00:01' - 1.5;
SELECT '0:00:01' - 1.5;

SELECT '1-0' * 1.5;
SELECT '0-1' * 1.5;
SELECT '1 0:00:00' * 1.5;
SELECT '1:00:00' * 1.5;
SELECT '0:01:00' * 1.5;
SELECT '0:00:01' * 1.5;
SELECT '0-1' * 1.5;
SELECT '1:00:00' * 1.5;
SELECT '0:01:00' * 1.5;
SELECT '0:00:01' * 1.5;
SELECT '0:01:00' * 1.5;
SELECT '0:00:01' * 1.5;
SELECT '0:00:01' * 1.5;

SELECT '1-0' / 1.5;
SELECT '0-1' / 1.5;
SELECT '1 0:00:00' / 1.5;
SELECT '1:00:00' / 1.5;
SELECT '0:01:00' / 1.5;
SELECT '0:00:01' / 1.5;
SELECT '0-1' / 1.5;
SELECT '1:00:00' / 1.5;
SELECT '0:01:00' / 1.5;
SELECT '0:00:01' / 1.5;
SELECT '0:01:00' / 1.5;
SELECT '0:00:01' / 1.5;
SELECT '0:00:01' / 1.5;