!4 XG-TYPE-INTERVAL-001 INTERVAL 类型相互运算 : 块语句声明部分赋值

// INTERVAL YEAR 的转换
DECLARE
v_y INTERVAL YEAR := '9';
y_m VARCHAR;
BEGIN
SELECT v_y::INTERVAL MONTH INTO y_m;
DBMS_OUTPUT.PUT_LINE('y_m : ' || y_m);
END;
/

DECLARE
v_y INTERVAL YEAR := '9';
y_d VARCHAR;
BEGIN
SELECT v_y::INTERVAL DAY INTO y_d;
DBMS_OUTPUT.PUT_LINE('y_d : ' || y_d);
END;
/

DECLARE
v_y INTERVAL YEAR := '9';
y_h VARCHAR;
BEGIN
SELECT v_y::INTERVAL HOUR INTO y_h;
DBMS_OUTPUT.PUT_LINE('y_h : ' || y_h);
END;
/

DECLARE
v_y INTERVAL YEAR := '9';
y_mi VARCHAR;
BEGIN
SELECT v_y::INTERVAL MINUTE INTO y_mi;
DBMS_OUTPUT.PUT_LINE('y_mi : ' || y_mi);
END;
/

DECLARE
v_y INTERVAL YEAR := '9';
y_s VARCHAR;
BEGIN
SELECT v_y::INTERVAL SECOND INTO y_s;
DBMS_OUTPUT.PUT_LINE('y_s : ' || y_s);
END;
/

DECLARE
v_y INTERVAL YEAR := '9';
y_y2m VARCHAR;
BEGIN
SELECT v_y::INTERVAL YEAR TO MONTH INTO y_y2m;
DBMS_OUTPUT.PUT_LINE('y_y2m : ' || y_y2m);
END;
/

DECLARE
v_y INTERVAL YEAR := '9';
y_d2h VARCHAR;
BEGIN
SELECT v_y::INTERVAL DAY TO HOUR INTO y_d2h;
DBMS_OUTPUT.PUT_LINE('y_d2h : ' || y_d2h);
END;
/

DECLARE
v_y INTERVAL YEAR := '9';
y_d2m VARCHAR;
BEGIN
SELECT v_y::INTERVAL DAY TO MINUTE INTO y_d2m;
DBMS_OUTPUT.PUT_LINE('y_d2m : ' || y_d2m);
END;
/

DECLARE
v_y INTERVAL YEAR := '9';
y_d2s VARCHAR;
BEGIN
SELECT v_y::INTERVAL DAY TO SECOND INTO y_d2s;
DBMS_OUTPUT.PUT_LINE('y_d2s : ' || y_d2s);
END;
/

DECLARE
v_y INTERVAL YEAR := '9';
y_h2m VARCHAR;
BEGIN
SELECT v_y::INTERVAL HOUR TO MINUTE INTO y_h2m;
DBMS_OUTPUT.PUT_LINE('y_h2m : ' || y_h2m);
END;
/

DECLARE
v_y INTERVAL YEAR := '9';
y_h2s VARCHAR;
BEGIN
SELECT v_y::INTERVAL HOUR TO SECOND INTO y_h2s;
DBMS_OUTPUT.PUT_LINE('y_h2s : ' || y_h2s);
END;
/

DECLARE
v_y INTERVAL YEAR := '9';
y_m2s VARCHAR;
BEGIN
SELECT v_y::INTERVAL MINUTE TO SECOND INTO y_m2s;
DBMS_OUTPUT.PUT_LINE('y_m2s : ' || y_m2s);
END;
/

//INTERVAL MONTH 的转换
DECLARE
v_m INTERVAL MONTH := '9';
m_y VARCHAR;
BEGIN
SELECT v_m::INTERVAL YEAR INTO m_y;
DBMS_OUTPUT.PUT_LINE('m_y : ' || m_y);
END;
/

DECLARE
v_m INTERVAL MONTH := '9';
m_d VARCHAR;
BEGIN
SELECT v_m::INTERVAL DAY INTO m_d;
DBMS_OUTPUT.PUT_LINE('m_d : ' || m_d);
END;
/

DECLARE
v_m INTERVAL MONTH := '9';
m_h VARCHAR;
BEGIN
SELECT v_m::INTERVAL HOUR INTO m_h;
DBMS_OUTPUT.PUT_LINE('m_h : ' || m_h);
END;
/

DECLARE
v_m INTERVAL MONTH := '9';
m_mi VARCHAR;
BEGIN
SELECT v_m::INTERVAL MINUTE INTO m_mi;
DBMS_OUTPUT.PUT_LINE('m_mi : ' || m_mi);
END;
/

DECLARE
v_m INTERVAL MONTH := '9';
m_s VARCHAR;
BEGIN
SELECT v_m::INTERVAL SECOND INTO m_s;
DBMS_OUTPUT.PUT_LINE('m_s : ' || m_s);
END;
/

DECLARE
v_m INTERVAL MONTH := '9';
m_y2m VARCHAR;
BEGIN
SELECT v_m::INTERVAL YEAR TO MONTH INTO m_y2m;
DBMS_OUTPUT.PUT_LINE('m_y2m : ' || m_y2m);
END;
/

DECLARE
v_m INTERVAL MONTH := '9';
m_d2h VARCHAR;
BEGIN
SELECT v_m::INTERVAL DAY TO HOUR INTO m_d2h;
DBMS_OUTPUT.PUT_LINE('m_d2h : ' || m_d2h);
END;
/

DECLARE
v_m INTERVAL MONTH := '9';
m_d2m VARCHAR;
BEGIN
SELECT v_m::INTERVAL DAY TO MINUTE INTO m_d2m;
DBMS_OUTPUT.PUT_LINE('m_d2m : ' || m_d2m);
END;
/

DECLARE
v_m INTERVAL MONTH := '9';
m_d2s VARCHAR;
BEGIN
SELECT v_m::INTERVAL DAY TO SECOND INTO m_d2s;
DBMS_OUTPUT.PUT_LINE('m_d2s : ' || m_d2s);
END;
/

DECLARE
v_m INTERVAL MONTH := '9';
m_h2m VARCHAR;
BEGIN
SELECT v_m::INTERVAL HOUR TO MINUTE INTO m_h2m;
DBMS_OUTPUT.PUT_LINE('m_h2m : ' || m_h2m);
END;
/

DECLARE
v_m INTERVAL MONTH := '9';
m_h2s VARCHAR;
BEGIN
SELECT v_m::INTERVAL HOUR TO SECOND INTO m_h2s;
DBMS_OUTPUT.PUT_LINE('m_h2s : ' || m_h2s);
END;
/

DECLARE
v_m INTERVAL MONTH := '9';
m_m2s VARCHAR;
BEGIN
SELECT v_m::INTERVAL MINUTE TO SECOND INTO m_m2s;
DBMS_OUTPUT.PUT_LINE('m_m2s : ' || m_m2s);
END;
/

//INTERVAL DAY 的转换
DECLARE
v_d INTERVAL DAY := '9';
d_y VARCHAR;
BEGIN
SELECT v_d::INTERVAL YEAR INTO d_y;
DBMS_OUTPUT.PUT_LINE('d_y : ' || d_y);
END;
/

DECLARE
v_d INTERVAL DAY := '9';
d_m VARCHAR;
BEGIN
SELECT v_d::INTERVAL MONTH INTO d_m;
DBMS_OUTPUT.PUT_LINE('d_m : ' || d_m);
END;
/

DECLARE
v_d INTERVAL DAY := '9';
d_h VARCHAR;
BEGIN
SELECT v_d::INTERVAL HOUR INTO d_h;
DBMS_OUTPUT.PUT_LINE('d_h : ' || d_h);
END;
/

DECLARE
v_d INTERVAL DAY := '9';
d_mi VARCHAR;
BEGIN
SELECT v_d::INTERVAL MINUTE INTO d_mi;
DBMS_OUTPUT.PUT_LINE('d_mi : ' || d_mi);
END;
/

DECLARE
v_d INTERVAL DAY := '9';
d_s VARCHAR;
BEGIN
SELECT v_d::INTERVAL SECOND INTO d_s;
DBMS_OUTPUT.PUT_LINE('d_s : ' || d_s);
END;
/

DECLARE
v_d INTERVAL DAY := '9';
d_y2m VARCHAR;
BEGIN
SELECT v_d::INTERVAL YEAR TO MONTH INTO d_y2m;
DBMS_OUTPUT.PUT_LINE('d_y2m : ' || d_y2m);
END;
/

DECLARE
v_d INTERVAL DAY := '9';
d_d2h VARCHAR;
BEGIN
SELECT v_d::INTERVAL DAY TO HOUR INTO d_d2h;
DBMS_OUTPUT.PUT_LINE('d_d2h : ' || d_d2h);
END;
/

DECLARE
v_d INTERVAL DAY := '9';
d_d2m VARCHAR;
BEGIN
SELECT v_d::INTERVAL DAY TO MINUTE INTO d_d2m;
DBMS_OUTPUT.PUT_LINE('d_d2m : ' || d_d2m);
END;
/

DECLARE
v_d INTERVAL DAY := '9';
d_d2s VARCHAR;
BEGIN
SELECT v_d::INTERVAL DAY TO SECOND INTO d_d2s;
DBMS_OUTPUT.PUT_LINE('d_d2s : ' || d_d2s);
END;
/

DECLARE
v_d INTERVAL DAY := '9';
d_h2m VARCHAR;
BEGIN
SELECT v_d::INTERVAL HOUR TO MINUTE INTO d_h2m;
DBMS_OUTPUT.PUT_LINE('d_h2m : ' || d_h2m);
END;
/

DECLARE
v_d INTERVAL DAY := '9';
d_h2s VARCHAR;
BEGIN
SELECT v_d::INTERVAL HOUR TO SECOND INTO d_h2s;
DBMS_OUTPUT.PUT_LINE('d_h2s : ' || d_h2s);
END;
/

DECLARE
v_d INTERVAL DAY := '9';
d_m2s VARCHAR;
BEGIN
SELECT v_d::INTERVAL MINUTE TO SECOND INTO d_m2s;
DBMS_OUTPUT.PUT_LINE('d_m2s : ' || d_m2s);
END;
/

//INTERVAL HOUR 的转换
DECLARE
v_h INTERVAL HOUR := '9';
h_y VARCHAR;
BEGIN
SELECT v_h::INTERVAL YEAR INTO h_y;
DBMS_OUTPUT.PUT_LINE('h_y : ' || h_y);
END;
/

DECLARE
v_h INTERVAL HOUR := '9';
h_m VARCHAR;
BEGIN
SELECT v_h::INTERVAL MONTH INTO h_m;
DBMS_OUTPUT.PUT_LINE('h_m : ' || h_m);
END;
/

DECLARE
v_h INTERVAL HOUR := '9';
h_d VARCHAR;
BEGIN
SELECT v_h::INTERVAL DAY INTO h_d;
DBMS_OUTPUT.PUT_LINE('h_d : ' || h_d);
END;
/

DECLARE
v_h INTERVAL HOUR := '9';
h_mi VARCHAR;
BEGIN
SELECT v_h::INTERVAL MINUTE INTO h_mi;
DBMS_OUTPUT.PUT_LINE('h_mi : ' || h_mi);
END;
/

DECLARE
v_h INTERVAL HOUR := '9';
h_s VARCHAR;
BEGIN
SELECT v_h::INTERVAL SECOND INTO h_s;
DBMS_OUTPUT.PUT_LINE('h_s : ' || h_s);
END;
/

DECLARE
v_h INTERVAL HOUR := '9';
h_y2m VARCHAR;
BEGIN
SELECT v_h::INTERVAL YEAR TO MONTH INTO h_y2m;
DBMS_OUTPUT.PUT_LINE('h_y2m : ' || h_y2m);
END;
/

DECLARE
v_h INTERVAL HOUR := '9';
h_d2h VARCHAR;
BEGIN
SELECT v_h::INTERVAL DAY TO HOUR INTO h_d2h;
DBMS_OUTPUT.PUT_LINE('h_d2h : ' || h_d2h);
END;
/

DECLARE
v_h INTERVAL HOUR := '9';
h_d2m VARCHAR;
BEGIN
SELECT v_h::INTERVAL DAY TO MINUTE INTO h_d2m;
DBMS_OUTPUT.PUT_LINE('h_d2m : ' || h_d2m);
END;
/

DECLARE
v_h INTERVAL HOUR := '9';
h_d2s VARCHAR;
BEGIN
SELECT v_h::INTERVAL DAY TO SECOND INTO h_d2s;
DBMS_OUTPUT.PUT_LINE('h_d2s : ' || h_d2s);
END;
/

DECLARE
v_h INTERVAL HOUR := '9';
h_h2m VARCHAR;
BEGIN
SELECT v_h::INTERVAL HOUR TO MINUTE INTO h_h2m;
DBMS_OUTPUT.PUT_LINE('h_h2m : ' || h_h2m);
END;
/

DECLARE
v_h INTERVAL HOUR := '9';
h_h2s VARCHAR;
BEGIN
SELECT v_h::INTERVAL HOUR TO SECOND INTO h_h2s;
DBMS_OUTPUT.PUT_LINE('h_h2s : ' || h_h2s);
END;
/

DECLARE
v_h INTERVAL HOUR := '9';
h_m2s VARCHAR;
BEGIN
SELECT v_h::INTERVAL MINUTE TO SECOND INTO h_m2s;
DBMS_OUTPUT.PUT_LINE('h_m2s : ' || h_m2s);
END;
/

//INTERVAL MINUTE 的转换
DECLARE
v_mi INTERVAL MINUTE := '9';
mi_y VARCHAR;
BEGIN
SELECT v_mi::INTERVAL YEAR INTO mi_y;
DBMS_OUTPUT.PUT_LINE('mi_y : ' || mi_y);
END;
/

DECLARE
v_mi INTERVAL MINUTE := '9';
mi_m VARCHAR;
BEGIN
SELECT v_mi::INTERVAL MONTH INTO mi_m;
DBMS_OUTPUT.PUT_LINE('mi_m : ' || mi_m);
END;
/

DECLARE
v_mi INTERVAL MINUTE := '9';
mi_d VARCHAR;
BEGIN
SELECT v_mi::INTERVAL DAY INTO mi_d;
DBMS_OUTPUT.PUT_LINE('mi_d : ' || mi_d);
END;
/

DECLARE
v_mi INTERVAL MINUTE := '9';
mi_h VARCHAR;
BEGIN
SELECT v_mi::INTERVAL HOUR INTO mi_h;
DBMS_OUTPUT.PUT_LINE('mi_h : ' || mi_h);
END;
/

DECLARE
v_mi INTERVAL MINUTE := '9';
mi_s VARCHAR;
BEGIN
SELECT v_mi::INTERVAL SECOND INTO mi_s;
DBMS_OUTPUT.PUT_LINE('mi_s : ' || mi_s);
END;
/

DECLARE
v_mi INTERVAL MINUTE := '9';
mi_y2m VARCHAR;
BEGIN
SELECT v_mi::INTERVAL YEAR TO MONTH INTO mi_y2m;
DBMS_OUTPUT.PUT_LINE('mi_y2m : ' || mi_y2m);
END;
/

DECLARE
v_mi INTERVAL MINUTE := '9';
mi_d2h VARCHAR;
BEGIN
SELECT v_mi::INTERVAL DAY TO HOUR INTO mi_d2h;
DBMS_OUTPUT.PUT_LINE('mi_d2h : ' || mi_d2h);
END;
/

DECLARE
v_mi INTERVAL MINUTE := '9';
mi_d2m VARCHAR;
BEGIN
SELECT v_mi::INTERVAL DAY TO MINUTE INTO mi_d2m;
DBMS_OUTPUT.PUT_LINE('mi_d2m : ' || mi_d2m);
END;
/

DECLARE
v_mi INTERVAL MINUTE := '9';
mi_d2s VARCHAR;
BEGIN
SELECT v_mi::INTERVAL DAY TO SECOND INTO mi_d2s;
DBMS_OUTPUT.PUT_LINE('mi_d2s : ' || mi_d2s);
END;
/

DECLARE
v_mi INTERVAL MINUTE := '9';
mi_h2m VARCHAR;
BEGIN
SELECT v_mi::INTERVAL HOUR TO MINUTE INTO mi_h2m;
DBMS_OUTPUT.PUT_LINE('mi_h2m : ' || mi_h2m);
END;
/

DECLARE
v_mi INTERVAL MINUTE := '9';
mi_h2s VARCHAR;
BEGIN
SELECT v_mi::INTERVAL HOUR TO SECOND INTO mi_h2s;
DBMS_OUTPUT.PUT_LINE('mi_h2s : ' || mi_h2s);
END;
/

DECLARE
v_mi INTERVAL MINUTE := '9';
mi_m2s VARCHAR;
BEGIN
SELECT v_mi::INTERVAL MINUTE TO SECOND INTO mi_m2s;
DBMS_OUTPUT.PUT_LINE('mi_m2s : ' || mi_m2s);
END;
/

//INTERVAL SECOND 的转换
DECLARE
v_s INTERVAL SECOND := '9';
s_y VARCHAR;
BEGIN
SELECT v_s::INTERVAL YEAR INTO s_y;
DBMS_OUTPUT.PUT_LINE('s_y : ' || s_y);
END;
/

DECLARE
v_s INTERVAL SECOND := '9';
s_m VARCHAR;
BEGIN
SELECT v_s::INTERVAL MONTH INTO s_m;
DBMS_OUTPUT.PUT_LINE('s_m : ' || s_m);
END;
/

DECLARE
v_s INTERVAL SECOND := '9';
s_d VARCHAR;
BEGIN
SELECT v_s::INTERVAL DAY INTO s_d;
DBMS_OUTPUT.PUT_LINE('s_d : ' || s_d);
END;
/

DECLARE
v_s INTERVAL SECOND := '9';
s_h VARCHAR;
BEGIN
SELECT v_s::INTERVAL HOUR INTO s_h;
DBMS_OUTPUT.PUT_LINE('s_h : ' || s_h);
END;
/

DECLARE
v_s INTERVAL SECOND := '9';
s_mi VARCHAR;
BEGIN
SELECT v_s::INTERVAL MINUTE INTO s_mi;
DBMS_OUTPUT.PUT_LINE('s_mi : ' || s_mi);
END;
/

DECLARE
v_s INTERVAL SECOND := '9';
s_y2m VARCHAR;
BEGIN
SELECT v_s::INTERVAL YEAR TO MONTH INTO s_y2m;
DBMS_OUTPUT.PUT_LINE('s_y2m : ' || s_y2m);
END;
/

DECLARE
v_s INTERVAL SECOND := '9';
s_d2h VARCHAR;
BEGIN
SELECT v_s::INTERVAL DAY TO HOUR INTO s_d2h;
DBMS_OUTPUT.PUT_LINE('s_d2h : ' || s_d2h);
END;
/

DECLARE
v_s INTERVAL SECOND := '9';
s_d2m VARCHAR;
BEGIN
SELECT v_s::INTERVAL DAY TO MINUTE INTO s_d2m;
DBMS_OUTPUT.PUT_LINE('s_d2m : ' || s_d2m);
END;
/

DECLARE
v_s INTERVAL SECOND := '9';
s_d2s VARCHAR;
BEGIN
SELECT v_s::INTERVAL DAY TO SECOND INTO s_d2s;
DBMS_OUTPUT.PUT_LINE('s_d2s : ' || s_d2s);
END;
/

DECLARE
v_s INTERVAL SECOND := '9';
s_h2m VARCHAR;
BEGIN
SELECT v_s::INTERVAL HOUR TO MINUTE INTO s_h2m;
DBMS_OUTPUT.PUT_LINE('s_h2m : ' || s_h2m);
END;
/

DECLARE
v_s INTERVAL SECOND := '9';
s_h2s VARCHAR;
BEGIN
SELECT v_s::INTERVAL HOUR TO SECOND INTO s_h2s;
DBMS_OUTPUT.PUT_LINE('s_h2s : ' || s_h2s);
END;
/

DECLARE
v_s INTERVAL SECOND := '9';
s_m2s VARCHAR;
BEGIN
SELECT v_s::INTERVAL MINUTE TO SECOND INTO s_m2s;
DBMS_OUTPUT.PUT_LINE('s_m2s : ' || s_m2s);
END;
/

//INTERVAL YEAR TO MONTH 的转换
DECLARE
v_y2m INTERVAL YEAR TO MONTH := '9';
y2m_y VARCHAR;
BEGIN
SELECT v_y2m::INTERVAL YEAR INTO y2m_y;
DBMS_OUTPUT.PUT_LINE('y2m_y : ' || y2m_y);
END;
/

DECLARE
v_y2m INTERVAL YEAR TO MONTH := '9';
y2m_m VARCHAR;
BEGIN
SELECT v_y2m::INTERVAL MONTH INTO y2m_m;
DBMS_OUTPUT.PUT_LINE('y2m_m : ' || y2m_m);
END;
/

DECLARE
v_y2m INTERVAL YEAR TO MONTH := '9';
y2m_d VARCHAR;
BEGIN
SELECT v_y2m::INTERVAL DAY INTO y2m_d;
DBMS_OUTPUT.PUT_LINE('y2m_d : ' || y2m_d);
END;
/

DECLARE
v_y2m INTERVAL YEAR TO MONTH := '9';
y2m_h VARCHAR;
BEGIN
SELECT v_y2m::INTERVAL HOUR INTO y2m_h;
DBMS_OUTPUT.PUT_LINE('y2m_h : ' || y2m_h);
END;
/

DECLARE
v_y2m INTERVAL YEAR TO MONTH := '9';
y2m_mi VARCHAR;
BEGIN
SELECT v_y2m::INTERVAL MINUTE INTO y2m_mi;
DBMS_OUTPUT.PUT_LINE('y2m_mi : ' || y2m_mi);
END;
/

DECLARE
v_y2m INTERVAL YEAR TO MONTH := '9';
y2m_s VARCHAR;
BEGIN
SELECT v_y2m::INTERVAL SECOND INTO y2m_s;
DBMS_OUTPUT.PUT_LINE('y2m_s : ' || y2m_s);
END;
/

DECLARE
v_y2m INTERVAL YEAR TO MONTH := '9';
y2m_d2h VARCHAR;
BEGIN
SELECT v_y2m::INTERVAL DAY TO HOUR INTO y2m_d2h;
DBMS_OUTPUT.PUT_LINE('y2m_d2h : ' || y2m_d2h);
END;
/

DECLARE
v_y2m INTERVAL YEAR TO MONTH := '9';
y2m_d2m VARCHAR;
BEGIN
SELECT v_y2m::INTERVAL DAY TO MINUTE INTO y2m_d2m;
DBMS_OUTPUT.PUT_LINE('y2m_d2m : ' || y2m_d2m);
END;
/

DECLARE
v_y2m INTERVAL YEAR TO MONTH := '9';
y2m_d2s VARCHAR;
BEGIN
SELECT v_y2m::INTERVAL DAY TO SECOND INTO y2m_d2s;
DBMS_OUTPUT.PUT_LINE('y2m_d2s : ' || y2m_d2s);
END;
/

DECLARE
v_y2m INTERVAL YEAR TO MONTH := '9';
y2m_h2m VARCHAR;
BEGIN
SELECT v_y2m::INTERVAL HOUR TO MINUTE INTO y2m_h2m;
DBMS_OUTPUT.PUT_LINE('y2m_h2m : ' || y2m_h2m);
END;
/

DECLARE
v_y2m INTERVAL YEAR TO MONTH := '9';
y2m_h2s VARCHAR;
BEGIN
SELECT v_y2m::INTERVAL HOUR TO SECOND INTO y2m_h2s;
DBMS_OUTPUT.PUT_LINE('y2m_h2s : ' || y2m_h2s);
END;
/

DECLARE
v_y2m INTERVAL YEAR TO MONTH := '9';
y2m_m2s VARCHAR;
BEGIN
SELECT v_y2m::INTERVAL MINUTE TO SECOND INTO y2m_m2s;
DBMS_OUTPUT.PUT_LINE('y2m_m2s : ' || y2m_m2s);
END;
/

//INTERVAL DAY TO HOUR 的转换
DECLARE
v_d2h INTERVAL DAY TO HOUR := '9';
d2h_y VARCHAR;
BEGIN
SELECT v_d2h::INTERVAL YEAR INTO d2h_y;
DBMS_OUTPUT.PUT_LINE('d2h_y : ' || d2h_y);
END;
/

DECLARE
v_d2h INTERVAL DAY TO HOUR := '9';
d2h_m VARCHAR;
BEGIN
SELECT v_d2h::INTERVAL MONTH INTO d2h_m;
DBMS_OUTPUT.PUT_LINE('d2h_m : ' || d2h_m);
END;
/

DECLARE
v_d2h INTERVAL DAY TO HOUR := '9';
d2h_d VARCHAR;
BEGIN
SELECT v_d2h::INTERVAL DAY INTO d2h_d;
DBMS_OUTPUT.PUT_LINE('d2h_d : ' || d2h_d);
END;
/

DECLARE
v_d2h INTERVAL DAY TO HOUR := '9';
d2h_h VARCHAR;
BEGIN
SELECT v_d2h::INTERVAL HOUR INTO d2h_h;
DBMS_OUTPUT.PUT_LINE('d2h_h : ' || d2h_h);
END;
/

DECLARE
v_d2h INTERVAL DAY TO HOUR := '9';
d2h_mi VARCHAR;
BEGIN
SELECT v_d2h::INTERVAL MINUTE INTO d2h_mi;
DBMS_OUTPUT.PUT_LINE('d2h_mi : ' || d2h_mi);
END;
/

DECLARE
v_d2h INTERVAL DAY TO HOUR := '9';
d2h_s VARCHAR;
BEGIN
SELECT v_d2h::INTERVAL SECOND INTO d2h_s;
DBMS_OUTPUT.PUT_LINE('d2h_s : ' || d2h_s);
END;
/

DECLARE
v_d2h INTERVAL DAY TO HOUR := '9';
d2h_y2m VARCHAR;
BEGIN
SELECT v_d2h::INTERVAL YEAR TO MONTH INTO d2h_y2m;
DBMS_OUTPUT.PUT_LINE('d2h_y2m : ' || d2h_y2m);
END;
/

DECLARE
v_d2h INTERVAL DAY TO HOUR := '9';
d2h_d2m VARCHAR;
BEGIN
SELECT v_d2h::INTERVAL DAY TO MINUTE INTO d2h_d2m;
DBMS_OUTPUT.PUT_LINE('d2h_d2m : ' || d2h_d2m);
END;
/

DECLARE
v_d2h INTERVAL DAY TO HOUR := '9';
d2h_d2s VARCHAR;
BEGIN
SELECT v_d2h::INTERVAL DAY TO SECOND INTO d2h_d2s;
DBMS_OUTPUT.PUT_LINE('d2h_d2s : ' || d2h_d2s);
END;
/

DECLARE
v_d2h INTERVAL DAY TO HOUR := '9';
d2h_h2m VARCHAR;
BEGIN
SELECT v_d2h::INTERVAL HOUR TO MINUTE INTO d2h_h2m;
DBMS_OUTPUT.PUT_LINE('d2h_h2m : ' || d2h_h2m);
END;
/

DECLARE
v_d2h INTERVAL DAY TO HOUR := '9';
d2h_h2s VARCHAR;
BEGIN
SELECT v_d2h::INTERVAL HOUR TO SECOND INTO d2h_h2s;
DBMS_OUTPUT.PUT_LINE('d2h_h2s : ' || d2h_h2s);
END;
/

DECLARE
v_d2h INTERVAL DAY TO HOUR := '9';
d2h_m2s VARCHAR;
BEGIN
SELECT v_d2h::INTERVAL MINUTE TO SECOND INTO d2h_m2s;
DBMS_OUTPUT.PUT_LINE('d2h_m2s : ' || d2h_m2s);
END;
/

//INTERVAL DAY TO MINUTE 的转换
DECLARE
v_d2m INTERVAL DAY TO MINUTE := '9';
d2m_y VARCHAR;
BEGIN
SELECT v_d2m::INTERVAL YEAR INTO d2m_y;
DBMS_OUTPUT.PUT_LINE('d2m_y : ' || d2m_y);
END;
/

DECLARE
v_d2m INTERVAL DAY TO MINUTE := '9';
d2m_m VARCHAR;
BEGIN
SELECT v_d2m::INTERVAL MONTH INTO d2m_m;
DBMS_OUTPUT.PUT_LINE('d2m_m : ' || d2m_m);
END;
/

DECLARE
v_d2m INTERVAL DAY TO MINUTE := '9';
d2m_d VARCHAR;
BEGIN
SELECT v_d2m::INTERVAL DAY INTO d2m_d;
DBMS_OUTPUT.PUT_LINE('d2m_d : ' || d2m_d);
END;
/

DECLARE
v_d2m INTERVAL DAY TO MINUTE := '9';
d2m_h VARCHAR;
BEGIN
SELECT v_d2m::INTERVAL HOUR INTO d2m_h;
DBMS_OUTPUT.PUT_LINE('d2m_h : ' || d2m_h);
END;
/

DECLARE
v_d2m INTERVAL DAY TO MINUTE := '9';
d2m_mi VARCHAR;
BEGIN
SELECT v_d2m::INTERVAL MINUTE INTO d2m_mi;
DBMS_OUTPUT.PUT_LINE('d2m_mi : ' || d2m_mi);
END;
/

DECLARE
v_d2m INTERVAL DAY TO MINUTE := '9';
d2m_s VARCHAR;
BEGIN
SELECT v_d2m::INTERVAL SECOND INTO d2m_s;
DBMS_OUTPUT.PUT_LINE('d2m_s : ' || d2m_s);
END;
/

DECLARE
v_d2m INTERVAL DAY TO MINUTE := '9';
d2m_y2m VARCHAR;
BEGIN
SELECT v_d2m::INTERVAL YEAR TO MONTH INTO d2m_y2m;
DBMS_OUTPUT.PUT_LINE('d2m_y2m : ' || d2m_y2m);
END;
/

DECLARE
v_d2m INTERVAL DAY TO MINUTE := '9';
d2m_d2h VARCHAR;
BEGIN
SELECT v_d2m::INTERVAL DAY TO HOUR INTO d2m_d2h;
DBMS_OUTPUT.PUT_LINE('d2m_d2h : ' || d2m_d2h);
END;
/

DECLARE
v_d2m INTERVAL DAY TO MINUTE := '9';
d2m_d2s VARCHAR;
BEGIN
SELECT v_d2m::INTERVAL DAY TO SECOND INTO d2m_d2s;
DBMS_OUTPUT.PUT_LINE('d2m_d2s : ' || d2m_d2s);
END;
/

DECLARE
v_d2m INTERVAL DAY TO MINUTE := '9';
d2m_h2m VARCHAR;
BEGIN
SELECT v_d2m::INTERVAL HOUR TO MINUTE INTO d2m_h2m;
DBMS_OUTPUT.PUT_LINE('d2m_h2m : ' || d2m_h2m);
END;
/

DECLARE
v_d2m INTERVAL DAY TO MINUTE := '9';
d2m_h2s VARCHAR;
BEGIN
SELECT v_d2m::INTERVAL HOUR TO SECOND INTO d2m_h2s;
DBMS_OUTPUT.PUT_LINE('d2m_h2s : ' || d2m_h2s);
END;
/

DECLARE
v_d2m INTERVAL DAY TO MINUTE := '9';
d2m_m2s VARCHAR;
BEGIN
SELECT v_d2m::INTERVAL MINUTE TO SECOND INTO d2m_m2s;
DBMS_OUTPUT.PUT_LINE('d2m_m2s : ' || d2m_m2s);
END;
/

//INTERVAL DAY TO SECOND 的转换
DECLARE
v_d2s INTERVAL DAY TO SECOND := '9';
d2s_y VARCHAR;
BEGIN
SELECT v_d2s::INTERVAL YEAR INTO d2s_y;
DBMS_OUTPUT.PUT_LINE('d2s_y : ' || d2s_y);
END;
/

DECLARE
v_d2s INTERVAL DAY TO SECOND := '9';
d2s_m VARCHAR;
BEGIN
SELECT v_d2s::INTERVAL MONTH INTO d2s_m;
DBMS_OUTPUT.PUT_LINE('d2s_m : ' || d2s_m);
END;
/

DECLARE
v_d2s INTERVAL DAY TO SECOND := '9';
d2s_d VARCHAR;
BEGIN
SELECT v_d2s::INTERVAL DAY INTO d2s_d;
DBMS_OUTPUT.PUT_LINE('d2s_d : ' || d2s_d);
END;
/

DECLARE
v_d2s INTERVAL DAY TO SECOND := '9';
d2s_h VARCHAR;
BEGIN
SELECT v_d2s::INTERVAL HOUR INTO d2s_h;
DBMS_OUTPUT.PUT_LINE('d2s_h : ' || d2s_h);
END;
/

DECLARE
v_d2s INTERVAL DAY TO SECOND := '9';
d2s_mi VARCHAR;
BEGIN
SELECT v_d2s::INTERVAL MINUTE INTO d2s_mi;
DBMS_OUTPUT.PUT_LINE('d2s_mi : ' || d2s_mi);
END;
/

DECLARE
v_d2s INTERVAL DAY TO SECOND := '9';
d2s_s VARCHAR;
BEGIN
SELECT v_d2s::INTERVAL SECOND INTO d2s_s;
DBMS_OUTPUT.PUT_LINE('d2s_s : ' || d2s_s);
END;
/

DECLARE
v_d2s INTERVAL DAY TO SECOND := '9';
d2s_y2m VARCHAR;
BEGIN
SELECT v_d2s::INTERVAL YEAR TO MONTH INTO d2s_y2m;
DBMS_OUTPUT.PUT_LINE('d2s_y2m : ' || d2s_y2m);
END;
/

DECLARE
v_d2s INTERVAL DAY TO SECOND := '9';
d2s_d2h VARCHAR;
BEGIN
SELECT v_d2s::INTERVAL DAY TO HOUR INTO d2s_d2h;
DBMS_OUTPUT.PUT_LINE('d2s_d2h : ' || d2s_d2h);
END;
/

DECLARE
v_d2s INTERVAL DAY TO SECOND := '9';
d2s_d2m VARCHAR;
BEGIN
SELECT v_d2s::INTERVAL DAY TO MINUTE INTO d2s_d2m;
DBMS_OUTPUT.PUT_LINE('d2s_d2m : ' || d2s_d2m);
END;
/

DECLARE
v_d2s INTERVAL DAY TO SECOND := '9';
d2s_h2m VARCHAR;
BEGIN
SELECT v_d2s::INTERVAL HOUR TO MINUTE INTO d2s_h2m;
DBMS_OUTPUT.PUT_LINE('d2s_h2m : ' || d2s_h2m);
END;
/

DECLARE
v_d2s INTERVAL DAY TO SECOND := '9';
d2s_h2s VARCHAR;
BEGIN
SELECT v_d2s::INTERVAL HOUR TO SECOND INTO d2s_h2s;
DBMS_OUTPUT.PUT_LINE('d2s_h2s : ' || d2s_h2s);
END;
/

DECLARE
v_d2s INTERVAL DAY TO SECOND := '9';
d2s_m2s VARCHAR;
BEGIN
SELECT v_d2s::INTERVAL MINUTE TO SECOND INTO d2s_m2s;
DBMS_OUTPUT.PUT_LINE('d2s_m2s : ' || d2s_m2s);
END;
/

//INTERVAL HOUR TO MINUTE 的转换
DECLARE
v_h2m INTERVAL HOUR TO MINUTE := '9';
h2m_y VARCHAR;
BEGIN
SELECT v_h2m::INTERVAL YEAR INTO h2m_y;
DBMS_OUTPUT.PUT_LINE('h2m_y : ' || h2m_y);
END;
/

DECLARE
v_h2m INTERVAL HOUR TO MINUTE := '9';
h2m_m VARCHAR;
BEGIN
SELECT v_h2m::INTERVAL MONTH INTO h2m_m;
DBMS_OUTPUT.PUT_LINE('h2m_m : ' || h2m_m);
END;
/

DECLARE
v_h2m INTERVAL HOUR TO MINUTE := '9';
h2m_d VARCHAR;
BEGIN
SELECT v_h2m::INTERVAL DAY INTO h2m_d;
DBMS_OUTPUT.PUT_LINE('h2m_d : ' || h2m_d);
END;
/

DECLARE
v_h2m INTERVAL HOUR TO MINUTE := '9';
h2m_h VARCHAR;
BEGIN
SELECT v_h2m::INTERVAL HOUR INTO h2m_h;
DBMS_OUTPUT.PUT_LINE('h2m_h : ' || h2m_h);
END;
/

DECLARE
v_h2m INTERVAL HOUR TO MINUTE := '9';
h2m_mi VARCHAR;
BEGIN
SELECT v_h2m::INTERVAL MINUTE INTO h2m_mi;
DBMS_OUTPUT.PUT_LINE('h2m_mi : ' || h2m_mi);
END;
/

DECLARE
v_h2m INTERVAL HOUR TO MINUTE := '9';
h2m_s VARCHAR;
BEGIN
SELECT v_h2m::INTERVAL SECOND INTO h2m_s;
DBMS_OUTPUT.PUT_LINE('h2m_s : ' || h2m_s);
END;
/

DECLARE
v_h2m INTERVAL HOUR TO MINUTE := '9';
h2m_y2m VARCHAR;
BEGIN
SELECT v_h2m::INTERVAL YEAR TO MONTH INTO h2m_y2m;
DBMS_OUTPUT.PUT_LINE('h2m_y2m : ' || h2m_y2m);
END;
/

DECLARE
v_h2m INTERVAL HOUR TO MINUTE := '9';
h2m_d2h VARCHAR;
BEGIN
SELECT v_h2m::INTERVAL DAY TO HOUR INTO h2m_d2h;
DBMS_OUTPUT.PUT_LINE('h2m_d2h : ' || h2m_d2h);
END;
/

DECLARE
v_h2m INTERVAL HOUR TO MINUTE := '9';
h2m_d2m VARCHAR;
BEGIN
SELECT v_h2m::INTERVAL DAY TO MINUTE INTO h2m_d2m;
DBMS_OUTPUT.PUT_LINE('h2m_d2m : ' || h2m_d2m);
END;
/

DECLARE
v_h2m INTERVAL HOUR TO MINUTE := '9';
h2m_d2s VARCHAR;
BEGIN
SELECT v_h2m::INTERVAL DAY TO SECOND INTO h2m_d2s;
DBMS_OUTPUT.PUT_LINE('h2m_d2s : ' || h2m_d2s);
END;
/

DECLARE
v_h2m INTERVAL HOUR TO MINUTE := '9';
h2m_h2s VARCHAR;
BEGIN
SELECT v_h2m::INTERVAL HOUR TO SECOND INTO h2m_h2s;
DBMS_OUTPUT.PUT_LINE('h2m_h2s : ' || h2m_h2s);
END;
/

DECLARE
v_h2m INTERVAL HOUR TO MINUTE := '9';
h2m_m2s VARCHAR;
BEGIN
SELECT v_h2m::INTERVAL MINUTE TO SECOND INTO h2m_m2s;
DBMS_OUTPUT.PUT_LINE('h2m_m2s : ' || h2m_m2s);
END;
/

//INTERVAL HOUR TO SECOND 的转换
DECLARE
v_h2s INTERVAL HOUR TO SECOND := '9';
h2s_y VARCHAR;
BEGIN
SELECT v_h2s::INTERVAL YEAR INTO h2s_y;
DBMS_OUTPUT.PUT_LINE('h2s_y : ' || h2s_y);
END;
/

DECLARE
v_h2s INTERVAL HOUR TO SECOND := '9';
h2s_m VARCHAR;
BEGIN
SELECT v_h2s::INTERVAL MONTH INTO h2s_m;
DBMS_OUTPUT.PUT_LINE('h2s_m : ' || h2s_m);
END;
/

DECLARE
v_h2s INTERVAL HOUR TO SECOND := '9';
h2s_d VARCHAR;
BEGIN
SELECT v_h2s::INTERVAL DAY INTO h2s_d;
DBMS_OUTPUT.PUT_LINE('h2s_d : ' || h2s_d);
END;
/

DECLARE
v_h2s INTERVAL HOUR TO SECOND := '9';
h2s_h VARCHAR;
BEGIN
SELECT v_h2s::INTERVAL HOUR INTO h2s_h;
DBMS_OUTPUT.PUT_LINE('h2s_h : ' || h2s_h);
END;
/

DECLARE
v_h2s INTERVAL HOUR TO SECOND := '9';
h2s_mi VARCHAR;
BEGIN
SELECT v_h2s::INTERVAL MINUTE INTO h2s_mi;
DBMS_OUTPUT.PUT_LINE('h2s_mi : ' || h2s_mi);
END;
/

DECLARE
v_h2s INTERVAL HOUR TO SECOND := '9';
h2s_s VARCHAR;
BEGIN
SELECT v_h2s::INTERVAL SECOND INTO h2s_s;
DBMS_OUTPUT.PUT_LINE('h2s_s : ' || h2s_s);
END;
/

DECLARE
v_h2s INTERVAL HOUR TO SECOND := '9';
h2s_y2m VARCHAR;
BEGIN
SELECT v_h2s::INTERVAL YEAR TO MONTH INTO h2s_y2m;
DBMS_OUTPUT.PUT_LINE('h2s_y2m : ' || h2s_y2m);
END;
/

DECLARE
v_h2s INTERVAL HOUR TO SECOND := '9';
h2s_d2h VARCHAR;
BEGIN
SELECT v_h2s::INTERVAL DAY TO HOUR INTO h2s_d2h;
DBMS_OUTPUT.PUT_LINE('h2s_d2h : ' || h2s_d2h);
END;
/

DECLARE
v_h2s INTERVAL HOUR TO SECOND := '9';
h2s_d2m VARCHAR;
BEGIN
SELECT v_h2s::INTERVAL DAY TO MINUTE INTO h2s_d2m;
DBMS_OUTPUT.PUT_LINE('h2s_d2m : ' || h2s_d2m);
END;
/

DECLARE
v_h2s INTERVAL HOUR TO SECOND := '9';
h2s_d2s VARCHAR;
BEGIN
SELECT v_h2s::INTERVAL DAY TO SECOND INTO h2s_d2s;
DBMS_OUTPUT.PUT_LINE('h2s_d2s : ' || h2s_d2s);
END;
/

DECLARE
v_h2s INTERVAL HOUR TO SECOND := '9';
h2s_h2m VARCHAR;
BEGIN
SELECT v_h2s::INTERVAL HOUR TO MINUTE INTO h2s_h2m;
DBMS_OUTPUT.PUT_LINE('h2s_h2m : ' || h2s_h2m);
END;
/

DECLARE
v_h2s INTERVAL HOUR TO SECOND := '9';
h2s_m2s VARCHAR;
BEGIN
SELECT v_h2s::INTERVAL MINUTE TO SECOND INTO h2s_m2s;
DBMS_OUTPUT.PUT_LINE('h2s_m2s : ' || h2s_m2s);
END;
/

//INTERVAL MINUTE TO SECOND 的转换
DECLARE
v_m2s INTERVAL MINUTE TO SECOND := '9';
m2s_y VARCHAR;
BEGIN
SELECT v_m2s::INTERVAL YEAR INTO m2s_y;
DBMS_OUTPUT.PUT_LINE('m2s_y : ' || m2s_y);
END;
/

DECLARE
v_m2s INTERVAL MINUTE TO SECOND := '9';
m2s_m VARCHAR;
BEGIN
SELECT v_m2s::INTERVAL MONTH INTO m2s_m;
DBMS_OUTPUT.PUT_LINE('m2s_m : ' || m2s_m);
END;
/

DECLARE
v_m2s INTERVAL MINUTE TO SECOND := '9';
m2s_d VARCHAR;
BEGIN
SELECT v_m2s::INTERVAL DAY INTO m2s_d;
DBMS_OUTPUT.PUT_LINE('m2s_d : ' || m2s_d);
END;
/

DECLARE
v_m2s INTERVAL MINUTE TO SECOND := '9';
m2s_h VARCHAR;
BEGIN
SELECT v_m2s::INTERVAL HOUR INTO m2s_h;
DBMS_OUTPUT.PUT_LINE('m2s_h : ' || m2s_h);
END;
/

DECLARE
v_m2s INTERVAL MINUTE TO SECOND := '9';
m2s_mi VARCHAR;
BEGIN
SELECT v_m2s::INTERVAL MINUTE INTO m2s_mi;
DBMS_OUTPUT.PUT_LINE('m2s_mi : ' || m2s_mi);
END;
/

DECLARE
v_m2s INTERVAL MINUTE TO SECOND := '9';
m2s_s VARCHAR;
BEGIN
SELECT v_m2s::INTERVAL SECOND INTO m2s_s;
DBMS_OUTPUT.PUT_LINE('m2s_s : ' || m2s_s);
END;
/

DECLARE
v_m2s INTERVAL MINUTE TO SECOND := '9';
m2s_y2m VARCHAR;
BEGIN
SELECT v_m2s::INTERVAL YEAR TO MONTH INTO m2s_y2m;
DBMS_OUTPUT.PUT_LINE('m2s_y2m : ' || m2s_y2m);
END;
/

DECLARE
v_m2s INTERVAL MINUTE TO SECOND := '9';
m2s_d2h VARCHAR;
BEGIN
SELECT v_m2s::INTERVAL DAY TO HOUR INTO m2s_d2h;
DBMS_OUTPUT.PUT_LINE('m2s_d2h : ' || m2s_d2h);
END;
/

DECLARE
v_m2s INTERVAL MINUTE TO SECOND := '9';
m2s_d2m VARCHAR;
BEGIN
SELECT v_m2s::INTERVAL DAY TO MINUTE INTO m2s_d2m;
DBMS_OUTPUT.PUT_LINE('m2s_d2m : ' || m2s_d2m);
END;
/

DECLARE
v_m2s INTERVAL MINUTE TO SECOND := '9';
m2s_d2s VARCHAR;
BEGIN
SELECT v_m2s::INTERVAL DAY TO SECOND INTO m2s_d2s;
DBMS_OUTPUT.PUT_LINE('m2s_d2s : ' || m2s_d2s);
END;
/

DECLARE
v_m2s INTERVAL MINUTE TO SECOND := '9';
m2s_h2m VARCHAR;
BEGIN
SELECT v_m2s::INTERVAL HOUR TO MINUTE INTO m2s_h2m;
DBMS_OUTPUT.PUT_LINE('m2s_h2m : ' || m2s_h2m);
END;
/

DECLARE
v_m2s INTERVAL MINUTE TO SECOND := '9';
m2s_h2s VARCHAR;
BEGIN
SELECT v_m2s::INTERVAL HOUR TO SECOND INTO m2s_h2s;
DBMS_OUTPUT.PUT_LINE('m2s_h2s : ' || m2s_h2s);
END;
/

!4 XG-TYPE-INTERVAL-002 INTERVAL 类型相互运算 : 块语句执行部分赋值
// INTERVAL YEAR 的转换
DECLARE
v_y INTERVAL YEAR;
y_m VARCHAR;
BEGIN
v_y := '9';
SELECT v_y::INTERVAL MONTH INTO y_m;
DBMS_OUTPUT.PUT_LINE('y_m : ' || y_m);
END;
/

DECLARE
v_y INTERVAL YEAR;
y_d VARCHAR;
BEGIN
v_y := '9';
SELECT v_y::INTERVAL DAY INTO y_d;
DBMS_OUTPUT.PUT_LINE('y_d : ' || y_d);
END;
/

DECLARE
v_y INTERVAL YEAR;
y_h VARCHAR;
BEGIN
v_y := '9';
SELECT v_y::INTERVAL HOUR INTO y_h;
DBMS_OUTPUT.PUT_LINE('y_h : ' || y_h);
END;
/

DECLARE
v_y INTERVAL YEAR;
y_mi VARCHAR;
BEGIN
v_y := '9';
SELECT v_y::INTERVAL MINUTE INTO y_mi;
DBMS_OUTPUT.PUT_LINE('y_mi : ' || y_mi);
END;
/

DECLARE
v_y INTERVAL YEAR;
y_s VARCHAR;
BEGIN
v_y := '9';
SELECT v_y::INTERVAL SECOND INTO y_s;
DBMS_OUTPUT.PUT_LINE('y_s : ' || y_s);
END;
/

DECLARE
v_y INTERVAL YEAR;
y_y2m VARCHAR;
BEGIN
v_y := '9';
SELECT v_y::INTERVAL YEAR TO MONTH INTO y_y2m;
DBMS_OUTPUT.PUT_LINE('y_y2m : ' || y_y2m);
END;
/

DECLARE
v_y INTERVAL YEAR;
y_d2h VARCHAR;
BEGIN
v_y := '9';
SELECT v_y::INTERVAL DAY TO HOUR INTO y_d2h;
DBMS_OUTPUT.PUT_LINE('y_d2h : ' || y_d2h);
END;
/

DECLARE
v_y INTERVAL YEAR;
y_d2m VARCHAR;
BEGIN
v_y := '9';
SELECT v_y::INTERVAL DAY TO MINUTE INTO y_d2m;
DBMS_OUTPUT.PUT_LINE('y_d2m : ' || y_d2m);
END;
/

DECLARE
v_y INTERVAL YEAR;
y_d2s VARCHAR;
BEGIN
v_y := '9';
SELECT v_y::INTERVAL DAY TO SECOND INTO y_d2s;
DBMS_OUTPUT.PUT_LINE('y_d2s : ' || y_d2s);
END;
/

DECLARE
v_y INTERVAL YEAR;
y_h2m VARCHAR;
BEGIN
v_y := '9';
SELECT v_y::INTERVAL HOUR TO MINUTE INTO y_h2m;
DBMS_OUTPUT.PUT_LINE('y_h2m : ' || y_h2m);
END;
/

DECLARE
v_y INTERVAL YEAR;
y_h2s VARCHAR;
BEGIN
v_y := '9';
SELECT v_y::INTERVAL HOUR TO SECOND INTO y_h2s;
DBMS_OUTPUT.PUT_LINE('y_h2s : ' || y_h2s);
END;
/

DECLARE
v_y INTERVAL YEAR;
y_m2s VARCHAR;
BEGIN
v_y := '9';
SELECT v_y::INTERVAL MINUTE TO SECOND INTO y_m2s;
DBMS_OUTPUT.PUT_LINE('y_m2s : ' || y_m2s);
END;
/

//INTERVAL MONTH 的转换
DECLARE
v_m INTERVAL MONTH;
m_y VARCHAR;
BEGIN
v_m := '9';
SELECT v_m::INTERVAL YEAR INTO m_y;
DBMS_OUTPUT.PUT_LINE('m_y : ' || m_y);
END;
/

DECLARE
v_m INTERVAL MONTH;
m_d VARCHAR;
BEGIN
v_m := '9';
SELECT v_m::INTERVAL DAY INTO m_d;
DBMS_OUTPUT.PUT_LINE('m_d : ' || m_d);
END;
/

DECLARE
v_m INTERVAL MONTH;
m_h VARCHAR;
BEGIN
v_m := '9';
SELECT v_m::INTERVAL HOUR INTO m_h;
DBMS_OUTPUT.PUT_LINE('m_h : ' || m_h);
END;
/

DECLARE
v_m INTERVAL MONTH;
m_mi VARCHAR;
BEGIN
v_m := '9';
SELECT v_m::INTERVAL MINUTE INTO m_mi;
DBMS_OUTPUT.PUT_LINE('m_mi : ' || m_mi);
END;
/

DECLARE
v_m INTERVAL MONTH;
m_s VARCHAR;
BEGIN
v_m := '9';
SELECT v_m::INTERVAL SECOND INTO m_s;
DBMS_OUTPUT.PUT_LINE('m_s : ' || m_s);
END;
/

DECLARE
v_m INTERVAL MONTH;
m_y2m VARCHAR;
BEGIN
v_m := '9';
SELECT v_m::INTERVAL YEAR TO MONTH INTO m_y2m;
DBMS_OUTPUT.PUT_LINE('m_y2m : ' || m_y2m);
END;
/

DECLARE
v_m INTERVAL MONTH;
m_d2h VARCHAR;
BEGIN
v_m := '9';
SELECT v_m::INTERVAL DAY TO HOUR INTO m_d2h;
DBMS_OUTPUT.PUT_LINE('m_d2h : ' || m_d2h);
END;
/

DECLARE
v_m INTERVAL MONTH;
m_d2m VARCHAR;
BEGIN
v_m := '9';
SELECT v_m::INTERVAL DAY TO MINUTE INTO m_d2m;
DBMS_OUTPUT.PUT_LINE('m_d2m : ' || m_d2m);
END;
/

DECLARE
v_m INTERVAL MONTH;
m_d2s VARCHAR;
BEGIN
v_m := '9';
SELECT v_m::INTERVAL DAY TO SECOND INTO m_d2s;
DBMS_OUTPUT.PUT_LINE('m_d2s : ' || m_d2s);
END;
/

DECLARE
v_m INTERVAL MONTH;
m_h2m VARCHAR;
BEGIN
v_m := '9';
SELECT v_m::INTERVAL HOUR TO MINUTE INTO m_h2m;
DBMS_OUTPUT.PUT_LINE('m_h2m : ' || m_h2m);
END;
/

DECLARE
v_m INTERVAL MONTH;
m_h2s VARCHAR;
BEGIN
v_m := '9';
SELECT v_m::INTERVAL HOUR TO SECOND INTO m_h2s;
DBMS_OUTPUT.PUT_LINE('m_h2s : ' || m_h2s);
END;
/

DECLARE
v_m INTERVAL MONTH;
m_m2s VARCHAR;
BEGIN
v_m := '9';
SELECT v_m::INTERVAL MINUTE TO SECOND INTO m_m2s;
DBMS_OUTPUT.PUT_LINE('m_m2s : ' || m_m2s);
END;
/

//INTERVAL DAY 的转换
DECLARE
v_d INTERVAL DAY;
d_y VARCHAR;
BEGIN
v_d := '9';
SELECT v_d::INTERVAL YEAR INTO d_y;
DBMS_OUTPUT.PUT_LINE('d_y : ' || d_y);
END;
/

DECLARE
v_d INTERVAL DAY;
d_m VARCHAR;
BEGIN
v_d := '9';
SELECT v_d::INTERVAL MONTH INTO d_m;
DBMS_OUTPUT.PUT_LINE('d_m : ' || d_m);
END;
/

DECLARE
v_d INTERVAL DAY;
d_h VARCHAR;
BEGIN
v_d := '9';
SELECT v_d::INTERVAL HOUR INTO d_h;
DBMS_OUTPUT.PUT_LINE('d_h : ' || d_h);
END;
/

DECLARE
v_d INTERVAL DAY;
d_mi VARCHAR;
BEGIN
v_d := '9';
SELECT v_d::INTERVAL MINUTE INTO d_mi;
DBMS_OUTPUT.PUT_LINE('d_mi : ' || d_mi);
END;
/

DECLARE
v_d INTERVAL DAY;
d_s VARCHAR;
BEGIN
v_d := '9';
SELECT v_d::INTERVAL SECOND INTO d_s;
DBMS_OUTPUT.PUT_LINE('d_s : ' || d_s);
END;
/

DECLARE
v_d INTERVAL DAY;
d_y2m VARCHAR;
BEGIN
v_d := '9';
SELECT v_d::INTERVAL YEAR TO MONTH INTO d_y2m;
DBMS_OUTPUT.PUT_LINE('d_y2m : ' || d_y2m);
END;
/

DECLARE
v_d INTERVAL DAY;
d_d2h VARCHAR;
BEGIN
v_d := '9';
SELECT v_d::INTERVAL DAY TO HOUR INTO d_d2h;
DBMS_OUTPUT.PUT_LINE('d_d2h : ' || d_d2h);
END;
/

DECLARE
v_d INTERVAL DAY;
d_d2m VARCHAR;
BEGIN
v_d := '9';
SELECT v_d::INTERVAL DAY TO MINUTE INTO d_d2m;
DBMS_OUTPUT.PUT_LINE('d_d2m : ' || d_d2m);
END;
/

DECLARE
v_d INTERVAL DAY;
d_d2s VARCHAR;
BEGIN
v_d := '9';
SELECT v_d::INTERVAL DAY TO SECOND INTO d_d2s;
DBMS_OUTPUT.PUT_LINE('d_d2s : ' || d_d2s);
END;
/

DECLARE
v_d INTERVAL DAY;
d_h2m VARCHAR;
BEGIN
v_d := '9';
SELECT v_d::INTERVAL HOUR TO MINUTE INTO d_h2m;
DBMS_OUTPUT.PUT_LINE('d_h2m : ' || d_h2m);
END;
/

DECLARE
v_d INTERVAL DAY;
d_h2s VARCHAR;
BEGIN
v_d := '9';
SELECT v_d::INTERVAL HOUR TO SECOND INTO d_h2s;
DBMS_OUTPUT.PUT_LINE('d_h2s : ' || d_h2s);
END;
/

DECLARE
v_d INTERVAL DAY;
d_m2s VARCHAR;
BEGIN
v_d := '9';
SELECT v_d::INTERVAL MINUTE TO SECOND INTO d_m2s;
DBMS_OUTPUT.PUT_LINE('d_m2s : ' || d_m2s);
END;
/

//INTERVAL HOUR 的转换
DECLARE
v_h INTERVAL HOUR;
h_y VARCHAR;
BEGIN
v_h := '9';
SELECT v_h::INTERVAL YEAR INTO h_y;
DBMS_OUTPUT.PUT_LINE('h_y : ' || h_y);
END;
/

DECLARE
v_h INTERVAL HOUR;
h_m VARCHAR;
BEGIN
v_h := '9';
SELECT v_h::INTERVAL MONTH INTO h_m;
DBMS_OUTPUT.PUT_LINE('h_m : ' || h_m);
END;
/

DECLARE
v_h INTERVAL HOUR;
h_d VARCHAR;
BEGIN
v_h := '9';
SELECT v_h::INTERVAL DAY INTO h_d;
DBMS_OUTPUT.PUT_LINE('h_d : ' || h_d);
END;
/

DECLARE
v_h INTERVAL HOUR;
h_mi VARCHAR;
BEGIN
v_h := '9';
SELECT v_h::INTERVAL MINUTE INTO h_mi;
DBMS_OUTPUT.PUT_LINE('h_mi : ' || h_mi);
END;
/

DECLARE
v_h INTERVAL HOUR;
h_s VARCHAR;
BEGIN
v_h := '9';
SELECT v_h::INTERVAL SECOND INTO h_s;
DBMS_OUTPUT.PUT_LINE('h_s : ' || h_s);
END;
/

DECLARE
v_h INTERVAL HOUR;
h_y2m VARCHAR;
BEGIN
v_h := '9';
SELECT v_h::INTERVAL YEAR TO MONTH INTO h_y2m;
DBMS_OUTPUT.PUT_LINE('h_y2m : ' || h_y2m);
END;
/

DECLARE
v_h INTERVAL HOUR;
h_d2h VARCHAR;
BEGIN
v_h := '9';
SELECT v_h::INTERVAL DAY TO HOUR INTO h_d2h;
DBMS_OUTPUT.PUT_LINE('h_d2h : ' || h_d2h);
END;
/

DECLARE
v_h INTERVAL HOUR;
h_d2m VARCHAR;
BEGIN
v_h := '9';
SELECT v_h::INTERVAL DAY TO MINUTE INTO h_d2m;
DBMS_OUTPUT.PUT_LINE('h_d2m : ' || h_d2m);
END;
/

DECLARE
v_h INTERVAL HOUR;
h_d2s VARCHAR;
BEGIN
v_h := '9';
SELECT v_h::INTERVAL DAY TO SECOND INTO h_d2s;
DBMS_OUTPUT.PUT_LINE('h_d2s : ' || h_d2s);
END;
/

DECLARE
v_h INTERVAL HOUR;
h_h2m VARCHAR;
BEGIN
v_h := '9';
SELECT v_h::INTERVAL HOUR TO MINUTE INTO h_h2m;
DBMS_OUTPUT.PUT_LINE('h_h2m : ' || h_h2m);
END;
/

DECLARE
v_h INTERVAL HOUR;
h_h2s VARCHAR;
BEGIN
v_h := '9';
SELECT v_h::INTERVAL HOUR TO SECOND INTO h_h2s;
DBMS_OUTPUT.PUT_LINE('h_h2s : ' || h_h2s);
END;
/

DECLARE
v_h INTERVAL HOUR;
h_m2s VARCHAR;
BEGIN
v_h := '9';
SELECT v_h::INTERVAL MINUTE TO SECOND INTO h_m2s;
DBMS_OUTPUT.PUT_LINE('h_m2s : ' || h_m2s);
END;
/

//INTERVAL MINUTE 的转换
DECLARE
v_mi INTERVAL MINUTE;
mi_y VARCHAR;
BEGIN
v_mi := '9';
SELECT v_mi::INTERVAL YEAR INTO mi_y;
DBMS_OUTPUT.PUT_LINE('mi_y : ' || mi_y);
END;
/

DECLARE
v_mi INTERVAL MINUTE;
mi_m VARCHAR;
BEGIN
v_mi := '9';
SELECT v_mi::INTERVAL MONTH INTO mi_m;
DBMS_OUTPUT.PUT_LINE('mi_m : ' || mi_m);
END;
/

DECLARE
v_mi INTERVAL MINUTE;
mi_d VARCHAR;
BEGIN
v_mi := '9';
SELECT v_mi::INTERVAL DAY INTO mi_d;
DBMS_OUTPUT.PUT_LINE('mi_d : ' || mi_d);
END;
/

DECLARE
v_mi INTERVAL MINUTE;
mi_h VARCHAR;
BEGIN
v_mi := '9';
SELECT v_mi::INTERVAL HOUR INTO mi_h;
DBMS_OUTPUT.PUT_LINE('mi_h : ' || mi_h);
END;
/

DECLARE
v_mi INTERVAL MINUTE;
mi_s VARCHAR;
BEGIN
v_mi := '9';
SELECT v_mi::INTERVAL SECOND INTO mi_s;
DBMS_OUTPUT.PUT_LINE('mi_s : ' || mi_s);
END;
/

DECLARE
v_mi INTERVAL MINUTE;
mi_y2m VARCHAR;
BEGIN
v_mi := '9';
SELECT v_mi::INTERVAL YEAR TO MONTH INTO mi_y2m;
DBMS_OUTPUT.PUT_LINE('mi_y2m : ' || mi_y2m);
END;
/

DECLARE
v_mi INTERVAL MINUTE;
mi_d2h VARCHAR;
BEGIN
v_mi := '9';
SELECT v_mi::INTERVAL DAY TO HOUR INTO mi_d2h;
DBMS_OUTPUT.PUT_LINE('mi_d2h : ' || mi_d2h);
END;
/

DECLARE
v_mi INTERVAL MINUTE;
mi_d2m VARCHAR;
BEGIN
v_mi := '9';
SELECT v_mi::INTERVAL DAY TO MINUTE INTO mi_d2m;
DBMS_OUTPUT.PUT_LINE('mi_d2m : ' || mi_d2m);
END;
/

DECLARE
v_mi INTERVAL MINUTE;
mi_d2s VARCHAR;
BEGIN
v_mi := '9';
SELECT v_mi::INTERVAL DAY TO SECOND INTO mi_d2s;
DBMS_OUTPUT.PUT_LINE('mi_d2s : ' || mi_d2s);
END;
/

DECLARE
v_mi INTERVAL MINUTE;
mi_h2m VARCHAR;
BEGIN
v_mi := '9';
SELECT v_mi::INTERVAL HOUR TO MINUTE INTO mi_h2m;
DBMS_OUTPUT.PUT_LINE('mi_h2m : ' || mi_h2m);
END;
/

DECLARE
v_mi INTERVAL MINUTE;
mi_h2s VARCHAR;
BEGIN
v_mi := '9';
SELECT v_mi::INTERVAL HOUR TO SECOND INTO mi_h2s;
DBMS_OUTPUT.PUT_LINE('mi_h2s : ' || mi_h2s);
END;
/

DECLARE
v_mi INTERVAL MINUTE;
mi_m2s VARCHAR;
BEGIN
v_mi := '9';
SELECT v_mi::INTERVAL MINUTE TO SECOND INTO mi_m2s;
DBMS_OUTPUT.PUT_LINE('mi_m2s : ' || mi_m2s);
END;
/

//INTERVAL SECOND 的转换
DECLARE
v_s INTERVAL SECOND;
s_y VARCHAR;
BEGIN
v_s := '9';
SELECT v_s::INTERVAL YEAR INTO s_y;
DBMS_OUTPUT.PUT_LINE('s_y : ' || s_y);
END;
/

DECLARE
v_s INTERVAL SECOND;
s_m VARCHAR;
BEGIN
v_s := '9';
SELECT v_s::INTERVAL MONTH INTO s_m;
DBMS_OUTPUT.PUT_LINE('s_m : ' || s_m);
END;
/

DECLARE
v_s INTERVAL SECOND;
s_d VARCHAR;
BEGIN
v_s := '9';
SELECT v_s::INTERVAL DAY INTO s_d;
DBMS_OUTPUT.PUT_LINE('s_d : ' || s_d);
END;
/

DECLARE
v_s INTERVAL SECOND;
s_h VARCHAR;
BEGIN
v_s := '9';
SELECT v_s::INTERVAL HOUR INTO s_h;
DBMS_OUTPUT.PUT_LINE('s_h : ' || s_h);
END;
/

DECLARE
v_s INTERVAL SECOND;
s_mi VARCHAR;
BEGIN
v_s := '9';
SELECT v_s::INTERVAL MINUTE INTO s_mi;
DBMS_OUTPUT.PUT_LINE('s_mi : ' || s_mi);
END;
/

DECLARE
v_s INTERVAL SECOND;
s_y2m VARCHAR;
BEGIN
v_s := '9';
SELECT v_s::INTERVAL YEAR TO MONTH INTO s_y2m;
DBMS_OUTPUT.PUT_LINE('s_y2m : ' || s_y2m);
END;
/

DECLARE
v_s INTERVAL SECOND;
s_d2h VARCHAR;
BEGIN
v_s := '9';
SELECT v_s::INTERVAL DAY TO HOUR INTO s_d2h;
DBMS_OUTPUT.PUT_LINE('s_d2h : ' || s_d2h);
END;
/

DECLARE
v_s INTERVAL SECOND;
s_d2m VARCHAR;
BEGIN
v_s := '9';
SELECT v_s::INTERVAL DAY TO MINUTE INTO s_d2m;
DBMS_OUTPUT.PUT_LINE('s_d2m : ' || s_d2m);
END;
/

DECLARE
v_s INTERVAL SECOND;
s_d2s VARCHAR;
BEGIN
v_s := '9';
SELECT v_s::INTERVAL DAY TO SECOND INTO s_d2s;
DBMS_OUTPUT.PUT_LINE('s_d2s : ' || s_d2s);
END;
/

DECLARE
v_s INTERVAL SECOND;
s_h2m VARCHAR;
BEGIN
v_s := '9';
SELECT v_s::INTERVAL HOUR TO MINUTE INTO s_h2m;
DBMS_OUTPUT.PUT_LINE('s_h2m : ' || s_h2m);
END;
/

DECLARE
v_s INTERVAL SECOND;
s_h2s VARCHAR;
BEGIN
v_s := '9';
SELECT v_s::INTERVAL HOUR TO SECOND INTO s_h2s;
DBMS_OUTPUT.PUT_LINE('s_h2s : ' || s_h2s);
END;
/

DECLARE
v_s INTERVAL SECOND;
s_m2s VARCHAR;
BEGIN
v_s := '9';
SELECT v_s::INTERVAL MINUTE TO SECOND INTO s_m2s;
DBMS_OUTPUT.PUT_LINE('s_m2s : ' || s_m2s);
END;
/

//INTERVAL YEAR TO MONTH 的转换
DECLARE
v_y2m INTERVAL YEAR TO MONTH;
y2m_y VARCHAR;
BEGIN
v_y2m := '9';
SELECT v_y2m::INTERVAL YEAR INTO y2m_y;
DBMS_OUTPUT.PUT_LINE('y2m_y : ' || y2m_y);
END;
/

DECLARE
v_y2m INTERVAL YEAR TO MONTH;
y2m_m VARCHAR;
BEGIN
v_y2m := '9';
SELECT v_y2m::INTERVAL MONTH INTO y2m_m;
DBMS_OUTPUT.PUT_LINE('y2m_m : ' || y2m_m);
END;
/

DECLARE
v_y2m INTERVAL YEAR TO MONTH;
y2m_d VARCHAR;
BEGIN
v_y2m := '9';
SELECT v_y2m::INTERVAL DAY INTO y2m_d;
DBMS_OUTPUT.PUT_LINE('y2m_d : ' || y2m_d);
END;
/

DECLARE
v_y2m INTERVAL YEAR TO MONTH;
y2m_h VARCHAR;
BEGIN
v_y2m := '9';
SELECT v_y2m::INTERVAL HOUR INTO y2m_h;
DBMS_OUTPUT.PUT_LINE('y2m_h : ' || y2m_h);
END;
/

DECLARE
v_y2m INTERVAL YEAR TO MONTH;
y2m_mi VARCHAR;
BEGIN
v_y2m := '9';
SELECT v_y2m::INTERVAL MINUTE INTO y2m_mi;
DBMS_OUTPUT.PUT_LINE('y2m_mi : ' || y2m_mi);
END;
/

DECLARE
v_y2m INTERVAL YEAR TO MONTH;
y2m_s VARCHAR;
BEGIN
v_y2m := '9';
SELECT v_y2m::INTERVAL SECOND INTO y2m_s;
DBMS_OUTPUT.PUT_LINE('y2m_s : ' || y2m_s);
END;
/

DECLARE
v_y2m INTERVAL YEAR TO MONTH;
y2m_d2h VARCHAR;
BEGIN
v_y2m := '9';
SELECT v_y2m::INTERVAL DAY TO HOUR INTO y2m_d2h;
DBMS_OUTPUT.PUT_LINE('y2m_d2h : ' || y2m_d2h);
END;
/

DECLARE
v_y2m INTERVAL YEAR TO MONTH;
y2m_d2m VARCHAR;
BEGIN
v_y2m := '9';
SELECT v_y2m::INTERVAL DAY TO MINUTE INTO y2m_d2m;
DBMS_OUTPUT.PUT_LINE('y2m_d2m : ' || y2m_d2m);
END;
/

DECLARE
v_y2m INTERVAL YEAR TO MONTH;
y2m_d2s VARCHAR;
BEGIN
v_y2m := '9';
SELECT v_y2m::INTERVAL DAY TO SECOND INTO y2m_d2s;
DBMS_OUTPUT.PUT_LINE('y2m_d2s : ' || y2m_d2s);
END;
/

DECLARE
v_y2m INTERVAL YEAR TO MONTH;
y2m_h2m VARCHAR;
BEGIN
v_y2m := '9';
SELECT v_y2m::INTERVAL HOUR TO MINUTE INTO y2m_h2m;
DBMS_OUTPUT.PUT_LINE('y2m_h2m : ' || y2m_h2m);
END;
/

DECLARE
v_y2m INTERVAL YEAR TO MONTH;
y2m_h2s VARCHAR;
BEGIN
v_y2m := '9';
SELECT v_y2m::INTERVAL HOUR TO SECOND INTO y2m_h2s;
DBMS_OUTPUT.PUT_LINE('y2m_h2s : ' || y2m_h2s);
END;
/

DECLARE
v_y2m INTERVAL YEAR TO MONTH;
y2m_m2s VARCHAR;
BEGIN
v_y2m := '9';
SELECT v_y2m::INTERVAL MINUTE TO SECOND INTO y2m_m2s;
DBMS_OUTPUT.PUT_LINE('y2m_m2s : ' || y2m_m2s);
END;
/

//INTERVAL DAY TO HOUR 的转换
DECLARE
v_d2h INTERVAL DAY TO HOUR;
d2h_y VARCHAR;
BEGIN
v_d2h := '9';
SELECT v_d2h::INTERVAL YEAR INTO d2h_y;
DBMS_OUTPUT.PUT_LINE('d2h_y : ' || d2h_y);
END;
/

DECLARE
v_d2h INTERVAL DAY TO HOUR;
d2h_m VARCHAR;
BEGIN
v_d2h := '9';
SELECT v_d2h::INTERVAL MONTH INTO d2h_m;
DBMS_OUTPUT.PUT_LINE('d2h_m : ' || d2h_m);
END;
/

DECLARE
v_d2h INTERVAL DAY TO HOUR;
d2h_d VARCHAR;
BEGIN
v_d2h := '9';
SELECT v_d2h::INTERVAL DAY INTO d2h_d;
DBMS_OUTPUT.PUT_LINE('d2h_d : ' || d2h_d);
END;
/

DECLARE
v_d2h INTERVAL DAY TO HOUR;
d2h_h VARCHAR;
BEGIN
v_d2h := '9';
SELECT v_d2h::INTERVAL HOUR INTO d2h_h;
DBMS_OUTPUT.PUT_LINE('d2h_h : ' || d2h_h);
END;
/

DECLARE
v_d2h INTERVAL DAY TO HOUR;
d2h_mi VARCHAR;
BEGIN
v_d2h := '9';
SELECT v_d2h::INTERVAL MINUTE INTO d2h_mi;
DBMS_OUTPUT.PUT_LINE('d2h_mi : ' || d2h_mi);
END;
/

DECLARE
v_d2h INTERVAL DAY TO HOUR;
d2h_s VARCHAR;
BEGIN
v_d2h := '9';
SELECT v_d2h::INTERVAL SECOND INTO d2h_s;
DBMS_OUTPUT.PUT_LINE('d2h_s : ' || d2h_s);
END;
/

DECLARE
v_d2h INTERVAL DAY TO HOUR;
d2h_y2m VARCHAR;
BEGIN
v_d2h := '9';
SELECT v_d2h::INTERVAL YEAR TO MONTH INTO d2h_y2m;
DBMS_OUTPUT.PUT_LINE('d2h_y2m : ' || d2h_y2m);
END;
/

DECLARE
v_d2h INTERVAL DAY TO HOUR;
d2h_d2m VARCHAR;
BEGIN
v_d2h := '9';
SELECT v_d2h::INTERVAL DAY TO MINUTE INTO d2h_d2m;
DBMS_OUTPUT.PUT_LINE('d2h_d2m : ' || d2h_d2m);
END;
/

DECLARE
v_d2h INTERVAL DAY TO HOUR;
d2h_d2s VARCHAR;
BEGIN
v_d2h := '9';
SELECT v_d2h::INTERVAL DAY TO SECOND INTO d2h_d2s;
DBMS_OUTPUT.PUT_LINE('d2h_d2s : ' || d2h_d2s);
END;
/

DECLARE
v_d2h INTERVAL DAY TO HOUR;
d2h_h2m VARCHAR;
BEGIN
v_d2h := '9';
SELECT v_d2h::INTERVAL HOUR TO MINUTE INTO d2h_h2m;
DBMS_OUTPUT.PUT_LINE('d2h_h2m : ' || d2h_h2m);
END;
/

DECLARE
v_d2h INTERVAL DAY TO HOUR;
d2h_h2s VARCHAR;
BEGIN
v_d2h := '9';
SELECT v_d2h::INTERVAL HOUR TO SECOND INTO d2h_h2s;
DBMS_OUTPUT.PUT_LINE('d2h_h2s : ' || d2h_h2s);
END;
/

DECLARE
v_d2h INTERVAL DAY TO HOUR;
d2h_m2s VARCHAR;
BEGIN
v_d2h := '9';
SELECT v_d2h::INTERVAL MINUTE TO SECOND INTO d2h_m2s;
DBMS_OUTPUT.PUT_LINE('d2h_m2s : ' || d2h_m2s);
END;
/

//INTERVAL DAY TO MINUTE 的转换
DECLARE
v_d2m INTERVAL DAY TO MINUTE;
d2m_y VARCHAR;
BEGIN
v_d2m := '9';
SELECT v_d2m::INTERVAL YEAR INTO d2m_y;
DBMS_OUTPUT.PUT_LINE('d2m_y : ' || d2m_y);
END;
/

DECLARE
v_d2m INTERVAL DAY TO MINUTE;
d2m_m VARCHAR;
BEGIN
v_d2m := '9';
SELECT v_d2m::INTERVAL MONTH INTO d2m_m;
DBMS_OUTPUT.PUT_LINE('d2m_m : ' || d2m_m);
END;
/

DECLARE
v_d2m INTERVAL DAY TO MINUTE;
d2m_d VARCHAR;
BEGIN
v_d2m := '9';
SELECT v_d2m::INTERVAL DAY INTO d2m_d;
DBMS_OUTPUT.PUT_LINE('d2m_d : ' || d2m_d);
END;
/

DECLARE
v_d2m INTERVAL DAY TO MINUTE;
d2m_h VARCHAR;
BEGIN
v_d2m := '9';
SELECT v_d2m::INTERVAL HOUR INTO d2m_h;
DBMS_OUTPUT.PUT_LINE('d2m_h : ' || d2m_h);
END;
/

DECLARE
v_d2m INTERVAL DAY TO MINUTE;
d2m_mi VARCHAR;
BEGIN
v_d2m := '9';
SELECT v_d2m::INTERVAL MINUTE INTO d2m_mi;
DBMS_OUTPUT.PUT_LINE('d2m_mi : ' || d2m_mi);
END;
/

DECLARE
v_d2m INTERVAL DAY TO MINUTE;
d2m_s VARCHAR;
BEGIN
v_d2m := '9';
SELECT v_d2m::INTERVAL SECOND INTO d2m_s;
DBMS_OUTPUT.PUT_LINE('d2m_s : ' || d2m_s);
END;
/

DECLARE
v_d2m INTERVAL DAY TO MINUTE;
d2m_y2m VARCHAR;
BEGIN
v_d2m := '9';
SELECT v_d2m::INTERVAL YEAR TO MONTH INTO d2m_y2m;
DBMS_OUTPUT.PUT_LINE('d2m_y2m : ' || d2m_y2m);
END;
/

DECLARE
v_d2m INTERVAL DAY TO MINUTE;
d2m_d2h VARCHAR;
BEGIN
v_d2m := '9';
SELECT v_d2m::INTERVAL DAY TO HOUR INTO d2m_d2h;
DBMS_OUTPUT.PUT_LINE('d2m_d2h : ' || d2m_d2h);
END;
/

DECLARE
v_d2m INTERVAL DAY TO MINUTE;
d2m_d2s VARCHAR;
BEGIN
v_d2m := '9';
SELECT v_d2m::INTERVAL DAY TO SECOND INTO d2m_d2s;
DBMS_OUTPUT.PUT_LINE('d2m_d2s : ' || d2m_d2s);
END;
/

DECLARE
v_d2m INTERVAL DAY TO MINUTE;
d2m_h2m VARCHAR;
BEGIN
v_d2m := '9';
SELECT v_d2m::INTERVAL HOUR TO MINUTE INTO d2m_h2m;
DBMS_OUTPUT.PUT_LINE('d2m_h2m : ' || d2m_h2m);
END;
/

DECLARE
v_d2m INTERVAL DAY TO MINUTE;
d2m_h2s VARCHAR;
BEGIN
v_d2m := '9';
SELECT v_d2m::INTERVAL HOUR TO SECOND INTO d2m_h2s;
DBMS_OUTPUT.PUT_LINE('d2m_h2s : ' || d2m_h2s);
END;
/

DECLARE
v_d2m INTERVAL DAY TO MINUTE;
d2m_m2s VARCHAR;
BEGIN
v_d2m := '9';
SELECT v_d2m::INTERVAL MINUTE TO SECOND INTO d2m_m2s;
DBMS_OUTPUT.PUT_LINE('d2m_m2s : ' || d2m_m2s);
END;
/

//INTERVAL DAY TO SECOND 的转换
DECLARE
v_d2s INTERVAL DAY TO SECOND;
d2s_y VARCHAR;
BEGIN
v_d2s := '9';
SELECT v_d2s::INTERVAL YEAR INTO d2s_y;
DBMS_OUTPUT.PUT_LINE('d2s_y : ' || d2s_y);
END;
/

DECLARE
v_d2s INTERVAL DAY TO SECOND;
d2s_m VARCHAR;
BEGIN
v_d2s := '9';
SELECT v_d2s::INTERVAL MONTH INTO d2s_m;
DBMS_OUTPUT.PUT_LINE('d2s_m : ' || d2s_m);
END;
/

DECLARE
v_d2s INTERVAL DAY TO SECOND;
d2s_d VARCHAR;
BEGIN
v_d2s := '9';
SELECT v_d2s::INTERVAL DAY INTO d2s_d;
DBMS_OUTPUT.PUT_LINE('d2s_d : ' || d2s_d);
END;
/

DECLARE
v_d2s INTERVAL DAY TO SECOND;
d2s_h VARCHAR;
BEGIN
v_d2s := '9';
SELECT v_d2s::INTERVAL HOUR INTO d2s_h;
DBMS_OUTPUT.PUT_LINE('d2s_h : ' || d2s_h);
END;
/

DECLARE
v_d2s INTERVAL DAY TO SECOND;
d2s_mi VARCHAR;
BEGIN
v_d2s := '9';
SELECT v_d2s::INTERVAL MINUTE INTO d2s_mi;
DBMS_OUTPUT.PUT_LINE('d2s_mi : ' || d2s_mi);
END;
/

DECLARE
v_d2s INTERVAL DAY TO SECOND;
d2s_s VARCHAR;
BEGIN
v_d2s := '9';
SELECT v_d2s::INTERVAL SECOND INTO d2s_s;
DBMS_OUTPUT.PUT_LINE('d2s_s : ' || d2s_s);
END;
/

DECLARE
v_d2s INTERVAL DAY TO SECOND;
d2s_y2m VARCHAR;
BEGIN
v_d2s := '9';
SELECT v_d2s::INTERVAL YEAR TO MONTH INTO d2s_y2m;
DBMS_OUTPUT.PUT_LINE('d2s_y2m : ' || d2s_y2m);
END;
/

DECLARE
v_d2s INTERVAL DAY TO SECOND;
d2s_d2h VARCHAR;
BEGIN
v_d2s := '9';
SELECT v_d2s::INTERVAL DAY TO HOUR INTO d2s_d2h;
DBMS_OUTPUT.PUT_LINE('d2s_d2h : ' || d2s_d2h);
END;
/

DECLARE
v_d2s INTERVAL DAY TO SECOND;
d2s_d2m VARCHAR;
BEGIN
v_d2s := '9';
SELECT v_d2s::INTERVAL DAY TO MINUTE INTO d2s_d2m;
DBMS_OUTPUT.PUT_LINE('d2s_d2m : ' || d2s_d2m);
END;
/

DECLARE
v_d2s INTERVAL DAY TO SECOND;
d2s_h2m VARCHAR;
BEGIN
v_d2s := '9';
SELECT v_d2s::INTERVAL HOUR TO MINUTE INTO d2s_h2m;
DBMS_OUTPUT.PUT_LINE('d2s_h2m : ' || d2s_h2m);
END;
/

DECLARE
v_d2s INTERVAL DAY TO SECOND;
d2s_h2s VARCHAR;
BEGIN
v_d2s := '9';
SELECT v_d2s::INTERVAL HOUR TO SECOND INTO d2s_h2s;
DBMS_OUTPUT.PUT_LINE('d2s_h2s : ' || d2s_h2s);
END;
/

DECLARE
v_d2s INTERVAL DAY TO SECOND;
d2s_m2s VARCHAR;
BEGIN
v_d2s := '9';
SELECT v_d2s::INTERVAL MINUTE TO SECOND INTO d2s_m2s;
DBMS_OUTPUT.PUT_LINE('d2s_m2s : ' || d2s_m2s);
END;
/

//INTERVAL HOUR TO MINUTE 的转换
DECLARE
v_h2m INTERVAL HOUR TO MINUTE;
h2m_y VARCHAR;
BEGIN
v_h2m := '9';
SELECT v_h2m::INTERVAL YEAR INTO h2m_y;
DBMS_OUTPUT.PUT_LINE('h2m_y : ' || h2m_y);
END;
/

DECLARE
v_h2m INTERVAL HOUR TO MINUTE;
h2m_m VARCHAR;
BEGIN
v_h2m := '9';
SELECT v_h2m::INTERVAL MONTH INTO h2m_m;
DBMS_OUTPUT.PUT_LINE('h2m_m : ' || h2m_m);
END;
/

DECLARE
v_h2m INTERVAL HOUR TO MINUTE;
h2m_d VARCHAR;
BEGIN
v_h2m := '9';
SELECT v_h2m::INTERVAL DAY INTO h2m_d;
DBMS_OUTPUT.PUT_LINE('h2m_d : ' || h2m_d);
END;
/

DECLARE
v_h2m INTERVAL HOUR TO MINUTE;
h2m_h VARCHAR;
BEGIN
v_h2m := '9';
SELECT v_h2m::INTERVAL HOUR INTO h2m_h;
DBMS_OUTPUT.PUT_LINE('h2m_h : ' || h2m_h);
END;
/

DECLARE
v_h2m INTERVAL HOUR TO MINUTE;
h2m_mi VARCHAR;
BEGIN
v_h2m := '9';
SELECT v_h2m::INTERVAL MINUTE INTO h2m_mi;
DBMS_OUTPUT.PUT_LINE('h2m_mi : ' || h2m_mi);
END;
/

DECLARE
v_h2m INTERVAL HOUR TO MINUTE;
h2m_s VARCHAR;
BEGIN
v_h2m := '9';
SELECT v_h2m::INTERVAL SECOND INTO h2m_s;
DBMS_OUTPUT.PUT_LINE('h2m_s : ' || h2m_s);
END;
/

DECLARE
v_h2m INTERVAL HOUR TO MINUTE;
h2m_y2m VARCHAR;
BEGIN
v_h2m := '9';
SELECT v_h2m::INTERVAL YEAR TO MONTH INTO h2m_y2m;
DBMS_OUTPUT.PUT_LINE('h2m_y2m : ' || h2m_y2m);
END;
/

DECLARE
v_h2m INTERVAL HOUR TO MINUTE;
h2m_d2h VARCHAR;
BEGIN
v_h2m := '9';
SELECT v_h2m::INTERVAL DAY TO HOUR INTO h2m_d2h;
DBMS_OUTPUT.PUT_LINE('h2m_d2h : ' || h2m_d2h);
END;
/

DECLARE
v_h2m INTERVAL HOUR TO MINUTE;
h2m_d2m VARCHAR;
BEGIN
v_h2m := '9';
SELECT v_h2m::INTERVAL DAY TO MINUTE INTO h2m_d2m;
DBMS_OUTPUT.PUT_LINE('h2m_d2m : ' || h2m_d2m);
END;
/

DECLARE
v_h2m INTERVAL HOUR TO MINUTE;
h2m_d2s VARCHAR;
BEGIN
v_h2m := '9';
SELECT v_h2m::INTERVAL DAY TO SECOND INTO h2m_d2s;
DBMS_OUTPUT.PUT_LINE('h2m_d2s : ' || h2m_d2s);
END;
/

DECLARE
v_h2m INTERVAL HOUR TO MINUTE;
h2m_h2s VARCHAR;
BEGIN
v_h2m := '9';
SELECT v_h2m::INTERVAL HOUR TO SECOND INTO h2m_h2s;
DBMS_OUTPUT.PUT_LINE('h2m_h2s : ' || h2m_h2s);
END;
/

DECLARE
v_h2m INTERVAL HOUR TO MINUTE;
h2m_m2s VARCHAR;
BEGIN
v_h2m := '9';
SELECT v_h2m::INTERVAL MINUTE TO SECOND INTO h2m_m2s;
DBMS_OUTPUT.PUT_LINE('h2m_m2s : ' || h2m_m2s);
END;
/

//INTERVAL HOUR TO SECOND 的转换
DECLARE
v_h2s INTERVAL HOUR TO SECOND;
h2s_y VARCHAR;
BEGIN
v_h2s := '9';
SELECT v_h2s::INTERVAL YEAR INTO h2s_y;
DBMS_OUTPUT.PUT_LINE('h2s_y : ' || h2s_y);
END;
/

DECLARE
v_h2s INTERVAL HOUR TO SECOND;
h2s_m VARCHAR;
BEGIN
v_h2s := '9';
SELECT v_h2s::INTERVAL MONTH INTO h2s_m;
DBMS_OUTPUT.PUT_LINE('h2s_m : ' || h2s_m);
END;
/

DECLARE
v_h2s INTERVAL HOUR TO SECOND;
h2s_d VARCHAR;
BEGIN
v_h2s := '9';
SELECT v_h2s::INTERVAL DAY INTO h2s_d;
DBMS_OUTPUT.PUT_LINE('h2s_d : ' || h2s_d);
END;
/

DECLARE
v_h2s INTERVAL HOUR TO SECOND;
h2s_h VARCHAR;
BEGIN
v_h2s := '9';
SELECT v_h2s::INTERVAL HOUR INTO h2s_h;
DBMS_OUTPUT.PUT_LINE('h2s_h : ' || h2s_h);
END;
/

DECLARE
v_h2s INTERVAL HOUR TO SECOND;
h2s_mi VARCHAR;
BEGIN
v_h2s := '9';
SELECT v_h2s::INTERVAL MINUTE INTO h2s_mi;
DBMS_OUTPUT.PUT_LINE('h2s_mi : ' || h2s_mi);
END;
/

DECLARE
v_h2s INTERVAL HOUR TO SECOND;
h2s_s VARCHAR;
BEGIN
v_h2s := '9';
SELECT v_h2s::INTERVAL SECOND INTO h2s_s;
DBMS_OUTPUT.PUT_LINE('h2s_s : ' || h2s_s);
END;
/

DECLARE
v_h2s INTERVAL HOUR TO SECOND;
h2s_y2m VARCHAR;
BEGIN
v_h2s := '9';
SELECT v_h2s::INTERVAL YEAR TO MONTH INTO h2s_y2m;
DBMS_OUTPUT.PUT_LINE('h2s_y2m : ' || h2s_y2m);
END;
/

DECLARE
v_h2s INTERVAL HOUR TO SECOND;
h2s_d2h VARCHAR;
BEGIN
v_h2s := '9';
SELECT v_h2s::INTERVAL DAY TO HOUR INTO h2s_d2h;
DBMS_OUTPUT.PUT_LINE('h2s_d2h : ' || h2s_d2h);
END;
/

DECLARE
v_h2s INTERVAL HOUR TO SECOND;
h2s_d2m VARCHAR;
BEGIN
v_h2s := '9';
SELECT v_h2s::INTERVAL DAY TO MINUTE INTO h2s_d2m;
DBMS_OUTPUT.PUT_LINE('h2s_d2m : ' || h2s_d2m);
END;
/

DECLARE
v_h2s INTERVAL HOUR TO SECOND;
h2s_d2s VARCHAR;
BEGIN
v_h2s := '9';
SELECT v_h2s::INTERVAL DAY TO SECOND INTO h2s_d2s;
DBMS_OUTPUT.PUT_LINE('h2s_d2s : ' || h2s_d2s);
END;
/

DECLARE
v_h2s INTERVAL HOUR TO SECOND;
h2s_h2m VARCHAR;
BEGIN
v_h2s := '9';
SELECT v_h2s::INTERVAL HOUR TO MINUTE INTO h2s_h2m;
DBMS_OUTPUT.PUT_LINE('h2s_h2m : ' || h2s_h2m);
END;
/

DECLARE
v_h2s INTERVAL HOUR TO SECOND;
h2s_m2s VARCHAR;
BEGIN
v_h2s := '9';
SELECT v_h2s::INTERVAL MINUTE TO SECOND INTO h2s_m2s;
DBMS_OUTPUT.PUT_LINE('h2s_m2s : ' || h2s_m2s);
END;
/

//INTERVAL MINUTE TO SECOND 的转换
DECLARE
v_m2s INTERVAL MINUTE TO SECOND;
m2s_y VARCHAR;
BEGIN
v_m2s := '9';
SELECT v_m2s::INTERVAL YEAR INTO m2s_y;
DBMS_OUTPUT.PUT_LINE('m2s_y : ' || m2s_y);
END;
/

DECLARE
v_m2s INTERVAL MINUTE TO SECOND;
m2s_m VARCHAR;
BEGIN
v_m2s := '9';
SELECT v_m2s::INTERVAL MONTH INTO m2s_m;
DBMS_OUTPUT.PUT_LINE('m2s_m : ' || m2s_m);
END;
/

DECLARE
v_m2s INTERVAL MINUTE TO SECOND;
m2s_d VARCHAR;
BEGIN
v_m2s := '9';
SELECT v_m2s::INTERVAL DAY INTO m2s_d;
DBMS_OUTPUT.PUT_LINE('m2s_d : ' || m2s_d);
END;
/

DECLARE
v_m2s INTERVAL MINUTE TO SECOND;
m2s_h VARCHAR;
BEGIN
v_m2s := '9';
SELECT v_m2s::INTERVAL HOUR INTO m2s_h;
DBMS_OUTPUT.PUT_LINE('m2s_h : ' || m2s_h);
END;
/

DECLARE
v_m2s INTERVAL MINUTE TO SECOND;
m2s_mi VARCHAR;
BEGIN
v_m2s := '9';
SELECT v_m2s::INTERVAL MINUTE INTO m2s_mi;
DBMS_OUTPUT.PUT_LINE('m2s_mi : ' || m2s_mi);
END;
/

DECLARE
v_m2s INTERVAL MINUTE TO SECOND;
m2s_s VARCHAR;
BEGIN
v_m2s := '9';
SELECT v_m2s::INTERVAL SECOND INTO m2s_s;
DBMS_OUTPUT.PUT_LINE('m2s_s : ' || m2s_s);
END;
/

DECLARE
v_m2s INTERVAL MINUTE TO SECOND;
m2s_y2m VARCHAR;
BEGIN
v_m2s := '9';
SELECT v_m2s::INTERVAL YEAR TO MONTH INTO m2s_y2m;
DBMS_OUTPUT.PUT_LINE('m2s_y2m : ' || m2s_y2m);
END;
/

DECLARE
v_m2s INTERVAL MINUTE TO SECOND;
m2s_d2h VARCHAR;
BEGIN
v_m2s := '9';
SELECT v_m2s::INTERVAL DAY TO HOUR INTO m2s_d2h;
DBMS_OUTPUT.PUT_LINE('m2s_d2h : ' || m2s_d2h);
END;
/

DECLARE
v_m2s INTERVAL MINUTE TO SECOND;
m2s_d2m VARCHAR;
BEGIN
v_m2s := '9';
SELECT v_m2s::INTERVAL DAY TO MINUTE INTO m2s_d2m;
DBMS_OUTPUT.PUT_LINE('m2s_d2m : ' || m2s_d2m);
END;
/

DECLARE
v_m2s INTERVAL MINUTE TO SECOND;
m2s_d2s VARCHAR;
BEGIN
v_m2s := '9';
SELECT v_m2s::INTERVAL DAY TO SECOND INTO m2s_d2s;
DBMS_OUTPUT.PUT_LINE('m2s_d2s : ' || m2s_d2s);
END;
/

DECLARE
v_m2s INTERVAL MINUTE TO SECOND;
m2s_h2m VARCHAR;
BEGIN
v_m2s := '9';
SELECT v_m2s::INTERVAL HOUR TO MINUTE INTO m2s_h2m;
DBMS_OUTPUT.PUT_LINE('m2s_h2m : ' || m2s_h2m);
END;
/

DECLARE
v_m2s INTERVAL MINUTE TO SECOND;
m2s_h2s VARCHAR;
BEGIN
v_m2s := '9';
SELECT v_m2s::INTERVAL HOUR TO SECOND INTO m2s_h2s;
DBMS_OUTPUT.PUT_LINE('m2s_h2s : ' || m2s_h2s);
END;
/