!4 XG-TYPE-INTERVAL-EXPR-001 字面量表达式 : 完整标准字面量表达式
SELECT INTERVAL '1-0' YEAR;
SELECT INTERVAL '0-1' MONTH;
SELECT INTERVAL '1 0:00:00' DAY;
SELECT INTERVAL '1:00:00' HOUR;
SELECT INTERVAL '0:01:00' MINUTE;
SELECT INTERVAL '0:00:01' SECOND;
SELECT INTERVAL '1-2' YEAR TO MONTH;
SELECT INTERVAL '1 2:00:00' DAY TO HOUR;
SELECT INTERVAL '1 0:02:00' DAY TO MINUTE;
SELECT INTERVAL '1 0:00:02.345' DAY TO SECOND;
SELECT INTERVAL '1:23:00' HOUR TO MINUTE;
SELECT INTERVAL '1:23:45.678' HOUR TO SECOND;
SELECT INTERVAL '1:23:45.678' MINUTE TO SECOND;

!4 XG-TYPE-INTERVAL-EXPR-002 字面量表达式 : 简写合法字面量表达式
SELECT INTERVAL '1' YEAR;
SELECT INTERVAL '1' MONTH;
SELECT INTERVAL '1' DAY;
SELECT INTERVAL '1' HOUR;
SELECT INTERVAL '1' MINUTE;
SELECT INTERVAL '1.2' SECOND;
SELECT INTERVAL '1' YEAR TO MONTH;
SELECT INTERVAL '1' DAY TO HOUR;
SELECT INTERVAL '1' DAY TO MINUTE;
SELECT INTERVAL '1.2' DAY TO SECOND;
SELECT INTERVAL '1' HOUR TO MINUTE;
SELECT INTERVAL '1.2' HOUR TO SECOND;
SELECT INTERVAL '1.2' MINUTE TO SECOND;

!4 XG-TYPE-INTERVAL-EXPR-003 字面量表达式 : 前导零字面量表达式
SELECT INTERVAL '01-01' YEAR;
SELECT INTERVAL '01-01' MONTH;
SELECT INTERVAL '01 01:00:00' DAY;
SELECT INTERVAL '01:00:00' HOUR;
SELECT INTERVAL '01:00:00' MINUTE;
SELECT INTERVAL '01:00:00' SECOND;
SELECT INTERVAL '01-01' YEAR TO MONTH;
SELECT INTERVAL '01 02:00:00' DAY TO HOUR;
SELECT INTERVAL '01 02:03:00' DAY TO MINUTE;
SELECT INTERVAL '01 02:03:04.050' DAY TO SECOND;
SELECT INTERVAL '01:02:00' HOUR TO MINUTE;
SELECT INTERVAL '01:02:03.040' HOUR TO SECOND;
SELECT INTERVAL '01:02:03.040' MINUTE TO SECOND;

!4 XG-TYPE-INTERVAL-EXPR-004 字面量表达式 : 字面量与带强转表达式的运算
SELECT INTERVAL '1' YEAR = '1'::INTERVAL YEAR;
SELECT INTERVAL '1' MONTH = '1'::INTERVAL MONTH;
SELECT INTERVAL '1' DAY = '1'::INTERVAL DAY;
SELECT INTERVAL '1' HOUR = '1'::INTERVAL HOUR;
SELECT INTERVAL '1' MINUTE = '1'::INTERVAL MINUTE;
SELECT INTERVAL '1' SECOND = '1'::INTERVAL SECOND;
SELECT INTERVAL '1' YEAR TO MONTH = '1'::INTERVAL YEAR TO MONTH;
SELECT INTERVAL '1' DAY TO HOUR = '1'::INTERVAL DAY TO HOUR;
SELECT INTERVAL '1' DAY TO MINUTE = '1'::INTERVAL DAY TO MINUTE;
SELECT INTERVAL '1' DAY TO SECOND = '1'::INTERVAL DAY TO SECOND;
SELECT INTERVAL '1' HOUR TO MINUTE = '1'::INTERVAL HOUR TO MINUTE;
SELECT INTERVAL '1' HOUR TO SECOND = '1'::INTERVAL HOUR TO SECOND;
SELECT INTERVAL '1' MINUTE TO SECOND = '1'::INTERVAL MINUTE TO SECOND;

!4 XG-TYPE-INTERVAL-EXPR-005 字面量表达式 : BETWEEN 范围表达式
SELECT INTERVAL '5' YEAR BETWEEN INTERVAL '1' YEAR AND INTERVAL '9' YEAR;
SELECT INTERVAL '5' MONTH BETWEEN INTERVAL '1' MONTH AND INTERVAL '9' MONTH;
SELECT INTERVAL '5' DAY BETWEEN INTERVAL '1' DAY; AND INTERVAL '9' DAY
SELECT INTERVAL '5' HOUR BETWEEN INTERVAL '1' HOUR AND INTERVAL '9' HOUR;
SELECT INTERVAL '5' MINUTE BETWEEN INTERVAL '1' MINUTE AND INTERVAL '9' MINUTE;
SELECT INTERVAL '5' SECOND BETWEEN INTERVAL '1' SECOND AND INTERVAL '9' SECOND;
SELECT INTERVAL '5' YEAR TO MONTH BETWEEN INTERVAL '1' YEAR TO MONTH AND INTERVAL '9' YEAR TO MONTH;
SELECT INTERVAL '5' DAY TO HOUR BETWEEN INTERVAL '1' DAY TO HOUR AND INTERVAL '9' DAY TO HOUR;
SELECT INTERVAL '5' DAY TO MINUTE BETWEEN INTERVAL '1' DAY TO MINUTE AND INTERVAL '9' DAY TO MINUTE;
SELECT INTERVAL '5' DAY TO SECOND BETWEEN INTERVAL '1' DAY TO SECOND AND INTERVAL '9' DAY TO SECOND;
SELECT INTERVAL '5' HOUR TO MINUTE BETWEEN INTERVAL '1' HOUR TO MINUTE AND INTERVAL '9' HOUR TO MINUTE;
SELECT INTERVAL '5' HOUR TO SECOND BETWEEN INTERVAL '1' HOUR TO SECOND AND INTERVAL '9' HOUR TO SECOND;
SELECT INTERVAL '5' MINUTE TO SECOND BETWEEN INTERVAL '1' MINUTE TO SECOND AND INTERVAL '9' MINUTE TO SECOND;


!4 XG-TYPE-INTERVAL-EXPR-006 字面量表达式 : 带正、负号的字面量表达式
SELECT INTERVAL '+1' YEAR;
SELECT INTERVAL '+1' MONTH;
SELECT INTERVAL '+1' DAY;
SELECT INTERVAL '+1' HOUR;
SELECT INTERVAL '+1' MINUTE;
SELECT INTERVAL '+1' SECOND;
SELECT INTERVAL '+1' YEAR TO MONTH;
SELECT INTERVAL '+1' DAY TO HOUR;
SELECT INTERVAL '+1' DAY TO MINUTE;
SELECT INTERVAL '+1' DAY TO SECOND;
SELECT INTERVAL '+1' HOUR TO MINUTE;
SELECT INTERVAL '+1' HOUR TO SECOND;
SELECT INTERVAL '+1' MINUTE TO SECOND;

SELECT INTERVAL '-1' YEAR;
SELECT INTERVAL '-1' MONTH;
SELECT INTERVAL '-1' DAY;
SELECT INTERVAL '-1' HOUR;
SELECT INTERVAL '-1' MINUTE;
SELECT INTERVAL '-1' SECOND;
SELECT INTERVAL '-1' YEAR TO MONTH;
SELECT INTERVAL '-1' DAY TO HOUR;
SELECT INTERVAL '-1' DAY TO MINUTE;
SELECT INTERVAL '-1' DAY TO SECOND;
SELECT INTERVAL '-1' HOUR TO MINUTE;
SELECT INTERVAL '-1' HOUR TO SECOND;
SELECT INTERVAL '-1' MINUTE TO SECOND;
