!4 XG-TYPE-INTERVAL-EXPR-001 正负间隔表达式 : 负间隔字面量表达式
SELECT INTERVAL '-1-0' YEAR;
SELECT INTERVAL '-0-1' MONTH;
SELECT INTERVAL '-1 0:00:00' DAY;
SELECT INTERVAL '-1:00:00' HOUR;
SELECT INTERVAL '-0:01:00' MINUTE;
SELECT INTERVAL '-0:00:01.23' SECOND;
SELECT INTERVAL '-1-2' YEAR TO MONTH;
SELECT INTERVAL '-1 2:00:00' DAY TO HOUR;
SELECT INTERVAL '-1 2:34:00' DAY TO MINUTE;
SELECT INTERVAL '-1 2:34:56.78' DAY TO SECOND;
SELECT INTERVAL '-1:23:00' HOUR TO MINUTE;
SELECT INTERVAL '-1:23:45.67' HOUR TO SECOND;
SELECT INTERVAL '-1:23.45' MINUTE TO SECOND;

!4 XG-TYPE-INTERVAL-EXPR-002 正负间隔表达式 : 负间隔强转表达式
SELECT '-1-0'::INTERVAL YEAR;
SELECT '-0-1'::INTERVAL MONTH;
SELECT '-1 0:00:00'::INTERVAL DAY;
SELECT '-1:00:00'::INTERVAL HOUR;
SELECT '-0:01:00'::INTERVAL MINUTE;
SELECT '-0:00:01.23'::INTERVAL SECOND;
SELECT '-1-2'::INTERVAL YEAR TO MONTH;
SELECT '-1 2:00:00'::INTERVAL DAY TO HOUR;
SELECT '-1 2:3'::INTERVAL DAY TO MINUTE;
SELECT '-1 2:34:56.78'::INTERVAL DAY TO SECOND;
SELECT '-1:23:00'::INTERVAL HOUR TO MINUTE;
SELECT '-1:23:45.67'::INTERVAL HOUR TO SECOND;
SELECT '-1:23.45'::INTERVAL MINUTE TO SECOND;

!4 XG-TYPE-INTERVAL-EXPR-003 正负间隔表达式 : 正负间隔表达式运算

//INTERVAL YEAR
SELECT '1'::INTERVAL YEAR + INTERVAL '-1' YEAR;
SELECT '1'::INTERVAL YEAR + INTERVAL '-1' MONTH;
SELECT '1'::INTERVAL YEAR + INTERVAL '-1' DAY;
SELECT '1'::INTERVAL YEAR + INTERVAL '-1' HOUR;
SELECT '1'::INTERVAL YEAR + INTERVAL '-1' MINUTE;
SELECT '1'::INTERVAL YEAR + INTERVAL '-1' SECOND;
SELECT '1'::INTERVAL YEAR + INTERVAL '-1-0' YEAR TO MONTH;
SELECT '1'::INTERVAL YEAR + INTERVAL '-1 0' DAY TO HOUR;
SELECT '1'::INTERVAL YEAR + INTERVAL '-1 0:0' DAY TO MINUTE;
SELECT '1'::INTERVAL YEAR + INTERVAL '-1 0:0:0' DAY TO SECOND;
SELECT '1'::INTERVAL YEAR + INTERVAL '-1:0' HOUR TO MINUTE;
SELECT '1'::INTERVAL YEAR + INTERVAL '-1:0:0' HOUR TO SECOND;
SELECT '1'::INTERVAL YEAR + INTERVAL '-1:0.0' MINUTE TO SECOND;

//INTERVAL MONTH
SELECT '1'::INTERVAL MONTH + INTERVAL '-1' YEAR;
SELECT '1'::INTERVAL MONTH + INTERVAL '-1' MONTH;
SELECT '1'::INTERVAL MONTH + INTERVAL '-1' DAY;
SELECT '1'::INTERVAL MONTH + INTERVAL '-1' HOUR;
SELECT '1'::INTERVAL MONTH + INTERVAL '-1' MINUTE;
SELECT '1'::INTERVAL MONTH + INTERVAL '-1' SECOND;
SELECT '1'::INTERVAL MONTH + INTERVAL '-1-0' YEAR TO MONTH;
SELECT '1'::INTERVAL MONTH + INTERVAL '-1 0' DAY TO HOUR;
SELECT '1'::INTERVAL MONTH + INTERVAL '-1 0:0' DAY TO MINUTE;
SELECT '1'::INTERVAL MONTH + INTERVAL '-1 0:0:0' DAY TO SECOND;
SELECT '1'::INTERVAL MONTH + INTERVAL '-1:0' HOUR TO MINUTE;
SELECT '1'::INTERVAL MONTH + INTERVAL '-1:0:0' HOUR TO SECOND;
SELECT '1'::INTERVAL MONTH + INTERVAL '-1:0.0' MINUTE TO SECOND;

//INTERVAL DAY
SELECT '1'::INTERVAL DAY + INTERVAL '-1' YEAR;
SELECT '1'::INTERVAL DAY + INTERVAL '-1' MONTH;
SELECT '1'::INTERVAL DAY + INTERVAL '-1' DAY;
SELECT '1'::INTERVAL DAY + INTERVAL '-2' HOUR;
SELECT '1'::INTERVAL DAY + INTERVAL '-1' MINUTE;
SELECT '1'::INTERVAL DAY + INTERVAL '-1' SECOND;
SELECT '1'::INTERVAL DAY + INTERVAL '-1-0' YEAR TO MONTH;
SELECT '1'::INTERVAL DAY + INTERVAL '-1 0' DAY TO HOUR;
SELECT '1'::INTERVAL DAY + INTERVAL '-1 0:0' DAY TO MINUTE;
SELECT '1'::INTERVAL DAY + INTERVAL '-1 0:0:0' DAY TO SECOND;
SELECT '1'::INTERVAL DAY + INTERVAL '-1:0' HOUR TO MINUTE;
SELECT '1'::INTERVAL DAY + INTERVAL '-1:0:0' HOUR TO SECOND;
SELECT '1'::INTERVAL DAY + INTERVAL '-1:0.0' MINUTE TO SECOND;

//INTERVAL HOUR
SELECT '1'::INTERVAL HOUR + INTERVAL '-1' YEAR;
SELECT '1'::INTERVAL HOUR + INTERVAL '-1' MONTH;
SELECT '1'::INTERVAL HOUR + INTERVAL '-1' DAY;
SELECT '1'::INTERVAL HOUR + INTERVAL '-1' HOUR;
SELECT '1'::INTERVAL HOUR + INTERVAL '-1' MINUTE;
SELECT '1'::INTERVAL HOUR + INTERVAL '-1' SECOND;
SELECT '1'::INTERVAL HOUR + INTERVAL '-1-0' YEAR TO MONTH;
SELECT '1'::INTERVAL HOUR + INTERVAL '-1 0' DAY TO HOUR;
SELECT '1'::INTERVAL HOUR + INTERVAL '-1 0:0' DAY TO MINUTE;
SELECT '1'::INTERVAL HOUR + INTERVAL '-1 0:0:0' DAY TO SECOND;
SELECT '1'::INTERVAL HOUR + INTERVAL '-1:0' HOUR TO MINUTE;
SELECT '1'::INTERVAL HOUR + INTERVAL '-1:0:0' HOUR TO SECOND;
SELECT '1'::INTERVAL HOUR + INTERVAL '-1:0.0' MINUTE TO SECOND;

//INTERVAL MINUTE
SELECT '1'::INTERVAL MINUTE + INTERVAL '-1' YEAR;
SELECT '1'::INTERVAL MINUTE + INTERVAL '-1' MONTH;
SELECT '1'::INTERVAL MINUTE + INTERVAL '-1' DAY;
SELECT '1'::INTERVAL MINUTE + INTERVAL '-1' HOUR;
SELECT '1'::INTERVAL MINUTE + INTERVAL '-1' MINUTE;
SELECT '1'::INTERVAL MINUTE + INTERVAL '-1' SECOND;
SELECT '1'::INTERVAL MINUTE + INTERVAL '-1-0' YEAR TO MONTH;
SELECT '1'::INTERVAL MINUTE + INTERVAL '-1 0' DAY TO HOUR;
SELECT '1'::INTERVAL MINUTE + INTERVAL '-1 0:0' DAY TO MINUTE;
SELECT '1'::INTERVAL MINUTE + INTERVAL '-1 0:0:0' DAY TO SECOND;
SELECT '1'::INTERVAL MINUTE + INTERVAL '-1:0' HOUR TO MINUTE;
SELECT '1'::INTERVAL MINUTE + INTERVAL '-1:0:0' HOUR TO SECOND;
SELECT '1'::INTERVAL MINUTE + INTERVAL '-1:0.0' MINUTE TO SECOND;

//INTERVAL SECOND
SELECT '1'::INTERVAL SECOND + INTERVAL '-1' YEAR;
SELECT '1'::INTERVAL SECOND + INTERVAL '-1' MONTH;
SELECT '1'::INTERVAL SECOND + INTERVAL '-1' DAY;
SELECT '1'::INTERVAL SECOND + INTERVAL '-1' HOUR;
SELECT '1'::INTERVAL SECOND + INTERVAL '-1' MINUTE;
SELECT '1'::INTERVAL SECOND + INTERVAL '-1' SECOND;
SELECT '1'::INTERVAL SECOND + INTERVAL '-1-0' YEAR TO MONTH;
SELECT '1'::INTERVAL SECOND + INTERVAL '-1 0' DAY TO HOUR;
SELECT '1'::INTERVAL SECOND + INTERVAL '-1 0:0' DAY TO MINUTE;
SELECT '1'::INTERVAL SECOND + INTERVAL '-1 0:0:0' DAY TO SECOND;
SELECT '1'::INTERVAL SECOND + INTERVAL '-1:0' HOUR TO MINUTE;
SELECT '1'::INTERVAL SECOND + INTERVAL '-1:0:0' HOUR TO SECOND;
SELECT '1'::INTERVAL SECOND + INTERVAL '-1:0.0' MINUTE TO SECOND;

//INTERVAL YEAR TO MONTH
SELECT '1-0'::INTERVAL YEAR TO MONTH + INTERVAL '-1' YEAR;
SELECT '1-0'::INTERVAL YEAR TO MONTH + INTERVAL '-1' MONTH;
SELECT '1-0'::INTERVAL YEAR TO MONTH + INTERVAL '-1' DAY;
SELECT '1-0'::INTERVAL YEAR TO MONTH + INTERVAL '-1' HOUR;
SELECT '1-0'::INTERVAL YEAR TO MONTH + INTERVAL '-1' MINUTE;
SELECT '1-0'::INTERVAL YEAR TO MONTH + INTERVAL '-1' SECOND;
SELECT '1-0'::INTERVAL YEAR TO MONTH + INTERVAL '-1-0' YEAR TO MONTH;
SELECT '1-0'::INTERVAL YEAR TO MONTH + INTERVAL '-1 0' DAY TO HOUR;
SELECT '1-0'::INTERVAL YEAR TO MONTH + INTERVAL '-1 0:0' DAY TO MINUTE;
SELECT '1-0'::INTERVAL YEAR TO MONTH + INTERVAL '-1 0:0:0' DAY TO SECOND;
SELECT '1-0'::INTERVAL YEAR TO MONTH + INTERVAL '-1:0' HOUR TO MINUTE;
SELECT '1-0'::INTERVAL YEAR TO MONTH + INTERVAL '-1:0:0' HOUR TO SECOND;
SELECT '1-0'::INTERVAL YEAR TO MONTH + INTERVAL '-1:0.0' MINUTE TO SECOND;

//INTERVAL DAY TO HOUR
SELECT '1 0'::INTERVAL DAY TO HOUR + INTERVAL '-1' YEAR;
SELECT '1 0'::INTERVAL DAY TO HOUR + INTERVAL '-1' MONTH;
SELECT '1 0'::INTERVAL DAY TO HOUR + INTERVAL '-1' DAY;
SELECT '1 0'::INTERVAL DAY TO HOUR + INTERVAL '-1' HOUR;
SELECT '1 0'::INTERVAL DAY TO HOUR + INTERVAL '-1' MINUTE;
SELECT '1 0'::INTERVAL DAY TO HOUR + INTERVAL '-1' SECOND;
SELECT '1 0'::INTERVAL DAY TO HOUR + INTERVAL '-1-0' YEAR TO MONTH;
SELECT '1 0'::INTERVAL DAY TO HOUR + INTERVAL '-1 0' DAY TO HOUR;
SELECT '1 0'::INTERVAL DAY TO HOUR + INTERVAL '-1 0:0' DAY TO MINUTE;
SELECT '1 0'::INTERVAL DAY TO HOUR + INTERVAL '-1 0:0:0' DAY TO SECOND;
SELECT '1 0'::INTERVAL DAY TO HOUR + INTERVAL '-1:0' HOUR TO MINUTE;
SELECT '1 0'::INTERVAL DAY TO HOUR + INTERVAL '-1:0:0' HOUR TO SECOND;
SELECT '1 0'::INTERVAL DAY TO HOUR + INTERVAL '-1:0.0' MINUTE TO SECOND;

//INTERVAL DAY TO MINUTE
SELECT '1 0:0'::INTERVAL DAY TO MINUTE + INTERVAL '-1' YEAR;
SELECT '1 0:0'::INTERVAL DAY TO MINUTE + INTERVAL '-1' MONTH;
SELECT '1 0:0'::INTERVAL DAY TO MINUTE + INTERVAL '-1' DAY;
SELECT '1 0:0'::INTERVAL DAY TO MINUTE + INTERVAL '-1' HOUR;
SELECT '1 0:0'::INTERVAL DAY TO MINUTE + INTERVAL '-1' MINUTE;
SELECT '1 0:0'::INTERVAL DAY TO MINUTE + INTERVAL '-1' SECOND;
SELECT '1 0:0'::INTERVAL DAY TO MINUTE + INTERVAL '-1-0' YEAR TO MONTH;
SELECT '1 0:0'::INTERVAL DAY TO MINUTE + INTERVAL '-1 0' DAY TO HOUR;
SELECT '1 0:0'::INTERVAL DAY TO MINUTE + INTERVAL '-1 0:0' DAY TO MINUTE;
SELECT '1 0:0'::INTERVAL DAY TO MINUTE + INTERVAL '-1 0:0:0' DAY TO SECOND;
SELECT '1 0:0'::INTERVAL DAY TO MINUTE + INTERVAL '-1:0' HOUR TO MINUTE;
SELECT '1 0:0'::INTERVAL DAY TO MINUTE + INTERVAL '-1:0:0' HOUR TO SECOND;
SELECT '1 0:0'::INTERVAL DAY TO MINUTE + INTERVAL '-1:0.0' MINUTE TO SECOND;

//INTERVAL DAY TO SECOND
SELECT '1 0:0:0'::INTERVAL DAY TO SECOND + INTERVAL '-1' YEAR;
SELECT '1 0:0:0'::INTERVAL DAY TO SECOND + INTERVAL '-1' MONTH;
SELECT '1 0:0:0'::INTERVAL DAY TO SECOND + INTERVAL '-1' DAY;
SELECT '1 0:0:0'::INTERVAL DAY TO SECOND + INTERVAL '-1' HOUR;
SELECT '1 0:0:0'::INTERVAL DAY TO SECOND + INTERVAL '-1' MINUTE;
SELECT '1 0:0:0'::INTERVAL DAY TO SECOND + INTERVAL '-1' SECOND;
SELECT '1 0:0:0'::INTERVAL DAY TO SECOND + INTERVAL '-1-0' YEAR TO MONTH;
SELECT '1 0:0:0'::INTERVAL DAY TO SECOND + INTERVAL '-1 0' DAY TO HOUR;
SELECT '1 0:0:0'::INTERVAL DAY TO SECOND + INTERVAL '-1 0:0' DAY TO MINUTE;
SELECT '1 0:0:0'::INTERVAL DAY TO SECOND + INTERVAL '-1 0:0:0' DAY TO SECOND;
SELECT '1 0:0:0'::INTERVAL DAY TO SECOND + INTERVAL '-1:0' HOUR TO MINUTE;
SELECT '1 0:0:0'::INTERVAL DAY TO SECOND + INTERVAL '-1:0:0' HOUR TO SECOND;
SELECT '1 0:0:0'::INTERVAL DAY TO SECOND + INTERVAL '-1:0.0' MINUTE TO SECOND;

//INTERVAL HOUR TO MINUTE
SELECT '1:0'::INTERVAL HOUR TO MINUTE + INTERVAL '-1' YEAR;
SELECT '1:0'::INTERVAL HOUR TO MINUTE + INTERVAL '-1' MONTH;
SELECT '1:0'::INTERVAL HOUR TO MINUTE + INTERVAL '-1' DAY;
SELECT '1:0'::INTERVAL HOUR TO MINUTE + INTERVAL '-1' HOUR;
SELECT '1:0'::INTERVAL HOUR TO MINUTE + INTERVAL '-1' MINUTE;
SELECT '1:0'::INTERVAL HOUR TO MINUTE + INTERVAL '-1' SECOND;
SELECT '1:0'::INTERVAL HOUR TO MINUTE + INTERVAL '-1-0' YEAR TO MONTH;
SELECT '1:0'::INTERVAL HOUR TO MINUTE + INTERVAL '-1 0' DAY TO HOUR;
SELECT '1:0'::INTERVAL HOUR TO MINUTE + INTERVAL '-1 0:0' DAY TO MINUTE;
SELECT '1:0'::INTERVAL HOUR TO MINUTE + INTERVAL '-1 0:0:0' DAY TO SECOND;
SELECT '1:0'::INTERVAL HOUR TO MINUTE + INTERVAL '-1:0' HOUR TO MINUTE;
SELECT '1:0'::INTERVAL HOUR TO MINUTE + INTERVAL '-1:0:0' HOUR TO SECOND;
SELECT '1:0'::INTERVAL HOUR TO MINUTE + INTERVAL '-1:0.0' MINUTE TO SECOND;

//INTERVAL HOUR TO SECOND
SELECT '1:0:0'::INTERVAL HOUR TO SECOND + INTERVAL '-1' YEAR;
SELECT '1:0:0'::INTERVAL HOUR TO SECOND + INTERVAL '-1' MONTH;
SELECT '1:0:0'::INTERVAL HOUR TO SECOND + INTERVAL '-1' DAY;
SELECT '1:0:0'::INTERVAL HOUR TO SECOND + INTERVAL '-1' HOUR;
SELECT '1:0:0'::INTERVAL HOUR TO SECOND + INTERVAL '-1' MINUTE;
SELECT '1:0:0'::INTERVAL HOUR TO SECOND + INTERVAL '-1' SECOND;
SELECT '1:0:0'::INTERVAL HOUR TO SECOND + INTERVAL '-1-0' YEAR TO MONTH;
SELECT '1:0:0'::INTERVAL HOUR TO SECOND + INTERVAL '-1 0' DAY TO HOUR;
SELECT '1:0:0'::INTERVAL HOUR TO SECOND + INTERVAL '-1 0:0' DAY TO MINUTE;
SELECT '1:0:0'::INTERVAL HOUR TO SECOND + INTERVAL '-1 0:0:0' DAY TO SECOND;
SELECT '1:0:0'::INTERVAL HOUR TO SECOND + INTERVAL '-1:0' HOUR TO MINUTE;
SELECT '1:0:0'::INTERVAL HOUR TO SECOND + INTERVAL '-1:0:0' HOUR TO SECOND;
SELECT '1:0:0'::INTERVAL HOUR TO SECOND + INTERVAL '-1:0.0' MINUTE TO SECOND;

//INTERVAL MINUTE TO SECOND
SELECT '1:0.0'::INTERVAL MINUTE TO SECOND + INTERVAL '-1' YEAR;
SELECT '1:0.0'::INTERVAL MINUTE TO SECOND + INTERVAL '-1' MONTH;
SELECT '1:0.0'::INTERVAL MINUTE TO SECOND + INTERVAL '-1' DAY;
SELECT '1:0.0'::INTERVAL MINUTE TO SECOND + INTERVAL '-1' HOUR;
SELECT '1:0.0'::INTERVAL MINUTE TO SECOND + INTERVAL '-1' MINUTE;
SELECT '1:0.0'::INTERVAL MINUTE TO SECOND + INTERVAL '-1' SECOND;
SELECT '1:0.0'::INTERVAL MINUTE TO SECOND + INTERVAL '-1-0' YEAR TO MONTH;
SELECT '1:0.0'::INTERVAL MINUTE TO SECOND + INTERVAL '-1 0' DAY TO HOUR;
SELECT '1:0.0'::INTERVAL MINUTE TO SECOND + INTERVAL '-1 0:0' DAY TO MINUTE;
SELECT '1:0.0'::INTERVAL MINUTE TO SECOND + INTERVAL '-1 0:0:0' DAY TO SECOND;
SELECT '1:0.0'::INTERVAL MINUTE TO SECOND + INTERVAL '-1:0' HOUR TO MINUTE;
SELECT '1:0.0'::INTERVAL MINUTE TO SECOND + INTERVAL '-1:0:0' HOUR TO SECOND;
SELECT '1:0.0'::INTERVAL MINUTE TO SECOND + INTERVAL '-1:0.0' MINUTE TO SECOND;
