!4 XG-TYPE-INTERVAL-EXPR-001 NULL运算表达式

// " + " 操作符测试 : NULL
SELECT INTERVAL '1' YEAR + NULL;
SELECT INTERVAL '1' MONTH + NULL;
SELECT INTERVAL '1' DAY + NULL;
SELECT INTERVAL '1' HOUR + NULL;
SELECT INTERVAL '1' MINUTE + NULL;
SELECT INTERVAL '1' SECOND + NULL;
SELECT INTERVAL '1' YEAR TO MONTH + NULL;
SELECT INTERVAL '1' DAY TO HOUR + NULL;
SELECT INTERVAL '1' DAY TO MINUTE + NULL;
SELECT INTERVAL '1' DAY TO SECOND + NULL;
SELECT INTERVAL '1' HOUR TO MINUTE + NULL;
SELECT INTERVAL '1' HOUR TO SECOND + NULL;
SELECT INTERVAL '1' MINUTE TO SECOND + NULL;

// " - " 操作符测试 : NULL
SELECT INTERVAL '1' YEAR - NULL;
SELECT INTERVAL '1' MONTH - NULL;
SELECT INTERVAL '1' DAY - NULL;
SELECT INTERVAL '1' HOUR - NULL;
SELECT INTERVAL '1' MINUTE - NULL;
SELECT INTERVAL '1' SECOND - NULL;
SELECT INTERVAL '1' YEAR TO MONTH - NULL;
SELECT INTERVAL '1' DAY TO HOUR - NULL;
SELECT INTERVAL '1' DAY TO MINUTE - NULL;
SELECT INTERVAL '1' DAY TO SECOND - NULL;
SELECT INTERVAL '1' HOUR TO MINUTE - NULL;
SELECT INTERVAL '1' HOUR TO SECOND - NULL;
SELECT INTERVAL '1' MINUTE TO SECOND - NULL;

// " * " 操作符测试 : NULL
SELECT INTERVAL '1' YEAR * NULL;
SELECT INTERVAL '1' MONTH * NULL;
SELECT INTERVAL '1' DAY * NULL;
SELECT INTERVAL '1' HOUR * NULL;
SELECT INTERVAL '1' MINUTE * NULL;
SELECT INTERVAL '1' SECOND * NULL;
SELECT INTERVAL '1' YEAR TO MONTH * NULL;
SELECT INTERVAL '1' DAY TO HOUR * NULL;
SELECT INTERVAL '1' DAY TO MINUTE * NULL;
SELECT INTERVAL '1' DAY TO SECOND * NULL;
SELECT INTERVAL '1' HOUR TO MINUTE * NULL;
SELECT INTERVAL '1' HOUR TO SECOND * NULL;
SELECT INTERVAL '1' MINUTE TO SECOND * NULL;

// " / " 操作符测试 : NULL
SELECT INTERVAL '1' YEAR / NULL;
SELECT INTERVAL '1' MONTH / NULL;
SELECT INTERVAL '1' DAY / NULL;
SELECT INTERVAL '1' HOUR / NULL;
SELECT INTERVAL '1' MINUTE / NULL;
SELECT INTERVAL '1' SECOND / NULL;
SELECT INTERVAL '1' YEAR TO MONTH / NULL;
SELECT INTERVAL '1' DAY TO HOUR / NULL;
SELECT INTERVAL '1' DAY TO MINUTE / NULL;
SELECT INTERVAL '1' DAY TO SECOND / NULL;
SELECT INTERVAL '1' HOUR TO MINUTE / NULL;
SELECT INTERVAL '1' HOUR TO SECOND / NULL;
SELECT INTERVAL '1' MINUTE TO SECOND / NULL;

// " < " 操作符测试 : NULL
SELECT INTERVAL '1' YEAR < NULL;
SELECT INTERVAL '1' MONTH < NULL;
SELECT INTERVAL '1' DAY < NULL;
SELECT INTERVAL '1' HOUR < NULL;
SELECT INTERVAL '1' MINUTE < NULL;
SELECT INTERVAL '1' SECOND < NULL;
SELECT INTERVAL '1' YEAR TO MONTH < NULL;
SELECT INTERVAL '1' DAY TO HOUR < NULL;
SELECT INTERVAL '1' DAY TO MINUTE < NULL;
SELECT INTERVAL '1' DAY TO SECOND < NULL;
SELECT INTERVAL '1' HOUR TO MINUTE < NULL;
SELECT INTERVAL '1' HOUR TO SECOND < NULL;
SELECT INTERVAL '1' MINUTE TO SECOND < NULL;

// " <= " 操作符测试 : NULL
SELECT INTERVAL '1' YEAR <= NULL;
SELECT INTERVAL '1' MONTH <= NULL;
SELECT INTERVAL '1' DAY <= NULL;
SELECT INTERVAL '1' HOUR <= NULL;
SELECT INTERVAL '1' MINUTE <= NULL;
SELECT INTERVAL '1' SECOND <= NULL;
SELECT INTERVAL '1' YEAR TO MONTH <= NULL;
SELECT INTERVAL '1' DAY TO HOUR <= NULL;
SELECT INTERVAL '1' DAY TO MINUTE <= NULL;
SELECT INTERVAL '1' DAY TO SECOND <= NULL;
SELECT INTERVAL '1' HOUR TO MINUTE <= NULL;
SELECT INTERVAL '1' HOUR TO SECOND <= NULL;
SELECT INTERVAL '1' MINUTE TO SECOND <= NULL;

// " <> " 操作符测试 : NULL
SELECT INTERVAL '1' YEAR <> NULL;
SELECT INTERVAL '1' MONTH <> NULL;
SELECT INTERVAL '1' DAY <> NULL;
SELECT INTERVAL '1' HOUR <> NULL;
SELECT INTERVAL '1' MINUTE <> NULL;
SELECT INTERVAL '1' SECOND <> NULL;
SELECT INTERVAL '1' YEAR TO MONTH <> NULL;
SELECT INTERVAL '1' DAY TO HOUR <> NULL;
SELECT INTERVAL '1' DAY TO MINUTE <> NULL;
SELECT INTERVAL '1' DAY TO SECOND <> NULL;
SELECT INTERVAL '1' HOUR TO MINUTE <> NULL;
SELECT INTERVAL '1' HOUR TO SECOND <> NULL;
SELECT INTERVAL '1' MINUTE TO SECOND <> NULL;

// " = " 操作符测试 : NULL
SELECT INTERVAL '1' YEAR = NULL;
SELECT INTERVAL '1' MONTH = NULL;
SELECT INTERVAL '1' DAY = NULL;
SELECT INTERVAL '1' HOUR = NULL;
SELECT INTERVAL '1' MINUTE = NULL;
SELECT INTERVAL '1' SECOND = NULL;
SELECT INTERVAL '1' YEAR TO MONTH = NULL;
SELECT INTERVAL '1' DAY TO HOUR = NULL;
SELECT INTERVAL '1' DAY TO MINUTE = NULL;
SELECT INTERVAL '1' DAY TO SECOND = NULL;
SELECT INTERVAL '1' HOUR TO MINUTE = NULL;
SELECT INTERVAL '1' HOUR TO SECOND = NULL;
SELECT INTERVAL '1' MINUTE TO SECOND = NULL;

// " > " 操作符测试 : NULL
SELECT INTERVAL '1' YEAR > NULL;
SELECT INTERVAL '1' MONTH > NULL;
SELECT INTERVAL '1' DAY > NULL;
SELECT INTERVAL '1' HOUR > NULL;
SELECT INTERVAL '1' MINUTE > NULL;
SELECT INTERVAL '1' SECOND > NULL;
SELECT INTERVAL '1' YEAR TO MONTH > NULL;
SELECT INTERVAL '1' DAY TO HOUR > NULL;
SELECT INTERVAL '1' DAY TO MINUTE > NULL;
SELECT INTERVAL '1' DAY TO SECOND > NULL;
SELECT INTERVAL '1' HOUR TO MINUTE > NULL;
SELECT INTERVAL '1' HOUR TO SECOND > NULL;
SELECT INTERVAL '1' MINUTE TO SECOND > NULL;

// " >= " 操作符测试 : NULL
SELECT INTERVAL '1' YEAR >= NULL;
SELECT INTERVAL '1' MONTH >= NULL;
SELECT INTERVAL '1' DAY >= NULL;
SELECT INTERVAL '1' HOUR >= NULL;
SELECT INTERVAL '1' MINUTE >= NULL;
SELECT INTERVAL '1' SECOND >= NULL;
SELECT INTERVAL '1' YEAR TO MONTH >= NULL;
SELECT INTERVAL '1' DAY TO HOUR >= NULL;
SELECT INTERVAL '1' DAY TO MINUTE >= NULL;
SELECT INTERVAL '1' DAY TO SECOND >= NULL;
SELECT INTERVAL '1' HOUR TO MINUTE >= NULL;
SELECT INTERVAL '1' HOUR TO SECOND >= NULL;
SELECT INTERVAL '1' MINUTE TO SECOND >= NULL;

// " || " 操作符测试 : NULL
SELECT INTERVAL '1' YEAR || NULL;
SELECT INTERVAL '1' MONTH || NULL;
SELECT INTERVAL '1' DAY || NULL;
SELECT INTERVAL '1' HOUR || NULL;
SELECT INTERVAL '1' MINUTE || NULL;
SELECT INTERVAL '1' SECOND || NULL;
SELECT INTERVAL '1' YEAR TO MONTH || NULL;
SELECT INTERVAL '1' DAY TO HOUR || NULL;
SELECT INTERVAL '1' DAY TO MINUTE || NULL;
SELECT INTERVAL '1' DAY TO SECOND || NULL;
SELECT INTERVAL '1' HOUR TO MINUTE || NULL;
SELECT INTERVAL '1' HOUR TO SECOND || NULL;
SELECT INTERVAL '1' MINUTE TO SECOND || NULL;
