!4 XG-TYPE-INTERVAL-EXPR-001 格式非法表达式 : 分隔符错误

{{{
    - 在 年月 格式中,分隔符限制为只能使用 '-',其余字符会报错
    - 在 天时分秒 格式中,天与时分秒之间有分隔符,在插入数值带特殊符号时,会将特殊符号之前的内容识别为天,之后的内容识别为时分秒,特殊符号会被识别为分隔符
    - interval hour 格式特殊,走了 day to hour 格式,因此在这里插入分隔符也是可以通过的
}}}

SELECT '1,0'::INTERVAL YEAR;
SELECT '1/0'::INTERVAL MONTH;
SELECT '1|0'::INTERVAL DAY;
SELECT '1,0'::INTERVAL HOUR;
SELECT '1+0'::INTERVAL MINUTE;
SELECT '1@0'::INTERVAL SECOND;
SELECT '1.2.3'::INTERVAL YEAR TO MONTH;
SELECT '1|0'::INTERVAL DAY TO HOUR;
SELECT '1;0:0'::INTERVAL DAY TO MINUTE;
SELECT '1|0:0:0'::INTERVAL DAY TO SECOND;
SELECT '1|0'::INTERVAL HOUR TO MINUTE;
SELECT '1|0:0'::INTERVAL HOUR TO SECOND;
SELECT '1|0.0'::INTERVAL MINUTE TO SECOND;

!4 XG-TYPE-INTERVAL-EXPR-002 格式非法表达式 : 时分秒格式错误
SELECT 'A:B:C'::INTERVAL DAY;
SELECT 'A:B:C'::INTERVAL HOUR;
SELECT 'A:B:C'::INTERVAL MINUTE;
SELECT 'A:B:C'::INTERVAL SECOND;
SELECT 'A:B:C'::INTERVAL DAY TO HOUR;
SELECT 'A:B:C'::INTERVAL DAY TO MINUTE;
SELECT 'A:B:C'::INTERVAL DAY TO SECOND;
SELECT 'A:B:C'::INTERVAL HOUR TO MINUTE;
SELECT 'A:B:C'::INTERVAL HOUR TO SECOND;
SELECT 'A:B:C'::INTERVAL MINUTE TO SECOND;

!4 XG-TYPE-INTERVAL-EXPR-003 格式非法表达式 : 字面量值与类型定义不匹配
SELECT '1 0'::INTERVAL YEAR;
SELECT '0 1'::INTERVAL MONTH;
SELECT '1-0-0-0'::INTERVAL DAY;
SELECT '0-1-0-0'::INTERVAL HOUR;
SELECT '0-1-0'::INTERVAL MINUTE;
SELECT '0-0-1.234'::INTERVAL SECOND;
SELECT '0 1'::INTERVAL YEAR TO MONTH;
SELECT '0-1-2-3'::INTERVAL DAY TO HOUR;
SELECT '0-1-2-3'::INTERVAL DAY TO MINUTE;
SELECT '0-1-2-3.456'::INTERVAL DAY TO SECOND;
SELECT '0-1-0'::INTERVAL HOUR TO MINUTE;
SELECT '1-2-3.456'::INTERVAL HOUR TO SECOND;
SELECT '1-2-3.456'::INTERVAL MINUTE TO SECOND;

!4 XG-TYPE-INTERVAL-EXPR-004 格式非法表达式 : 多余非法字符

{{{ 当输入值不为纯数值格式时,会自动走标准字面量格式,因此特殊符号会被识别为分隔符,不会报特殊字符的错误,而其余非合法字母等字符会被报错}}}

SELECT '1-@x'::INTERVAL YEAR;
SELECT '1#'::INTERVAL MONTH;
SELECT '1$'::INTERVAL DAY;
SELECT '1%'::INTERVAL HOUR;
SELECT '1&'::INTERVAL MINUTE;
SELECT '1%'::INTERVAL SECOND;
SELECT '1-0x'::INTERVAL YEAR TO MONTH;
SELECT '1 0q'::INTERVAL DAY TO HOUR;
SELECT '1 0:0@'::INTERVAL DAY TO MINUTE;
SELECT '1 0:0:0!'::INTERVAL DAY TO SECOND;
SELECT '1:0~'::INTERVAL HOUR TO MINUTE;
SELECT '1:0:0}'::INTERVAL HOUR TO SECOND;
SELECT '1:0.0['::INTERVAL MINUTE TO SECOND;

!4 XG-TYPE-INTERVAL-EXPR-005 格式非法表达式 : 字面量为空字符串
SELECT ''::INTERVAL YEAR;
SELECT ''::INTERVAL MONTH;
SELECT ''::INTERVAL DAY;
SELECT ''::INTERVAL HOUR;
SELECT ''::INTERVAL MINUTE;
SELECT ''::INTERVAL SECOND;
SELECT ''::INTERVAL YEAR TO MONTH;
SELECT ''::INTERVAL DAY TO HOUR;
SELECT ''::INTERVAL DAY TO MINUTE;
SELECT ''::INTERVAL DAY TO SECOND;
SELECT ''::INTERVAL HOUR TO MINUTE;
SELECT ''::INTERVAL HOUR TO SECOND;
SELECT ''::INTERVAL MINUTE TO SECOND;

!4 XG-TYPE-INTERVAL-EXPR-006 格式非法表达式 : 字面量不带单引号

{{{非复合类型不支持将 TINYINT 转为 INTERVAL 格式,因此会报错}}}

SELECT INTERVAL '123' YEAR , INTERVAL 123 YEAR;
SELECT INTERVAL '123' MONTH , INTERVAL 123 MONTH;
SELECT INTERVAL '123' DAY , INTERVAL 123 DAY;
SELECT INTERVAL '123' HOUR , INTERVAL 123 HOUR;
SELECT INTERVAL '123' MINUTE , INTERVAL 123 MINUTE;
SELECT INTERVAL '123' SECOND , INTERVAL 123 SECOND;
SELECT INTERVAL '123' YEAR TO MONTH , INTERVAL 123 YEAR TO MONTH;
SELECT INTERVAL '123' DAY TO HOUR , INTERVAL 123 DAY TO HOUR;
SELECT INTERVAL '123' DAY TO MINUTE , INTERVAL 123 DAY TO MINUTE;
SELECT INTERVAL '123' DAY TO SECOND , INTERVAL 123 DAY TO SECOND;
SELECT INTERVAL '123' HOUR TO MINUTE , INTERVAL 123 HOUR TO MINUTE;
SELECT INTERVAL '123' HOUR TO SECOND , INTERVAL 123 HOUR TO SECOND;
SELECT INTERVAL '123' MINUTE TO SECOND , INTERVAL 123 MINUTE TO SECOND;
